### ISSUE TITLE
GradebookNG needs to use updated Date picker

### ISSUE THREAD

**Issue by ncaidin** [sakaiproject/sakai#1298]
GradebookNG appears to use the old date/time picker. Would be good to have consistency with the latest. 

<img width="890" alt="calendar_datepicker" src="https://cloud.githubusercontent.com/assets/5399652/11343668/0bb28de2-91db-11e5-91b2-e69d78eb5ce3.png">

**Comment by ncaidin** [comment]
Please refer to an open issue for the original Gradebook - https://jira.sakaiproject.org/browse/SAK-26293

**Comment by ottenhoff** [comment]
Your screenshot is not from GradebookNG

**Comment by ncaidin** [comment]
Thanks. Not sure how I missed that I was in the wrong gradebook.
