### ISSUE TITLE
Drag reorder not sticking with browser refresh

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1336]
_From @payten on April 1, 2015 4:8_

Hi @steveswinsburg,

After dragging and dropping a column I've been noticing the sort order isn't sticking on a page refresh, however when I hit the tool reset action the new sort order applies.  Smells of caching?

Cheers
Payten

_Copied from original issue: steveswinsburg/gradebookNG#35_

**Comment by steveswinsburg** [comment]
_From @payten on April 1, 2015 6:17_

Hm.. looks like there's a similar issue when entering a grade too e.g. I enter a new grade value; after refresh of page it reverts to the previous value; after reset of tool it displays the new value.

**Comment by steveswinsburg** [comment]
Interesting. The wicket models are updating but the page refresh is pulling the current version of the page from the cache due to the ?pageid param being in the URL. Investigating.

**Comment by steveswinsburg** [comment]
Ok so we can add a different rendering strategy which seems to fix this. The only thing is it makes the URLs a bit ugly.

getRequestCycleSettings().setRenderStrategy(IRequestCycleSettings.RenderStrategy.ONE_PASS_RENDER); 

It's in but commented out in the Application class. Let me know your thoughts.

**Comment by steveswinsburg** [comment]
I think I might leave this as a known issue for now. This adds some ugly bits to the URL. There are a few ways to fix this so we can look at in in depth soon.

**Comment by steveswinsburg** [comment]
Refs:
http://apache-wicket.1842946.n4.nabble.com/Stateful-pages-without-page-Id-in-the-url-td3816663.html

**Comment by kyleblythe** [comment]
Hey @steveswinsburg ,

I'm seeing some add'l weirdness cropping up with ordering when using both refresh and tool reset. It does not seem to be very consistent, so I've tried to capture a video showing item ordering not get reflected when resetting/refreshing with no categories enabled:

http://www.screencast.com/t/ubQrm0JFB9B

And here's some funkiness with the tool reset when categories are enabled. Everything seems fine after the first reorder, then, after a second reorder, the reset takes you back to the original order:

http://www.screencast.com/t/fXxdPhhzv1

**Comment by steveswinsburg** [comment]
Hey @kyleblythe - with that first issue, it actually looks ok except for the homework item switching position with the one next to it, but they never change back to their default which means it is saving/refreshing ok. However I think there may be a minor issue with the assignment sort order in the backend since they swap places rather than back to where they were originally.

With the second, again I think this could be down to the categorised sort order. The refresh we were seeing ebfore was that it would return to the exact original state as before, this is different and I think is a separate issue.

@payten, are you able to take a look at the sort order and see whats up? If you need to, disable the mod I made in this ticket to compare, ie comment out:
`getRequestCycleSettings().setRenderStrategy(RenderStrategy.ONE_PASS_RENDER);`

**Comment by payten** [comment]
Hm.. something fishy is definitely happening.  I'm seeing a single drag-and-drop reorder sticking nicely.  But if I do two drap-and-drops in a row the second isn't persisting on refresh.  I'll continue to explore.. but hopefully this means the refresh strategy is ok and it's just a regular bug 😅

**Comment by kyleblythe** [comment]
Nice one! This is working exactly as it should now. Closing this one out!
