### ISSUE TITLE
Add logging into various steps for timing purposes

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1351]
_From @steveswinsburg on May 4, 2015 12:58_

Add some logging into various steps for performance measurement of various tasks. This is to get some rudimentary figured before we hook up our full tests.

_Copied from original issue: steveswinsburg/gradebookNG#64_

**Comment by steveswinsburg** [comment]
Ok I've added some logging in. It just prints to the console so you can see whats taking the time. The back end time is about 10ms per student. On a local site with 300 or so users, this means just to get the data is about 3500ms. I then see about 1 second before it appears in my browser. It is interesting to have a console open and render the main page to see it all happening.

https://gist.github.com/steveswinsburg/4af27827a628793bf8b9

@payten can you run this up and see what numbers you get, then run it up again with the XML parsing ofthe categories and see if that changes anything? It would also be interesting to get some console logging for the javascript at key points when its attaching stuff to the page, just to see if there is anything there. I am going to try to get that 10ms down a bit. I am also very interested to see how this is on the build server, will have to get a console open as well.

**Comment by steveswinsburg** [comment]
_From @payten on May 7, 2015 2:36_

Hi @steveswinsburg,

Here are my times without the category-XML wrangling for a gradebook with 400 students and 11 gradebook items: https://gist.github.com/payten/7d8acc2268fa5a73b6c1

And with the category XML call: https://gist.github.com/payten/1854cbc8652ce27c8ea7

The XML category stuff adds ~100ms to the request:

     Time for [getCategorizedAssignmentOrder - start] was: 39683ms
     Time for [getCategorizedAssignmentOrder - finish] was: 39793ms

**Comment by steveswinsburg** [comment]
Hey @payten is that on your local machine? Interesting that the time per
student on the backend is about 100-150ms each compared to 10ms on mine.
What database are you running?

Sounds like I could add some more logging deeper in the gradebook calls to
see what part is taking 10 times as long.

Cheers
Steve

**Comment by steveswinsburg** [comment]
_From @payten on May 7, 2015 3:42_

I'm running MySQL 5.6.15-osx10.7-x86_64 on my MacBook (all local, so no latency).

How many grade items did you have? I have 11.

Edit: Just redid the timing with 1 grade item: https://gist.github.com/payten/4b956a556471f56b700e.  Much quicker!  About 10x quicker ;)

**Comment by steveswinsburg** [comment]
OK yes it looks like the time increases significantly as the number of gradebook items increases. I have 20 items and 5 users and now get around 40ms per user: https://gist.github.com/steveswinsburg/087594bc07d48a064106

I'll ramp this up on my other machine where I have hundreds of users and test again.

I'll also add additional timings inside the logic to see where its getting held up. I may be able to refactor the way the grade matrix is built, otherwise it might be in the Gradebook Service API.

**Comment by steveswinsburg** [comment]
Looking further, whether or not an assignment has grades doesn't seem to matter, its in the retrieval of the grades. See the gist where the first few students don't have grades (90-100ms per student) and the last two do have grades (same times). This may be due to some inefficient iterations in building the matrix. I originally did it this way so we had the comments in the returned structure but I think in the interests of performance we can ditch that. I'll rewrite this section to more closely match the original gradebook retrieval.

Also note that ALL grades are being retrieved even if we have just the first 50 selected, then its paged on the front end. We might be able to ditch the pager too, which would be good for infinite scrolling.

https://gist.github.com/steveswinsburg/bef6cddb8b7592543aa5

**Comment by steveswinsburg** [comment]
Ok I'm closing this one as I think I have everything I need to get this sorted. See #73

**Comment by steveswinsburg** [comment]
This needs to be backed out now the perf issues are sorted.

**Comment by steveswinsburg** [comment]
Leaving it in whilst we add more features, this is a simple one to back out later.

**Comment by steveswinsburg** [comment]
Will convert to log debug and leave it in 👌

**Comment by payten** [comment]
This is working nicely 👍
