### ISSUE TITLE
Enhance editing notifications to notify edits on the API directly

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1352]
_From @steveswinsburg on May 4, 2015 13:0_

Polling notifications should respect the Sakai event system as well so we know about edits in the original gradebook. This assumes that an edit fires an event (check this). If so, we can listen for it and add it to the cache.

_Copied from original issue: steveswinsburg/gradebookNG#65_

**Comment by steveswinsburg** [comment]
The gradebook API is inconsistent in its posting of events. Some actions send the `gradebook.updateItemScore` event, others don't do anything.

For the event that is posted, the data is:
`/gradebook/bd659b9b-4daa-403a-9b82-b5ddd38e33db/item 3bb/276aca5b-0820-4861-9046-b05e4527d952/99.0/instructor`

Which translates to: `/gradebook/siteid/assignmentname/studentuuid/grade/rolethatdidit`

**Comment by steveswinsburg** [comment]
- The event sending needs to be made consistent in the GradebookService
- There needs to be an event listener in the GBNG business service to pick up the event. However as above the data isn't great so it would need a DB hit to pickup the rest of the details.
- The event listener would then pop the editing notification into the map

**Comment by jeffpasch** [comment]
not a good solution for this one. closing.
