### ISSUE TITLE
DataTable and popup accessibility

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1357]
_From @payten on June 16, 2015 1:10_

I've started a first pass at making the table more accessible for screen readers etc and I'm stuck on introducing a row header as per the spec e.g. http://www.w3.org/WAI/tutorials/tables/two-headers/.

Is there a Wicket-way of adding an `AttributeModifier` to all &lt;thead&gt;&lt;tr&gt;&lt;th&gt; to introduce `scope='col'` and a modifying the student name cell to be a &lt;th scope='row'&gt;?

Thanks!

_Copied from original issue: steveswinsburg/gradebookNG#109_

**Comment by steveswinsburg** [comment]
_From @payten on June 16, 2015 1:59_

I've also been investigating adding aria attributes to the various popups in the interface.  `aria-haspopup` identifies an element as invoking a popup and `role="dialog"` will identify the resulting popup as a modal.  Similarly for our dropdown menus where `role="menu"`. 

The trick is associating the link with the popup it invokes via an `aria-labelledby` or `aria-controls` using element IDs.  

Is there a quick way via the wicket templates to insert a unique ID for these elements?  I've been finding the only way is to introduce a wicket:id and corresponding component and then refactor the Java to ensure any nested wicket components are added within.  Is there a simple decorator class I can use for modifying these elements?

For example the dropdown:
&lt;a href="#" class="dropdown-toggle"&gt;&lt;span class="caret"&gt;&lt;/a&gt;
&lt;ul class=dropdown-menu"&gt;... 

might become something like this: 

&lt;a href="#" id="link123" aria-controls="menu123" aria-haspopup="true" aria-label="Show context menu" class="dropdown-toggle"&gt;&lt;span role="presentation" class="caret"&gt;&lt;/a&gt;
&lt;ul id="menu123" role="menu" aria-labelledby="link123" class=dropdown-menu"&gt;

It gets pretty dense pretty quick!  Are there any Wicket accessibility plugins that might make this easier for us?  I wonder if it's more efficient to apply these dynamically with Javascript?

**Comment by steveswinsburg** [comment]
_From @payten on June 16, 2015 6:26_

Here's my first pass at adding aria attributes/roles: https://github.com/steveswinsburg/gradebookNG/compare/master...payten:accessibility-round-one

Admittedly the ARIA spec is as confusing as the implementations of the ARIA attributes are varied for different screen readers!  Without testing it in JAWS I'm not quite sure how helpful they are... but it's a start.  

It'd be nice to at least have the spreadsheet table in line with the accessibility guidelines, so will aim for that next.

**Comment by steveswinsburg** [comment]
Hi Payten,
There is a Jira here for adding some aria attributes to the modal windows:
https://issues.apache.org/jira/browse/WICKET-4472

Says its fixed in Wicket 6 so it might already be doable?

Re the uniqueID and dense HTML, yes we can set the ID in HTML and make sure it sticks by making a change in the class via `setMarkupId("something")`, however we will get collisions if that's inside a repeater like the table. 

The best bet here is to determine what elements we want the attributes on then use `AttributeModifier` to add them in the wicket component. We have access to the generated markupid once inside the class.

For the simple ones like `role="menu"` etc they could just go in the HTML directly as you've done 👍.

For the table headers, I havent tried but could we do an `AttributeModifier` on the relevant columns in `GradebookPage`? Those dynamic columns have both a header (getHeader) and body section (populteItem). We should be able to add something there?

**Comment by steveswinsburg** [comment]
_From @payten on June 17, 2015 5:6_

Thanks @steveswinsburg.  Yep I think WICKET-4472 is working - I'm seeing a `role="dialog"` on those popups and with the `aria-haspopup` I've added to the button it might be good enough.

Back to the table... I've been looking into adding the `scope="col"` to the header cell and I'm unable to modify the &lt;th&gt; via `getHeader`.  The problem is that `getHeader` is a &lt;span&gt; within the &lt;th&gt; and `super.getHeader(componentId).getParent()` return NULL.  Any ideas?  I can do it in the Javascript but trying to be Wicket-ty. 

Likewise, I'm still a little unsure how to change the Student name &lt;td&gt; to a &lt;th&gt;.  Any Wicket magic?  I can easily set `scope="row"` in StudentNameCellPanel.java using `getParent().add(new AttributeModifier("scope", "row"));` in `onInitialize`.

**Comment by steveswinsburg** [comment]
Hmm I might have to ask on the wicket mailing list. Let me see what they
say.

**Comment by steveswinsburg** [comment]
OK I got this back. This means we need to rework the cells a bit which is not impossible, but is a big change. We may need to subclass Item and pass that in so we can override the onComponentTag method and set the tag name to 'th'. IMO lets leave this as an open issue and fix it after the main bits are done. 

-

It's a little bit finicky, but it can be done:

        DataTable dataTable = new DefaultDataTable<Contact, String>("table", columns, new SortableContactDataProvider(), 8) {
            protected Item<IColumn<Contact, String>> newCellItem(final String id, final int index, final IModel<IColumn<Contact, String>> model)
            {
                    return new Item<IColumn<Contact, String>>(id, index, model) {
                        @Override
                        protected void onComponentTag(ComponentTag tag) {
                            super.onComponentTag(tag);

                            // parent is the repeater for the cells, its parent is the row
                            Contact contact = (Contact) getParent().getParent().getDefaultModelObject();
                            if (contact.isSpecíal()) {
                                tag.setName("th");
                            }
                        }
                    };
                }
        };

In a future version we might want to change #newCellItem() to get a reference to the row's model - that would remove the need to lookup the row object from the  grandparent.

**Comment by steveswinsburg** [comment]
_From @payten on June 22, 2015 22:23_

Oo wowzers :)  Thanks for chasing that down!

And yep no probs.  I'll prepare the accessibility changes I've already done for a PR in the meantime.

**Comment by steveswinsburg** [comment]
**Discussed 29/1/2016**
Probably doable, might be a little tricky. We are getting the accessibility review done so if they say that this is a priority we can address it.

**Comment by payten** [comment]
This is no longer an issue.
