### ISSUE TITLE
Add error messages at top of table with "view details"

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1358]
_From @jeffpasch on June 22, 2015 5:19_

When there are errors on the page, display error message above the grading table with the following:
 - X no. of errors on this page
 - "View details"
 - Expanding "view details" will show (1) the location of each error using coordinates (i.e., user and item) and (2) the reason for error (e.g., concurrent edit). The coordinates of the error should be a link, which will take the user to that cell in the table (to address the error).

_Copied from original issue: steveswinsburg/gradebookNG#120_

**Comment by kyleblythe** [comment]
This is an old issue - has already been addressed through other issues.
