### ISSUE TITLE
Fix UI when no assignments or students exist

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1359]
_From @steveswinsburg on June 23, 2015 13:10_

If you create new site with no students or assignments, the gradebook tool shows some empty columns. We could probably intercept this and make it nicer.

![screen shot 2015-06-23 at 11 08 22 pm](https://cloud.githubusercontent.com/assets/129129/8306646/e37b8ce4-19fc-11e5-9796-686997f575b0.png)

_Copied from original issue: steveswinsburg/gradebookNG#127_

**Comment by steveswinsburg** [comment]
Hey @payten, made a fix to the javascript $table as well as catered for both no users and no assignments.

**Comment by steveswinsburg** [comment]
This work is now done. Message will be displayed when no assignments and/or no students. Ready for test.

**Comment by kyleblythe** [comment]
Awesome. Looks great. 

![image](https://cloud.githubusercontent.com/assets/11447474/11874372/39a9e666-a4ad-11e5-90db-7461dee53a32.png)

We may want to consider adding something similar to the student view when no items have been released to students - they currently see the header row, with no content below.

**Comment by kyleblythe** [comment]
Confirmed.
