### ISSUE TITLE
Add the settings page

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1360]
_From @steveswinsburg on June 26, 2015 23:34_

Add the settings page. This is a rollup of all of the settings pages in Gradebook _classique_

_Copied from original issue: steveswinsburg/gradebookNG#132_

**Comment by steveswinsburg** [comment]
This should now be finalised with the addition of the PR #1407. Lots of backend changes had to occur for this one but its in pretty good shape now.

**Comment by steveswinsburg** [comment]
@kyleblythe this one is ready to test.

**Comment by kyleblythe** [comment]
This is up, running, and gorgeous. We've got other issues open for specific bugs/enhancements in Settings, so I think we can close this one out.
