### ISSUE TITLE
Make course grade column header clickable to sort asc/desc

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1361]
_From @steveswinsburg on July 11, 2015 22:53_

Make course grade column header clickable to sort asc/desc

_Copied from original issue: steveswinsburg/gradebookNG#141_

**Comment by steveswinsburg** [comment]
Hey @kyleblythe just checking if we have a requirement for this? I don't have much in the original ticket so can't remember if this is something I came up with myself or something we discussed.

**Comment by steveswinsburg** [comment]
**Discussed 29/1/2016**
Make this a clickable heading, consistent with the other assignments. Clicking will toggle the sort by asc/desc. 

**Implementation notes**
Need to add a comparator, an entry to GradebookUiSettings to store it (noting that each thing that is clicked clears the sorting of the other fields), pass this setting in to the matrix builder, then add a block for sorting using the comparator.

**Comment by steveswinsburg** [comment]
I've got this assigned to me as it is straightforward and was going to give to @amiedavis if possible.

**Comment by steveswinsburg** [comment]
Note that this is trickier now that we have the GbCourseGradeLabel which does all of the logic. That logic is being moved to the service for generating a display string

**Comment by kyleblythe** [comment]
Hi @steveswinsburg 

Interesting...a few things:

* When sorting ascending/descending by course grade, there's no up/down arrow that displays to the far right of the column header letting you know that it's sorted/which way it's sorted:

![image](https://cloud.githubusercontent.com/assets/11447474/15053125/0c9fe4d2-12cf-11e6-953c-59464d551645.png)

* Also, as you can see in the screenshot above, the "Course Grade" text seems to have some padding on top that the other column headers do not have.

* As of right now, once you start sorting by the "Course Grade" column, you cannot then start sorting by another column. I can click on other column headers and the page will refresh. Then, even though there's a sorting up/down arrow on that item's column header, the table itself is still sorted by the course grade:

![image](https://cloud.githubusercontent.com/assets/11447474/15053240/a3902bc2-12cf-11e6-8b75-c75d911f7f3b.png)

* Lastly, it looks like, even when you're sorting ascending, the actual percentages for the students are still being sorted descending. So, even though F's will display at the top, the percentages themselves still descend:
![image](https://cloud.githubusercontent.com/assets/11447474/15053202/6a065dae-12cf-11e6-9d3b-80a4b895beee.png)

**Comment by payten** [comment]
> Also, as you can see in the screenshot above, the "Course Grade" text seems to have some padding on top that the other column headers do not have.

This one is due to some CSS that can now be removed! Namely `#gradebookGrades .gb-course-grade > div {
  padding: 6px 0;
}`

**Comment by steveswinsburg** [comment]
Discussed on the call, currently this sorts by the course grade display string which is built using the settings. Could just sort by points only but then course grade overrides would not be considered.

**Comment by payten** [comment]
I'll have a go at introducing a course grade sort string that will allow sorting by grade letter (including the overridden value) then the point value.  Kinda like this maybe: <padded course grade letter as point><padded point score>. For example:
0000003700000100 == A- (100)
0000004000000120 == A+ (120)
0000003700000090 == A- (90) (B overridden as A-)

**Comment by steveswinsburg** [comment]
Ok cool. The GbCourseGradeFormatter figures out the display string, it could also determine the sort string at the same time. So if you returned a String[] and picked out the values for both display and sort and stored the sort in the GbCourseGrade. Then just flip the comparator over to use the sort string :thought_balloon: :ok_hand:

**Comment by jeffpasch** [comment]
Hi @payten in your example above, I think A+ would need to be 42. But I think you may we using a different scheme for this anyway. We'll need to be able to account for anything from A+ down to F-. I think we'll also want to account for Pass / Not Pass: http://www.screencast.com/t/fedQWy7QgY0

**Comment by payten** [comment]
Yep, good catch @jeffpasch.  I think we'll need to base our letter ordering off the grade scheme completely -- especially as instructors can create completely custom/random grading schemes if they desire.

The pull request above aims to use this grading scheme to order the letter grade (taking into account the overridden grade letter value) and then secondarily orders by points.

**Comment by steveswinsburg** [comment]
Ok this is in, lets see if it does what we need 👍

**Comment by kyleblythe** [comment]
Hi @payten and @steveswinsburg ,

Looks like the secondary ordering by points isn't getting reflected. :-/ It appears to still order primarily by the letter grade, then using the student name as the secondary sort:

![image](https://cloud.githubusercontent.com/assets/11447474/15215788/41316cc2-1822-11e6-88bb-249b9afaa224.png)

**Comment by kyleblythe** [comment]
It is, however, now allowing you to switch from course grade column sorting to item-based sorting, so we're good there.

**Comment by payten** [comment]
Thanks @kyleblythe.  It looks like I was sorting on the pointsEarned, which doesn't always match up with the calculatedScore (which takes into account weightings and extra credit scores). 

I've changed the sorting algorithm to first sort on the index of the letter grade within the grading scheme and then by the calculated score.   PR pending.

**Comment by kyleblythe** [comment]
Confirmed! Working great!

![image](https://cloud.githubusercontent.com/assets/11447474/15372968/179a593e-1d11-11e6-9c0f-70a89c21e587.png)

**Comment by kyleblythe** [comment]
Will create a separate issue for sorting within the "Students" column.
