### ISSUE TITLE
"Percentage" Grade Entry Type

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1363]
_From @kyleblythe on July 14, 2015 20:55_

Provide the ability to enter grades as percentages into the spreadsheet interface, if the "Percentage" grade entry type is selected in the GB settings.

If the "Percentage" grade entry type is selected:

* Remove the " / [total points]" element that appears within the cell when editing it.
* Add a " % " into the cell when it is being edited.
* If the cell value is empty/null, keep the cell empty. However, once a value has been entered, provide a " % " after the value in the cell (e.g., 90% instead of 90).

_Copied from original issue: steveswinsburg/gradebookNG#146_

**Comment by steveswinsburg** [comment]
For reference, Gradebook _classique_ has percentage grade precision to 2 decimal places (12.34%) and points grade precision of 1 decimal place (eg 12.3).

**Comment by steveswinsburg** [comment]
The setting works, need to follow through the logic flow as it returns the concurrent error, presumably it’s using the point grade underneath, so that needs to be made aware. Also need some UI work to make it show percentage in the cell. Cells probably also need to be aware of the setting.

**Comment by steveswinsburg** [comment]
For now, this setting will be disabled.

**Comment by steveswinsburg** [comment]
Underway!

**Comment by steveswinsburg** [comment]
From my analysis in GB1, if the Gradebook is setup to enter grades as percentages, then when entering the percentage grade, it is actually stored as the corresponding point value.
Also, the add/edit grade item panel has a label change from 'Gradebook Item Point Value' to 'Gradebook Item Relative Weight'. But under the hood these are identical, ie the total points for that item.

Example 1, a gradebook item has a 'Gradebook Item Relative Weight' = 10.
If you enter 100% for the score, the data is stored as 10.

Example 2, a gradebook item has a 'Gradebook Item Relative Weight' = 40.
If you enter 50% for the score, the data is stored as 20.
If you enter 31% for the score, the data is stored as 12.4

In addition, if you change the 'Gradebook Item Relative Weight' value, say from 40 to 30, then, since all percentages would be out of sync, they are all recalculated based on the new total.

Example 3, a gradebook item has a 'Gradebook Item Relative Weight' = 40.
A percentange of 31% is enter for the score, the data is stored as 12.4.
The gradebook item is edited and the 40 is changed to 30.
The  data is now stored as 9.3.

**Comment by steveswinsburg** [comment]
- [ ] Re-enable setting
- [ ] If setting is toggled, need to recalculate the grades
- [ ] Backend cals need to work with a passed in grade being a percentage rather than raw number, ie calculate the raw grade from percentage

**Comment by payten** [comment]
Ah, that's interesting!  I was just thinking there'll probably be some front-end changes too.  For example, we'll need to update the "out of" label on the editable cell to be `/ 100%` and perhaps even the points label in the assignment header cell? Also, would the student grade summary need to be changed to display the percentage value rather than the point value?

**Comment by steveswinsburg** [comment]
PR sent. Things left to to:

- [ ] Edit gradebook item may need a label change w.r.t. total points
- [ ] 'Show Points' doesn't seem relevant in the course grade. Disable for both settings and the little drop down?
- [ ] Instructor summary and student summary have not yet been updated. I was going to make sure the change in the grade item cell is ok before making the same change there.
- [ ] Gradebook stores the percentage value internally as a calculated decimal. So if you change the total point value of an assignment from say 50 to 100, all records for that assignment need to be updated to reflect the new percentage as a decimal.  This is underway
- [ ] If you toggle from points to percentage it has to calculate new grades for the entire grade book. This could take a while especially if there are many gradebook items. May need to make asynchronous in a new thread, however this would also need to block grade updates while it is processing and present a note on the screen to tell people why. Need to profile this.

**Comment by steveswinsburg** [comment]
I have not updated the instructor grade summary or the student summary as it already shows the value as a percentage out of relative weight (ie 20/50). However this could be changed if desired, ie to 20%. Have a look and see.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

This is looking great. I am ambivalent re: the percentage displayed in the grade summary/student review mode/student view. I think you're right that it already shows this, and I don't know if it's necessary to hide the relative weight to show a straight percentage.

I do have a question though...with exception to the change form "Total" to "Relative weight" in the column header, the interface itself looks identical when in "Points" v. "Percentage" mode. I know that the "%" shows up in-cell when editing a cell, but I'm wondering if we'd also want the percentage to remain persistent in each cell, to better denote that the values displayed are, in fact, percentages. Let's chat about it today!

**Comment by kyleblythe** [comment]
As per our call yesterday, let's show the "%" symbol in all cells that contain a score.

**Comment by payten** [comment]
Latest version has been merged and is ready for testing.  This includes the patch to show the '%' symbol for non-null values.

**Comment by kyleblythe** [comment]
Looking great! And category subtotal percentages appear to be working as expected, so I'm assuming that #2781 is resolved as well? Nice!
