### ISSUE TITLE
AjaxEditableLabel under iOS/touch screen doesn't focus input

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1364]
_From @payten on July 21, 2015 3:22_

In investigating better mobile compatibility I've come across an issue with the AjaxEditableLabel on touch devices.  To replicate:

1. open the gradebook in an iOS simulator or iPad
2. tap once on a score cell to focus
3. tap again to invoke the AjaxEditableLabel
4. the input will display however will not be focused
5. tap to focus inside the input
6. the input reverts to the label before the keyboard is displayed

I thought this might be due to the context within the grid and the custom javascript, however the behaviour was replicated with a simple test harness with a single AjaxEditableLabel (outside of the grid, form context and untouched by the custom Javascript).

I believe the issue stems from the iOS "feature" which will not focus an input programatically under normal circumstances and only allow focus to be set if within of a "click" or "touchend" event thread.  As the AjaxEditableLabel input is loaded via ajax, the Wicket focus (`Wicket.Focus.setFocusOnId('editor2130c');}`) is suppressed by iOS and does not apply.  I've tried to force this focus via the custom Javascript but iOS is making it tricksy.

I'm scratching my head trying to work around this one.

_Copied from original issue: steveswinsburg/gradebookNG#151_

**Comment by steveswinsburg** [comment]
_From @payten on July 21, 2015 4:54_

Just had a play with replacing AjaxEditableLabel with a TextField and OnChangeAjaxBehaviour - I wonder if something like this (https://github.com/payten/gradebookNG/commit/bbce353aed36d609756102bc7432e8c11a10c3b8) could be an option?  It would mean the input field is always in the DOM and only POSTs to submit the value, the iOS touch event would focus input and we wouldn't have that lag as the label becomes an input. I imagine the cell would still be replaced as new notifications/flags are added via the AjaxRequestTarget as required.

**Comment by steveswinsburg** [comment]
_From @payten on July 23, 2015 23:4_

Perhaps worth mentioning here too:  Kyle reported a performance issue whereby entering the edit mode felt sluggish.  This could be due to either network latency/the round trip required to load the input field combined with the click-delay required to distinguish between a cell-focus and a click-to-edit.

Note: A distinct click to focus is now required before allowing a click to edit.  This was to better support touch to focus on mobile devices to allow viewing of the popover context messages (as hover to view messages is not an option).  

Possible alternatives: Instead of showing the popover on focus of the cell, offer a button which can be clicked to toggle the popover.  This could be a button on the left of the cell.  I could work on some designs/mockups if we wanted to explore this option. Also the TextField/OnChangeAjaxBehaviour would resolve the current pause as the user waits for the input to load.

**Comment by steveswinsburg** [comment]
Hey @payten, since the editablelabel is now a textfield, is this one sorted?

**Comment by payten** [comment]
Yep, thanks @steveswinsburg.  

@kyleblythe, with the input refactor changes, touch screen editing should now be supported. Huzzah!

**Comment by kyleblythe** [comment]
Confirmed! Beautiful.
