### ISSUE TITLE
Add support for gradebook.coursepoints.displayed for student view

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1367]
_From @steveswinsburg on July 30, 2015 21:29_

If `gradebook.coursepoints.displayed = true`, have an option in the settings page that allows the instructor to toggle on/off the course grade as points.

Likewise, add a setting for the percentage grade display.

The backend will need to check this setting and get the appropriate course grade. The front end will then need to render the appropriate columns.

_Copied from original issue: steveswinsburg/gradebookNG#167_

**Comment by steveswinsburg** [comment]
_From @kyleblythe on July 31, 2015 17:52_

In Settings, beneath the option to "Display Course Grade to Students Now," provide a series of checkboxes for instructors to select which course grade options will display to students. 

By default, "Letter" and "Percentage" will be selected, though the instructor can modify this. Additionally, the "Points" option will be available, if categories and weighting have not been enabled within the GB.

**Comment by steveswinsburg** [comment]
_From @kyleblythe on October 15, 2015 17:4_

Below the "Display Course Grade to Students Now" option, provide text stating "Display Grade As:" followed by:

* Letter Grade
* Percentage
* Points

Points will only be available to select if Categories/Categories & Weighting is NOT enabled within the Gradebook.

Letter Grade and Percentage will both by default be selected. Instructor can modify this by deselecting checkboxes, or enabling others. Any combination of the 2/3 (depending on setup) will be allowed.

If the instructor deselects ALL checkboxes, a red warning should appear notifying them that at least one display option must be selected.

Additionally, to the right of "Display Course Grade to Students Now," provide a preview pane showing how the selected options will appear to students.

Mockup:

![course grade display settings](https://cloud.githubusercontent.com/assets/11447474/10521326/4265386a-733d-11e5-9ec8-29cbcbb14be1.png)

**Comment by steveswinsburg** [comment]
Hey @kyleblythe, 

The gradebook record in the database contains columns for `course_grade_displayed`, `course_points_displayed` and `course_average_displayed`. Interestingly, `course_average_displayed` is completely unused at present, it is never set or retrieved anywhere, as far as I can see.

The mappings I see for this are:
1. 'Display course grade to students now' = `course_grade_displayed`. This is already wired up and cannot be changed.
2. 'Letter Grade' = There is no field to store this.
3. 'Percentage' = we could use the `course_average_displayed` - see below.
4. 'Points' = `course_points_displayed`. Maps fine, no further discussion required.

__Problems__
For Letter Grade, there is no field to store this. We will need to add it, which means a db conversion. Until now we have been able to avoid this...

For Percentage, we could use the course_average_displayed as it is currently unused, however I am unsure of the original intent of this field and whether it is meant to be student specific or entire site specific. In any case it is unimplemented so maybe we can just use it. It kind of fits since it is the same naming as the course_points_displayed field.

Thoughts?

**Comment by steveswinsburg** [comment]
_From @kyleblythe on October 22, 2015 13:50_

Hey @steveswinsburg ,

Sorry for the delay in responding. Hmm, yeah. Do you see any way around having to add a new field to the db? In the past, when the grade released to students was both the letter grade & percentage, what field was storing those entries? Was that just part of the course_grade_displayed (sorry my understanding's so basic)?

That's interesting that the course_average_displayed is currently unused. I wonder what it was meant for in GB1? Students cannot see the class average for any items in the GB, only their individual subtotal averages across categories, so unless that's tied to category subtotal scores I'm not sure what this could have meant in relation to them. Mapping "Percentage" to this db field wouldn't interfere with any of the class-wide averages we're planning to include in the instructor's "View Grade Statistics" lightbox, would it?

**Comment by steveswinsburg** [comment]
In GB1, toggling 'display course grade to students now' adjusted `course_grade_displayed` and controlled the letter grade/pass not pass etc.

So the one setting controlled both the actual display of the course grade AND the letter/pass grade.

In addition, if the sakai.property `gradebook.coursepoints.displayed = true` was set, then there is an additional column in the course grade page for points. This is a server wide setting.

Discussed on the call today, not a big deal to add a new column for controlling letter grade, then we can have this flexible. So the `course_grade_displayed` will only control if the course grade is displayed, not what is displayed. 

In terms of backwards compatibility, GB1 will ignore this and continue to show the letter grade or not depending on the setting.

**Comment by steveswinsburg** [comment]
Closing this one as it is done in other tickets (see above).

**Comment by kyleblythe** [comment]
Re-opening this one, as the requirement for linking up what displays in the student's grade view with the options selected in Settings is still in progress.

Closed issues #1454 (the display of the course grade preview in Settings) and #1419 (the course grade display in student's view).

**Comment by kyleblythe** [comment]
Additional details re: this requirement:

If the instructor deselects all 3 checkboxes (letter, percentage, and points), a red warning should appear notifying them that at least one display option must be selected.

If the instructor tries to save their Settings despite not having at least one of the checkboxes selected, an error message should appear. Ideally, the window would automatically scroll up to the error message, and would re-open the accordion menu for "Grade Release Rules."

**Comment by steveswinsburg** [comment]
Validation is added as part of #1734.
Still to do is the course grade points being set into the object so we can use it.

**Comment by steveswinsburg** [comment]
@kyleblythe In implementing this I noticed that there is a method in the gradebook service to get the total points possible for a student in the course, however it is impacted by weighting. For example, without weighting it's just a sum of the assignment totals (excluding extra credit and those excluded from course grade), eg:

Points earned = 330.0
Points possible = 350.0

With weighting, the total points earned is pretty odd:

Points earned = 330.0
Points possible = **0.9975**

Should the points possible calculation be impacted by weighting? Just wanted to check before I go ahead and fix this to give the correct number for points possible.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

That sounds about right, that the points earned/possible would end up being pretty meaningless in the context of categories & weighting.

For that reason, what I think we were envisioning is preventing the "Points" option from being available when the GB is set up with "Categories" or "Categories & Weighting" (i.e., that it would only be available when it's set to "No Categories"). That way, we would prevent points from being surfaced when it wouldn't be meaningful to display them.

Question: what should we do if, in either the instructor view or this student view, the following occurs:
* the instructor sets "Points" to be visible, as the GB is not set up with "Categories" or "Categories & Weighting"
* the instructor then changes the settings to enable "Categories" or "Categories & Weighting"

I think that we might want to have the following automatically occur:
* Revert the student course grade view to the default (Letter Grade + Percentage)
* Deselect the checkbox for "Release final course grade to students"
* An info message appears for the instructor at the top of the Settings page letting them know that "Points can not be displayed as a course grade when Categories or Categories & Weighting are enabled. Please select different course grade display options and re-release to students."

**Comment by steveswinsburg** [comment]
The bulk of this is in PR. I have disregarded the gradebook.coursepoints.displayed sakai property, the points option is there in all cases. I think that setting is an unnecessary complication especially as its an all or nothing setting, but if we really want it I can make the change in settings.

Also to note that I haven't yet made the latest change that @kyleblythe posted about having a setting then clearing categories and resetting some options. Maybe we could test this out once merged and see if necessary.

**Comment by kyleblythe** [comment]
beautiful. Confirmed!

**Comment by kyleblythe** [comment]
Wanted to reopen this to mention a quick issue - right now the "Points" option can be selected in "Grade release rules" when categories & weighting are enabled. When cat & weighting is enabled, this checkbox should be greyed out and disabled. 

And, as mentioned above, if points were previously selected and the cat & weighting is enabled, the following should occur:

I think that we might want to have the following automatically occur:

* Revert the student course grade view to the default (Letter Grade + Percentage)
* Deselect the checkbox for "Release final course grade to students"
* An info message appears for the instructor at the top of the Settings page letting them know that "Points can not be displayed as a course grade when Categories or Categories & Weighting are enabled. Please select different course grade display options and re-release to students."

**Comment by steveswinsburg** [comment]
@kyleblythe 

The current behaviour is that you will be prevented from saving if 'course grade points' are enabled and 'categories and weighting' is the category type.

I think if we made the modifications described above it could get confusing. This is because once modified (ie reset the course grade display to letter + percentage and not points), the form would then be in a state where the user could just click save again and the validation would pass. However they may not tick the 'release to students' box and may inadvertently leave the form without the course grade released.

So currently the form is left unmodified and in a non submittable state, with the error message to prompt them to review and resubmit.

Might need to discuss the workflow on the call as there are a few nuances in it I think!

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

That's a really good counter-argument. Yeah, I'm torn about this one. I definitely see your point, and don't want to take any sort of action re: the course grade display that might get overlooked by the instructor. It just also feels a little weird to have the "Points" option remain selectable if it produces an error message. Hmm. We'll talk through it on the call - thanks!

**Comment by steveswinsburg** [comment]
Discussed 18/3/2016:
Make the points and categories & weighting setting mutually exclusive. If one is selected the other is deselected and greyed out and some info text added.

**Comment by kyleblythe** [comment]
Add'l info:

1. When Points is selected, disabled categories & weighting and provide grey text alongside saying “Cannot use categories & weighting and display points as final course grade to students”

2. When cat & weighting is selected, disable points checkbox and provide grey text alongside saying “Cannot use points while Gradebook is set with Categories & Weighting”

**Comment by steveswinsburg** [comment]
I have make the changes w.r.t. disabling each setting and added the instruction text, but added it to the overall instruction for each section. I have not added it as a conditionally appearing item as both of these are in separate panels in the overall page. I already had to expose a few components out to allow them to update each other and set each one disabled, exposing the label out as well seemed a bit messy. I can make this change if we really want it though.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg,

I think I'm okay with the instructional text staying within the info box. However, at the moment, there's no visual styling denoting that the radio buttons are inactive: 

![image](https://cloud.githubusercontent.com/assets/11447474/14366395/9252a4ca-fce0-11e5-817f-8f278dada6af.png)

If we could grey out the radio button/text, and maybe provide a hover tooltip, I think that would be great.

**Comment by kyleblythe** [comment]
Confirmed!
