### ISSUE TITLE
Course Grade Display Type - Instructors and TAs

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1368]
_From @kyleblythe on July 31, 2015 17:58_

Within the "Course Grades" column header in the spreadsheet view, provide an option for "Course Grade Display Type."

This should open a lightbox window that will allow for instructors and TA's (if given the ability to see course grades) to be able to determine what displays within the course grades column.

By default, "Letter" and "Percentage" should be selected, though the user can modify this. A third option, "Points" should be available for selection only if categories and weighting have not been enabled within the GB. Explanatory text should also be provided, notifying the user that this display type is only for them, and that the student course grade display type is available, along with the course grade release option, in Settings.

Ideally, this display type will be set on a user-by-user basis.

_Copied from original issue: steveswinsburg/gradebookNG#168_

**Comment by steveswinsburg** [comment]
_From @kyleblythe on July 31, 2015 17:58_

![2015-07-31_13-58-14](https://cloud.githubusercontent.com/assets/11447474/9013805/387a36bc-378c-11e5-9642-415994f511fb.jpg)

**Comment by steveswinsburg** [comment]
_From @kyleblythe on October 22, 2015 15:3_

Follow-up re: formatting and alignment of these grade values when displayed for the instructor/TA in the spreadsheet view:

Ordering of displayed grades should be as follows:

1. Letter Grade
2. Percentage
3. Points

Formatting of the displayed grades should be as follows:

A-   92%  276/300

Additionally, there should be consistent alignment following the letter grade to aid with visual clarity, since some letter grades will have a +/- afterwards, while others will not.

Example:

A___95%
A-__ 92%
B+__91%

**Comment by steveswinsburg** [comment]
*Implementation notes*
Call getGradebookSettings() and there are three options in there for each checkbox. Also see the settings panel where this is set. Could chuck the preview in there also maybe.

**Comment by kyleblythe** [comment]
Hey @steveswinsburg ,

This option (the "Update Course Grade Display" dropdown option in the Course Grade column header) appears to be taking the same action as the student grade display option in Settings (captured in #1367 ).

Apologies for the confusion - these should function independently of one another. This issue relates to how instructors & TA's in the site see the course grade as it displays in the Course Grade column, and has no impact on what the student view displays.

The setting in #1367 provides the course grade that gets actually released to the student. This way, the instructor can see more/less info than what they decide to release to the student.

**Comment by steveswinsburg** [comment]
Discussed 19/2/2016:

Instead of lightbox, provide a single toggle to Show/Hide Points in course grade dropdown. Option will just not appear if you’re using Cat & Weighting.

Letter grade + percentage will always appear in instructor view.

Add note to setting page saying that this format is just for the student view.

Instructor summary view would use whatever is set for the instructor view.
Student grade summary would use what is in the settings.

**Comment by kyleblythe** [comment]
This is looking great. Quick note:

The "show/hide points" option appears in the course grade column header dropdown even when the Gradebook is setup with categories & weighting. So while points will not display, you are able to select the option to show/hide points. This dropdown option should be hidden when categories & weighting are enabled.

**Comment by kyleblythe** [comment]
Confirmed! Beautiful.
