### ISSUE TITLE
Course Grade Override & Log

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1369]
_From @kyleblythe on July 31, 2015 18:4_

Within individual students' Course Grade cells, provide a drop-down menu containing options for a) Grade Override, and b) Override Log.

**Dropdown being added in #1639 - this must be done first**

For Grade Override:

Provide a lightbox window, wherein the instructor may see the course grade info for the selected student (same as the current "Course Grades" screen in GB1), as well as provide a course grade override. Additionally, provide the ability to navigate to the previous/next student.

![2015-07-31_14-03-50](https://cloud.githubusercontent.com/assets/11447474/9013918/fdc79748-378c-11e5-92d2-39b4537bbb92.jpg)

For Override log:

Provide an override grade log lightbox window, similar to the grade logs for individual item cells.

_Copied from original issue: steveswinsburg/gradebookNG#169_

**Comment by steveswinsburg** [comment]
_From @kyleblythe on August 28, 2015 18:3_

Additional details re: Grade Override:

To allow flexibility / precision for override grade entry, ideally we could provide multiple entry fields within the "Grade Override" column - one for letter grade entry (with + / - capability), one for percentage grade entry, and one for points (if using the standard GB setup or unweighted categories. This should be unavailable / hidden if using Categories & Weighting).

When a grade is entered into one of these fields, automatically provide a corresponding entry into the additional fields. Examples:

* If entering an "A" into the letter grade field, the percentage field would automatically populate with the corresponding default percentage for "A" as calculated in the GB, i.e., 95%.
* The percentage could then be tweaked to provide an exact grade. If the grade is changed to a score outside of the letter grade's range, provide an updated letter grade. Changing the grade to 97%, for example, would cause the letter grade to remain an "A", while changing the percentage grade to 91% would change the letter grade to "A-."

This relationship could be represented graphically by a link icon / lock icon, as seen when modifying the size of images in applications like photoshop:

http://www.screencast.com/t/wGwOPNzDs9jo

**Comment by kyleblythe** [comment]
This looks great! Grade override and override log are working beautifully. Looks like you can also delete an override entry to clear out the override and return to the calculated course grade - nice!

One more request for this, though - would it be possible, when a grade override has been entered and saved, for the Grade Override window to display a "Remove grade override" option, which would accomplish the same thing as clearing out the override entry and saving?

My concern is that people may not realize that they have to delete the current override entry to return to the calculated course grade.

**Comment by steveswinsburg** [comment]
I think this one is ready to test :)

**Comment by steveswinsburg** [comment]
And merged. Cheers

**Comment by kyleblythe** [comment]
Confirmed!

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

Sorry, one last enhancement for this. Currently, the "revert" button appears even when there isn't currently a course grade override in place:

![image](https://cloud.githubusercontent.com/assets/11447474/13999102/0f20e1fa-f111-11e5-83e0-8bfd3f297928.png)

Question - is it possible to disable/hide the "revert" button when there isn't currently a grade override in place?

**Comment by kyleblythe** [comment]
Confirmed!
