### ISSUE TITLE
Reorder Capability for Student Info Columns

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1374]
_From @kyleblythe on August 6, 2015 14:51_

Provide ability to change the ordering of the two student info columns ("Students" and "Course Grade"), so that the user may determine whether the students' names or their course grades should appear next to the grade item columns.

These columns should be draggable within the context of the static student info area, and should also have "Move Left" or "Move Right" options within the header drop-downs, depending on which position they currently occupy.

_Copied from original issue: steveswinsburg/gradebookNG#174_

**Comment by kyleblythe** [comment]
Closing this issue out - will revisit in the future if needed.
