### ISSUE TITLE
New Icons for TA view

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1377]
_From @kyleblythe on September 11, 2015 14:2_

Provide 3 new in-cell icons/popover messages for TA view.

'You do not have the ability to view scores for this section/group.' - appears when TA is able to see a given item column (because they have view/grade access for a given section/group), but does not have view/grade access for another section.

'You have view-only access for this item.' - appears when TA is able to "View" a given item column.

'You do not have view access for final course grades.' - appears when TA does not have the permission for 'Allow grader to see course grade for selected section(s) below' selected.

_Copied from original issue: steveswinsburg/gradebookNG#227_

**Comment by kyleblythe** [comment]
This has been addressed already - we are using the lock icons throughout TA view to denote that content is not editable. Cells without view access simply don't display scores.
