### ISSUE TITLE
"-" as Course Grade when no scores are present for student

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1378]
_From @kyleblythe on September 23, 2015 20:4_

When no scores have been provided for a student (and their course grade therefore is a null value), provide a dash (i.e., - ) as the displayed value in that student's "Course Grade" column, replacing the current "F."

_Copied from original issue: steveswinsburg/gradebookNG#237_

**Comment by steveswinsburg** [comment]
I think this needs to go into the gradebook service as it is there where the course grade is calculated.

**Comment by steveswinsburg** [comment]
The ‘F’ comes from the gradebook service and any change to this would be a modification to the gradebook service which may affect other tools. We should just handle this in our business service and override the course grade if there are no grades for the student.

**Comment by steveswinsburg** [comment]
Pushed a fix for this. If the student has no grades entered the course grade is overriden to a -

**Comment by steveswinsburg** [comment]
_From @kyleblythe on October 14, 2015 1:23_

Hi @steveswinsburg ,

In a fresh course site w/ gradebook items and no scores, the dashes are showing up. However, in an existing site, students that at one point had scores that have since been deleted are still showing a course grade of "F":

![2015-10-13_21-20-14](https://cloud.githubusercontent.com/assets/11447474/10472613/47d6ff8e-71f0-11e5-9fb0-da0ba4fd15b6.png)

Fresh site URL: https://sandboxclasses1.home.nyu.edu/portal/site/90345863-6b59-4598-83f9-0263595e8ee3
Existing site URL: https://sandboxclasses1.home.nyu.edu/portal/site/6d46de05-0ce1-4839-acad-16f0741ca87c

**Comment by steveswinsburg** [comment]
Ok this is because they still actually have grades, but it's blank - might be a comment there too.
The current fix checks if they have any grade records and under this particular condition, it will say they do. So rather than just checking if they have grades, we would need to inspect the contents of every grade they have to see if its blank, which is a further iteration - alternatively add a flag onto the wrapper for each of the students (GbStudentGradeInfo) which is updated when setting the grades - but that will need to be kept in sync when grades are later added - could get tricky.

We might be able to consolidate some of these iterations soon but I'm not going to fix this just yet, though the above is the likely solution.

**Comment by steveswinsburg** [comment]
On further thought, because the F comes from the grade mapping, this could be enhanced to only count those that actually had grades with values.

**Comment by steveswinsburg** [comment]
Discussed 29/1/2016
If there are grades but they are empty these will be be treated as if there was no grade at all.
So even if all grades were entered but removed, course grade will be -. If there is one grade, then it will be mapped appropriated to an F.

**Comment by steveswinsburg** [comment]
This now conflicts with the course grade override feature. An instructor can specify a course grade override, but if the student has no grades for any assignments, it will remain as a -. I think that in the cases where there is an override present, that will take precedence.

**Comment by kyleblythe** [comment]
Working correctly! Thanks, @steveswinsburg . Confirmed.
