### ISSUE TITLE
Dynamic Updating of the Course Grade / Cat Subtotal Column Values

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1379]
_From @kyleblythe on September 23, 2015 20:9_

As scores are entered into the GB, live-update the values for category subtotal percentages and the Course Grade column.

_Copied from original issue: steveswinsburg/gradebookNG#239_

**Comment by steveswinsburg** [comment]
_From @payten on September 24, 2015 5:49_

Hi @steveswinsburg, I've had a quick go at this, but a little unsure of the best-practice Wicket way of doing things:

https://github.com/steveswinsburg/gradebookNG/compare/master...payten:magic-course-grades

Works a treat!  But storing the labels on the GradebookPage context feels a little strange...Let me know if I'm on the right track and I'll prepare a PR.

**Comment by steveswinsburg** [comment]
_From @payten on September 25, 2015 7:17_

After doing some reading, we could be able to do this using the Wicket event bus and broadcasting a custom event when a score is updated.  The course grade and category average cells can override onEvent and check for the custom event and if the studentuuids match, then update themselves.  I'll look into this next week.

**Comment by payten** [comment]
@steveswinsburg, @kyleblythe, I think this one is done?

**Comment by steveswinsburg** [comment]
Yup.
