### ISSUE TITLE
When invalid score is entered, keep score in field and direct users to refresh page to see last saved

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1380]
_From @kyleblythe on October 1, 2015 16:0_

When an invalid score is saved (resulting in the triangle "warning" message), retain the invalid score in the field along with the warning message. This allows the user to see what score is causing the error message. Within the possible warning messages, provide additional text notifying the user to refresh the tool in order to see the last saved score.

_Copied from original issue: steveswinsburg/gradebookNG#252_

**Comment by steveswinsburg** [comment]
Confirmed this is still a problem.

**Comment by kyleblythe** [comment]
Add'l requirements for this:

* Change this from a yellow "warning" to a red "error."
* Retain invalid score in cell.
* Rework wording of error. Also create an option to “revert to last saved value”

**Comment by steveswinsburg** [comment]
Discussed 18/3/2016:

May need to add more exceptions to the gradebook service to split up any errors that occur in the backend so they can be handled individually.

**Comment by payten** [comment]
I've just implemented revert-score in #2110. This PR doesn't touch the service errors and is purely on the GradebookNG side. It looks like this:

<img width="532" alt="screen shot 2016-04-04 at 1 49 43 pm" src="https://cloud.githubusercontent.com/assets/608337/14237872/215c48f4-fa6d-11e5-8576-2d758b374024.png">

@steveswinsburg, regarding the more granular validation errors, as I see it there's no quick way to split up the errors in the current service code without refactoring how `isGradeValid` interacts with `identifyStudentsWithInvalidGrades` and `saveGradesAndComments`.  I'm happy to have a go at this, but given dependencies with old Gradebook and other things (imports? Gradebook2? etc) I'm a little hesitant to jump in.  Any tips?

**Comment by steveswinsburg** [comment]
Yeah this probably requires careful thought, a bunch of other places may need to be updated to handle these new exceptions. Maybe we should raise a separate issue to track this particular change.

**Comment by steveswinsburg** [comment]
Raised #2119 for the exceptions. Lets test this one as is.

**Comment by kyleblythe** [comment]
Looks gorgeous. Confirmed.

**Comment by kyleblythe** [comment]
Re-opening this issue, as we want to consolidate the yellow "warning" and red "error" in-cell notification types (see comment from 2/18). That way, yellow is reserved exclusively for EC.
