### ISSUE TITLE
Remove "N/A*" from Student Review Mode Cat Subtotal and Show Subtotals in Student View

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1381]
_From @kyleblythe on October 8, 2015 14:32_

Currently, we have an "N/A*" appearing as the category subtotal score in the "Student Review Mode" when the category contains an item that has not been released to students. The student view does not show the subtotal score at all when this is the case.

Since items that are not released to students are ALSO not included in course grade calculations, there is no need to hide the subtotal score. As with the Instructor "Grade Summary" screen, show all subtotal scores, even if there are items within a category that have not been released to students.

_Copied from original issue: steveswinsburg/gradebookNG#256_

**Comment by steveswinsburg** [comment]
_From @payten on October 11, 2015 9:17_

Hi @kyleblythe.  Just had a look at this one.  Currently the service doesn't distinguish between released and not released items when calculating the category average.  @steveswinsburg, I have a feeling this might require a change to the Gradebook service?

**Comment by steveswinsburg** [comment]
Yep that's correct. Currently the category score calculation logic has these three conditions:

1. Assignment actually has points
2. It's not extra credit
3. There is a grade for the student

Shall I add:
4. the assignment is released?

**Comment by steveswinsburg** [comment]
_From @kyleblythe on October 12, 2015 13:52_

Hi @steveswinsburg ,

1. Re: "released" assignments, are we referring to the item being released/not released to students, or it being included/not included in course grade calculations? Because I don't really think that the item being released to students matters, since there's the dependency between that and the calculation status. If an item is not released to students, it's also not included in course grade calculations. With that in mind, though, if an item IS included in course grade calculations, I definitely think it should be a part of the category subtotal calculations. If not, it should be excluded.

2. Re: extra credit items - if an item is marked as extra credit, I think that it probably should be included in category score calculations as well. I know extra credit's calculated differently (with the total points possible not included, but with any scores provided applied to the existing subtotal), but the fact that it's possible to add extra credit items to a traditional category means that this probably should get reflected in that category's subtotal. 

E.g., if there are two items, each worth 100 pts, and an extra credit item worth 10 pts, the subtotal would calculate out of 200 pts. If a student gets maximum points on all 3, they would get a subtotal score of 210/200, or 105%.

**Comment by steveswinsburg** [comment]
Hi @kyleblythe,

Yes, by 'released' I mean the setting "Release item to students?" that can be applied on the assignment. Currently it ignores the setting and always includes it. So if the assignment is included in the course grade then it's all good (as by default it is also released), but if it's not part of the course grade, then it may or may not be released, but will still be included regardless.

Sooo, we can include either condition in the check, let me know.

Re extra credit, I will remove that condition from the check. Let me know on the first one and I'll do them both together.

**Comment by steveswinsburg** [comment]
_From @kyleblythe on October 14, 2015 1:8_

Hi @steveswinsburg,

I chatted with Jeff about this earlier. I think that the release status of an item doesn't matter as much as the course grade calc inclusion when it comes to subtotal scores. When an item is released to students and included in course grade calculations, it makes sense for it to be included in subtotal calculations. When the item is released to students but not included in course grade calculations, it doesn't make as much sense, as the item is not counting toward the course grade and the category subtotal score represents a certain percentage of the final course grade. And if the item is not released to students, thanks to the dependency, it's also not included in grade calculations.

I think that this is how category subtotals are calculated in GB1. Is there a way to double-check this?

If that's indeed the case, I think the three conditions should be:

1. Assignment actually has points,
2. There is a grade for the student,
3. Assignment is included in course grade calculations

**Comment by steveswinsburg** [comment]
Ok yep I just checked against GB1 and that appears to be the case. I'll make the change.

**Comment by steveswinsburg** [comment]
See https://jira.sakaiproject.org/browse/SAK-29975

I've found that the 'include in course grade calculation' and 'item released to students' dependency is not enforced on the backend, only the frontend. Should we make that change? It could have other effects.

The simplest solution here is to just also include the released to students check as the final check (after the include in course grade calculations) to catch any case where an assignment is included in course grade but not released to students (maybe created through the API). WDYT?

**Comment by steveswinsburg** [comment]
I've merged this so give it a run and let me know if it's what you need @kyleblythe .

**Comment by steveswinsburg** [comment]
Hey @kyleblythe, there's been lots of work on the category and student view lately, is this one still an issue?

**Comment by kyleblythe** [comment]
Looks good! Thanks, Steve. Confirmed.
