### ISSUE TITLE
Ability to get a category average for a single student and single category

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1384]
_From @payten on October 16, 2015 0:41_

Required for https://github.com/steveswinsburg/gradebookNG/pull/247.  

In dynamically updating a student's category average when a score changes, currently simplest way is to hit `buildGradeMatrix`, which may not be the most efficient method.  It'd be great to have the ability to pull back the latest category average for a single student and a provided category ID.

_Copied from original issue: steveswinsburg/gradebookNG#267_

**Comment by steveswinsburg** [comment]
Yeah we can make a new method here that calls:

`gradebookService.calculateCategoryScore(final Long categoryId, final List<Assignment> viewableAssignments, final Map<Long,String> gradeMap);`

We'll need to do a couple of lookups to get the assignment list and grademap but that is probably ok.

**Comment by steveswinsburg** [comment]
Hey @payten, it's been a while since we talked about this one. In GBNG Business Service we have:
{{ public Double getCategoryScoreForStudent(Long categoryId, String studentUuid, Map<Assignment,GbGradeInfo> grades)
}}

so I think this is done?

**Comment by payten** [comment]
Just delivered a PR which updates the dynamic category average code to use this new API.  Thanks!

**Comment by steveswinsburg** [comment]
Ok sweet, I'm going to close this off then :+1:
