### ISSUE TITLE
TA view - some cells not editable with grading permissions in place

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1385]
_From @kyleblythe on October 22, 2015 14:40_

In columns for which TA has grading access, if the cell has no grade associated with it, the TA cannot edit the cell to provide scores. Additionally the cell following one with no grade associated with it also cannot be edited.

![2015-10-22_10-26-27](https://cloud.githubusercontent.com/assets/11447474/10668230/4e67be82-78a9-11e5-9e53-7c1329dcc653.png)

_Copied from original issue: steveswinsburg/gradebookNG#270_

**Comment by kyleblythe** [comment]
Hey @steveswinsburg ,

I'm still seeing this issue. Where there are existing scores (or have been existing scores in the past), the cells are editable. However, if no scores have ever been present, the cell is not editable for the TA.

**Comment by steveswinsburg** [comment]
Ok the problem here is that the permissions are applied to items that have grades, everything else is false as there is no grade record returned so we have no way of setting the permissions onto it. This may need to be updated in the service so that a grade record is returned even when it would be blank.

**Comment by steveswinsburg** [comment]
This is fixed and now in PR.

**Comment by kyleblythe** [comment]
Confirmed!
