### ISSUE TITLE
Category Average different in different views

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1387]
_From @payten on November 13, 2015 3:10_

In Gradebook1, the Assignment category average is 12.5%:

<img width="1006" alt="screen shot 2015-11-13 at 2 07 04 pm" src="https://cloud.githubusercontent.com/assets/608337/11137865/024990d4-8a10-11e5-9dee-cd178bca7920.png">

In GradebookNG, the instructor sees 300%:

<img width="877" alt="screen shot 2015-11-13 at 2 07 15 pm" src="https://cloud.githubusercontent.com/assets/608337/11137884/1c19f990-8a10-11e5-9010-fc855bf96bb8.png">

and the student sees 100%:

![screen shot 2015-11-13 at 2 07 30 pm](https://cloud.githubusercontent.com/assets/608337/11137888/237dd6fc-8a10-11e5-936b-fa37f1248f8a.png)

Strange voodoo going on there... 

_Copied from original issue: steveswinsburg/gradebookNG#279_

**Comment by steveswinsburg** [comment]
This is odd, wondering if you can check if they are all the same call to the backend and what params are being sent?

**Comment by steveswinsburg** [comment]
_From @payten on November 20, 2015 3:37_

For the grade summary popup, I see the service hit here:
```
Double categoryScore = this.gradebookService.calculateCategoryScore(category, gradeMap);
```
With `category` being this:
```
org.sakaiproject.service.gradebook.shared.CategoryDefinition@71999334[
  id=8
  name=Assignments
  weight=0.2
  drop_lowest=0
  dropHighest=0
  keepHighest=0
  extraCredit=false
  assignmentList=[org.sakaiproject.service.gradebook.shared.Assignment@53cb3bcf[
  name=Assignment 1
  id=25
  points=100.0
  dueDate=<null>
  counted=false
  externallyMaintained=false
  externalId=<null>
  externalAppName=<null>
  released=false
  categoryName=Assignments
  weight=0.2
  ungraded=false
  extraCredit=false
  categoryExtraCredit=false
  sortOrder=0
  categoryId=8
], org.sakaiproject.service.gradebook.shared.Assignment@2cb68bdf[
  name=Assignment 2
  id=26
  points=50.0
  dueDate=<null>
  counted=false
  externallyMaintained=false
  externalId=<null>
  externalAppName=<null>
  released=true
  categoryName=Assignments
  weight=0.2
  ungraded=false
  extraCredit=false
  categoryExtraCredit=false
  sortOrder=1
  categoryId=8
], org.sakaiproject.service.gradebook.shared.Assignment@683bd2d0[
  name=Assignment 3
  id=27
  points=40.0
  dueDate=<null>
  counted=true
  externallyMaintained=false
  externalId=<null>
  externalAppName=<null>
  released=true
  categoryName=Assignments
  weight=0.2
  ungraded=false
  extraCredit=false
  categoryExtraCredit=false
  sortOrder=2
  categoryId=8
]]
]
```
And `gradeMap`:
```
{25=80.0, 26=35.0, 27=5.0}
```

Note that the first two assignments have `counted = 'false'`.  Might that be something to do with it?

**Comment by steveswinsburg** [comment]
_From @payten on November 20, 2015 3:42_

The student view hits a different endpoint:
```
public Double getCategoryScoreForStudent(Long categoryId, String studentUuid, Map<Assignment,GbGradeInfo> grades) {
    ...
    Double score = this.gradebookService.calculateCategoryScore(categoryId, assignments, gradeMap);
```
With params:
```
categoryId = 8
```
Hm.. so the number of assignments are different. Only two this time... only those with `released=true`?
```
assignments = [org.sakaiproject.service.gradebook.shared.Assignment@42dba333[
  name=Assignment 2
  id=26
  points=50.0
  dueDate=<null>
  counted=false
  externallyMaintained=false
  externalId=<null>
  externalAppName=<null>
  released=true
  categoryName=Assignments
  weight=0.2
  ungraded=false
  extraCredit=false
  categoryExtraCredit=false
  sortOrder=1
  categoryId=8
], org.sakaiproject.service.gradebook.shared.Assignment@748aabf7[
  name=Assignment 3
  id=27
  points=40.0
  dueDate=<null>
  counted=true
  externallyMaintained=false
  externalId=<null>
  externalAppName=<null>
  released=true
  categoryName=Assignments
  weight=0.2
  ungraded=false
  extraCredit=false
  categoryExtraCredit=false
  sortOrder=2
  categoryId=8
]]
```
Grades match up for those two:
```
gradeMap = {26=35.0, 27=5.0}
```

**Comment by steveswinsburg** [comment]
Hi @payten, flicking this back to you. I've fixed up the category calculations and wondering if you are still having issues with the values being different? Ignore the bug from #1420 where the calculation might be wrong, just wondering if it's inconsistent?

**Comment by payten** [comment]
Looks great!  The category averages match up on GradebookNG's student view and instructor views (in grid and summaries) and also with the old Gradebook values.

The only issue I'm seeing seems to be related to #1590 whereby the GradebookNG instructor view values are out when one of the grade items is not included in the course grade calculation.  

For example:

If item A is 6 out of 10 and isn't included in the course grade calc, and item B is 8 out 10 and is included, I'm seeing a category average of 140% in the NG instructor views; 80% in the NG student view; and 80% in the old gradebook all grades grid.

If you agree, I'll close this one and leave #1590 for the remaining issue.

**Comment by payten** [comment]
Ah yep, they definitely seem to be the same issue!  Closing. Thanks!
