### ISSUE TITLE
Slowness when saving grades & entering grade "edit" mode

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1388]
_From @kyleblythe on November 19, 2015 17:6_

As per our GB call last week, there seems to be some pretty noticeable slowness when both saving grades and entering the edit mode for a cell.

Saving scores for a cell is taking approximately 1.27 seconds to complete when categories & weighting are enabled - this may have to do with the live category subtotal score calculation. Perhaps it's possible to do this subtotal calculation on the side (or after the score is successfully saved), so that there's no delay for the user.

Entering the edit mode for a cell is also experiencing slowness (~600ms in Canberra, ~90ms in NY/Pittsburgh). Example of edit mode slowness taken from Shanghai:
http://screencast.com/t/8DufgNGzs2j

_Copied from original issue: steveswinsburg/gradebookNG#281_

**Comment by steveswinsburg** [comment]
_From @kyleblythe on November 19, 2015 17:7_

Additional notes:

PG: Locally for me it takes ~80ms to load the input and then 640ms to post the change.  Without the triggering the ScoreChangedEvent (to populate the Category Avg, Course Grade) the post takes 120ms.  So, definitely overhead in calculating those values.. add latency and makes for a sad faces.

PG: I investigated an alternative mechanism for the table inputs when looking into touch-screen compatibility: https://github.com/steveswinsburg/gradebookNG/issues/151 - that might come in handy to at least remove the first GET/latency to turn the label into an input field.

**Comment by steveswinsburg** [comment]
Sounds like it's the category/course grade calc on every cell update that is causing the slowdown - this should be made asynchronous, perhaps a callback/behaviour on the appropriate cells (category/course grade) so it can update itself in the background. It would mean that a user could tab to the next cell and continue on, then the other cell would update itself when ready.

**Comment by payten** [comment]
Hi @steveswinsburg, I've had a go at refactoring the `AjaxEditableLabel` and replacing with a `TextField` with an ajax onchange behaviour.  Things seems to nicely resolve the latency issue when loading the input and conveniently it all now works on touch devices.. huzzah!

Would you be able to give this a quick review: https://github.com/sakaiproject/sakai/compare/master...payten:1388-editable-cell-refactor

If you feel warm and fuzzy about it, I'll prepare a PR.  Thanks!

**Comment by payten** [comment]
Hi @kyleblythe.  We've implemented two changes to improve performance and the effects of latency:
1. move the course grade and category average calculations off the critical path of posting the score 
2. change the grid to use a text input up front so there's no latency when a user goes to edit a score (previously the score would AJAX the input field before the user was able to change the value).

**Comment by kyleblythe** [comment]
Confirmed!
