### ISSUE TITLE
Refactor categorized sort order code

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1389]
_From @payten on November 30, 2015 3:59_

To improve the robustness and reduce complexity of the categorized sort order mechanism, we should look to refactor the existing code to use Wicket events.  The problem is, we need to keep the sort order XML in sync with the state of the gradebook.  This includes when grade items are added, removed or moved to a new category; or when categories are enabled, disabled, added or removed.  Wicket events seem like a good fit to broadcast when these changes happen and callbacks can ensure the XML is in sync.

Relates to #282.

_Copied from original issue: steveswinsburg/gradebookNG#285_

**Comment by payten** [comment]
@steveswinsburg  Is there a chance we can move the categorized sort order onto the `gb_gradable_object_t` table?  I'm seeing some weird behaviour and I wonder if it's due to the caching of the XML stored as a site property?

**Comment by payten** [comment]
Was thinking more about this one @steveswinsburg.  Ideally it'd be great to solidify the categorised sort order by adding a `categorized_sort_order` column to the `gb_gradable_object_t` table.  We could then optimise SQL for updating this value for the grade item and others in that grade item's category.

I think this would manifest as a new gradebook service endpoint that allowed this value to updated for a single grade item, which would then modify the sequence for any other grade items in the same category.  It may also be complemented with private methods to assist in handling the following gradebook events:
- Categories disabled: if all categories are removed from the gradebook, then perhaps this new sort order is null'ed.
- Categories enabled: if previous categories are not retained(?), then can assume `sort_order` within an "uncategorised" state.
- Category removed: items would no longer ordered by a category.  Perhaps they can be ordered within an "uncategorised" state?
- Category added: no change required category won't have any items yet
- Grade item added with category: automatically added to the end of the categorised order 
- Grade item updated with new category: move to the end of newly assigned category and resequence the sort orders of grade items in the old category
- Grade item removed: resequence grade items in category
- Grade item drag and drop reordered: resequence the order for grade items within the category. 

One outstanding question, do we allow drag and drop of any grade items that do not have a category (in the uncategorised state)?  I believe this currently results in an exception.  This might be a question for the business folks.. but my feeling is that if it's not categorised, it cannot be reordered.

**Comment by steveswinsburg** [comment]
Agreed, lets move it to the gradeable object table so each items knows its own order within the category it is in.
When moving to a new category, the category sort order should be cleared.
Drag and drop should be handled on the front end to prevent it, if possible, however should also be handled on the backend so it doesn't explode and you can't set a categorised order if no category.

**Comment by steveswinsburg** [comment]
Marking this as a bug as the XML site property stuff is a bit flaky.

**Comment by payten** [comment]
Hi @steveswinsburg. I've had a initial go at this and I have the database interactions working well I think:

https://github.com/sakaiproject/sakai/compare/master...payten:1389-categorized-sort-order-refactor

I've backed out the XML property code and now rely on the new database value.  I update this sort_order whenever I add or edit an assignment.  If the assignment changes category, then I put it at the end of the category sort order.  Seem ok!

I'm a little unsure about DB migrations etc or handling null categorizedSortOrder values.. I have a TODO in there for further thought. 

One thing I noticed, was that the old categorizedSortOrder is retained on page refreshes requiring a page reset to pull back the new value.  So we might need to do some Wicket poking to ensure the state is updated accordingly.

Would be great to get your thoughts on the changes and if you feel good about them, I'll clean them up and continue to think about the edge cases!

**Comment by payten** [comment]
Hi @steveswinsburg. I've continued to work through and clean up this WIP.. plus test against the scenarios above. It behaved well! https://github.com/sakaiproject/sakai/compare/master...payten:1389-categorized-sort-order-refactor

On the call, including the category average column in the drag and drop ordering was mentioned.  That won't work with this solution :disappointed:  Perhaps if the category average column had a placeholder entry in the gradable_object table (like the course grade column) it could play nice though?

**Comment by steveswinsburg** [comment]
@payten sorry for the delay, going to look at this shortly. We should perhaps discuss with @kyleblythe all of the requirements around the category ordering (incl #1424) to figure out the best approach for all of it.

**Comment by payten** [comment]
Hm.. there's a `category_order` column available in the `gb_category_t` table.  Would be able to use that? Once exposed by the service, the Wicket templates and custom Javascript can be easily modified to use this value to sort the categories.

**Comment by steveswinsburg** [comment]
Yup that field looks to be for this purpose. We may need some service methods to handle this on the backend like with the ordering of the items.

**Comment by payten** [comment]
Latest WIP version contains code to introduce sorting of categories via the Settings interface and match that up in GradebookNG.  As discussed, it seems we can make use of the `gb_category_t` table `category_order` column.

Code is here: https://github.com/sakaiproject/sakai/compare/master...payten:1389-categorized-sort-order

There's a few more things to do before I'll have a PR ready:
- add a DB migration for the new `gb_gradable_object_t` column
- investigate why modifying the model doesn't refresh underlying panels in the Settings page (when the category_order changes, hit save, the order doesn't reflect the new order)
- review any new TODOs
- move new Settings page category drag handles from the Javascript to the Wicket template

Hopefully next week sometime.

**Comment by payten** [comment]
Thanks @steveswinsburg.  The refactor has been merged so we no longer rely on XML stored in site properties..
