### ISSUE TITLE
[GradebookNG] Course grade does not refresh upon score update when not released

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1396]
When setting a score and triggering a course grade refresh, I noticed that the course grade was returning null if isCourseGradeDisplayed == false. Perhaps we need another endpoint or a mechanism to bypass this constraint in the gradebook service - `GradebookServiceHibernateImpl >> getCourseGradeForStudent`:

```
//if not released, don't do any work
if(!gradebook.isCourseGradeDisplayed()){
    return rval;
}
```

**Comment by steveswinsburg** [comment]
This was resolved in another ticket. Course grade now updates correctly.
