### ISSUE TITLE
Hide category settings when not applicable

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1408]
From the 12/3/2015 tech call:

- Javascript to hide cat & weighting table when not set up as such
- Javascript to hide weighting columns when not set up with weighting
- Javascript to hide drop highest/drop lowest/keep highest when checkboxes are not selected
- Since "Drop Highest/Lowest/Keep Highest" only applies when "Categories & Weighting" is chosen, disable and hide the checkboxes for these options when "No Categories" or "Categories" only is chosen.

**Comment by payten** [comment]
Hi @steveswinsburg. I'm having trouble with the wicket callbacks on this one. I've created branch which adds an ajax handler to category radio group.  This then toggles the visibility of the `categoryWrap` container based on the radio selected.  Sounds about right!  The problem I'm seeing is an error when enabling categories it tries to bind to elements within the categoryWrap container that are not in the page; a race condition that I'm unable to get around.

Here's my code: https://github.com/sakaiproject/sakai/compare/master...payten:1408-category-settings

**Comment by payten** [comment]
Figured it out! PR submitted.

**Comment by steveswinsburg** [comment]
Found a bug in this. If there are categories, when the page loads, the radio button for the category setting is not selected correctly. See screenshot.
<img width="494" alt="screen shot 2015-12-15 at 9 03 53 pm" src="https://cloud.githubusercontent.com/assets/129129/11807678/6525cfce-a36f-11e5-85e2-e99149451e85.png">

**Comment by steveswinsburg** [comment]
I'll fix this now.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg , I was able to replicate this bug as well:

![image](https://cloud.githubusercontent.com/assets/11447474/11873751/31eb8310-a4aa-11e5-8598-b28dcdb398d3.png)

I think it is possible that users might set up categories and weighting, then decide to use no categories. Is it possible to continue to hide existing categories upon page load if the tool is set to "No categories"? Then, if the user selects "Categories & Weighting" again, the table could load?

**Comment by kyleblythe** [comment]
Also, @payten , would it be possible to add a few extra javascript hiding options to this:

* Hide the columns for "Percentage," "Extra Credit," and "Drop Highest/Lowest/Keep Highest" from the table when "Categories only" is selected
* Hide the columns for "Drop Highest/Lowest/Keep Highest" by default and show each column only when the associated checkbox is selected with "Categories & Weighting" chosen.

**Comment by payten** [comment]
@steveswinsburg, as expected, toggling these columns in either Wicket or with custom JS/CSS is a bit of a nightmare.  Would it be easier if this settings table was a Wicket `DataTable` where we have control of the columns and their visibility?  I've got a solution for the first dot-point requirement using Wicket and custom CSS, but for the second feature request there's no way to get inside the `ListView` to access the cells within that iterator (https://github.com/sakaiproject/sakai/compare/master...payten:1408-category-table-refinements). Any ideas?

**Comment by steveswinsburg** [comment]
@kyle, that bug with the category table showing should now be fixed.

I was hoping to not have to use a datatable for this but we might have to. Looking into it now.

**Comment by steveswinsburg** [comment]
@payten your new child induced deliriousness is taking hold :sleeping: 

I have added in the javascript callbacks to hide and show the various options depending on what options are selected. Check out this PR: https://github.com/sakaiproject/sakai/pull/1484
Less work than the datatable refactor - I think this one is done?

**Comment by kyleblythe** [comment]
Hi @payten and @steveswinsburg ,

This is looking great. One last bit that we should hide when "Categories Only" is selected - the Percentage total at the bottom of the table:

![image](https://cloud.githubusercontent.com/assets/11447474/12024695/c667a708-ad74-11e5-8c7a-9f12f6982709.png)

**Comment by payten** [comment]
Hi @kyleblythe, I've just merged a PR from Steve that fixes the issue above.

**Comment by kyleblythe** [comment]
Confirmed.
