### ISSUE TITLE
"Course Grade" Field Empty in Student View, Despite GB Settings Options

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1419]
When the "Display final course grade to students" checkbox is selected in Settings and corresponding grade display options are chosen, nothing is displaying in the student's view.

For the short term, the letter grade + points should display in this field when the "display" checkbox is selected.

Longer term, we can get the display options in as they are outlined in issue #1367 (mockup in comment dated October 15).

**Comment by steveswinsburg** [comment]
The problem here is that there is a call to `isCourseGradeVisible` which is not supported for students and will always return false. It makes use of roles and permissions, however we can now flesh this out for students has we have the settings available.

**Comment by kyleblythe** [comment]
Confirmed.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

While the letter grade + percentage is showing up for students now when the "display final course grade to students" checkbox is selected, it still isn't reflecting the options available - it will not, for example, only show percentage or letter grade, and is not reflecting points. We may want to re-open #1367 if we want to hook that last bit up later.
