### ISSUE TITLE
GB-wide "Set Score For Empty Cells" Option

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1422]
Within Settings (in the "Grade Release Rules" section?), include an option for a tool-wide "Set Score For Empty Cells." This provides feature parity with GB1.

Using the model set by the column-by-column "Set Score" option, provide the ability for an instructor to choose a default score that would apply for any empty scores across the entire GB.

**Comment by steveswinsburg** [comment]
Discussed 29/1/2016
'Set Ungraded items To Zero' was in the Course Grade page which GBNG doesn't have. If we add this to Settings we are mixing settings config with a grading action. We discussed moving this into the Course Grade dropdown on the main grading page. The instructor can then also see the consequence of the action, as the cells that are ungraded are visible.

**Comment by steveswinsburg** [comment]
Note, in order to do this we need the Course Grade dropdown to be added. @kyleblythe we might need to prioritise that ticket?

**Comment by steveswinsburg** [comment]
For implementation I was thinking we could have a GBNG business service method that gets all assignments, iterates them and calls the standard GB Service method to do this.

**Comment by kyleblythe** [comment]
Confirmed!
