### ISSUE TITLE
Settings - Hide Table Elements in Categories & Weighting Depending on Radio Button Selection

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1423]
Simplify the display of the "Categories & Weighting" table by hiding various table elements, depending upon the radio button selections made for Cat & Weighting:

* Hide table altogether when "No Categories" is chosen
* Hide "Percentage," "Extra Credit," and "Drop Highest/Lowest/Keep Highest" columns when "Categories only" is selected
* Hide "Drop Highest/Lowest/Keep Highest" by default and show each column only when the associated checkbox is selected with "Categories & Weighting" chosen.

Additionally, since "Drop Highest/Lowest/Keep Highest" only applies when "Categories & Weighting" is chosen, disable and hide the checkboxes for these options when "No Categories" or "Categories" only is chosen.

**Comment by payten** [comment]
Duplicate of #1408 - sorry @kyleblythe, think I double up on this issue.

**Comment by kyleblythe** [comment]
No worries, @Payten! This was my bad. I added this after you! Going ahead and closing this one out.
