### ISSUE TITLE
Provide Order/Reorder Capability for Categories in Cat & Weighting Table

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1424]
In order to modify the order of categories in the GB interface, provide an option for reordering the category rows in the Settings menu's "Categories & Weighting" table.

Either via drag handles or number ordering, provide the option for setting the order of the categories as listed in this table. The descending order of these categories should then determine the left-to-right order of the categories as displayed in the GB interface. By modifying this order in Settings, instructors should be able to determine the order in which the categories display.

**Comment by steveswinsburg** [comment]
Categories already have a sitewide order but this is unused. If we had an entitybroker interface for this we could do a drag and drop and then just set the order, then respect the order on the front end.

**Questions:**

1. Would the order only apply when grouped by category or would the ordering of the assignments on the gradeppk page be influences by what category it is in?
2. Would drag and drop of categories on the gradebook page update this order?

**Comment by steveswinsburg** [comment]
Discussed 29/1/2016. 
* Drag and drop in settings to set the order.
* On the Gradebook page, when grouped by category, render the list of categories in this order.

**Comment by kyleblythe** [comment]
Hey @steveswinsburg & @payten ,

I see that the drag-n-drop category sort ordering is showing up in the cat & weighting table - nice! I know this hasn't been marked as ready for testing yet, but as a heads-up, it appears to be working great.

A few things I've noticed:

* the sort icon is a little wonky in Chrome: http://www.screencast.com/t/lvbVTeBsNTlT
* it's currently possible to drag a category under the Total at the bottom of the table: http://www.screencast.com/t/0QT9w33W551

Otherwise, looks great!

**Comment by steveswinsburg** [comment]
Final fixes have been merged.

**Comment by kyleblythe** [comment]
The category headers are being reflected beautifully when reordering. However, there may be a bug associated with this, as the items themselves are no longer appearing within their respective categories. I detailed these issues in #1856 .

**Comment by kyleblythe** [comment]
Confirmed and closed!
