### ISSUE TITLE
Grade Option in Samigo to send score to GB does NOT exist unless GB tool is active ([GradebookNG] *is* active)

### ISSUE THREAD

**Issue by lgekeler** [sakaiproject/sakai#1428]
Create a course site
Add tools GradebookNG and Tests & Quizzes
Import a QTI 1.2 quiz from another Sakai server, mine was from 10.5
Change settings in Samigo quiz, including sending the grade to the gradebook.... the option does not exist.

Add the Gradebook tool. Return to Tests & Quizzes, NOW the option does exist. "Send assessment score to Gradebook immediately, regardless of options below."

EXPECTED BEHAVIOR: Option is available in Tests & Quizzes regardless of which Gradebook one is using.

<img width="586" alt="screen shot 2015-12-08 at 2 15 36 pm" src="https://cloud.githubusercontent.com/assets/5331541/11687125/c723a0ba-9e52-11e5-99be-6c2150396aec.png">

**Comment by steveswinsburg** [comment]
I'll need to look into how this piece works. I was assuming it would just use the gradebook service - I am hoping it doesn't rely on the tool being present as that may be a difficult fix as it would be bound to the old gradebook tool id. Unless we allowed the lookup for multiple tool ids. But will investigate.

**Comment by steveswinsburg** [comment]
Ok, the bug is in Samigo, specifically:
samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java

As suspected, it checks if a page exists in the site that has the `sakai.gradebook.tool` in it.
I have updated this to also check if the `sakai.gradebookng` tool exists.

**Comment by steveswinsburg** [comment]
https://github.com/sakaiproject/sakai/pull/1439

**Comment by steveswinsburg** [comment]
@lgekeler this fix is in master could you retest on nightly?

**Comment by steveswinsburg** [comment]
Closing. Reopen if still an issue.
