### ISSUE TITLE
When grouped by category, pre-sort assignments in backend

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1445]
From tech call 12/10/2015.

When grouped by cat, if you refresh the tool, the assignments load as ungrouped initially and in the default sort order.  The frontend javascript then reorders the columns(assignments) based on the categorised sort order which can be confusing to the user.

To fix, move the ordering of the assignments to the Wicket code so the JavaScript doesn't need to reorder columns once the page loads.

**Comment by steveswinsburg** [comment]
FYI I have some work on a new sort param going into the matrixbuilder so if you are doing something here, let me know and I'll get mine in. It's just being tested at the moment.

**Comment by payten** [comment]
Ah cool, I've had a go at doing the pre-sort in conjunction with the refactor from XML storage to the database #1389.  There's a WIP branch there in the comments that would be great to get some feedback on.  It's still incomplete, and could use some tips to introduce the new database column/migrations etc.  I think the row-sorting shouldn't get in the way of any of that stuff.

**Comment by kyleblythe** [comment]
Nice! Confirmed. The assignments are now displaying in their "group by category" ordering upon page-load, so when the category row pops in, the ordering doesn't change.
