### ISSUE TITLE
Additional Popup X's

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1469]
Put an “X” in the upper right of the popups that display in the item header / notification when an item is coming from another tool / final course grade not released icon.

**Comment by kyleblythe** [comment]
Hi @payten,

This looks great. Can we get one more "X" that shows up in the popup when an item is originating from another tool?

![image](https://cloud.githubusercontent.com/assets/11447474/12178058/6ff189ea-b53d-11e5-96d6-8419e73c85b3.png)

**Comment by steveswinsburg** [comment]
Hey @kyleblythe, last X added in the most recent PR. Ready for re-test. Cheers.

**Comment by kyleblythe** [comment]
Thanks, @steveswinsburg !

I think we'd like to be able to add two more popover messages:

* The category subtotal column color icon:

![image](https://cloud.githubusercontent.com/assets/11447474/12489218/3558a1fa-c03d-11e5-8f28-def468edead8.png)

This could include the following text: "Category Average for [Category Name]"

* The "+" icon in EC category rows:

![image](https://cloud.githubusercontent.com/assets/11447474/12489279/8194ed12-c03d-11e5-9098-389672189dc7.png)

This could include the following text: "This is an Extra Credit Category"

**Comment by kyleblythe** [comment]
Confirmed.
