### ISSUE TITLE
Category Subtotal Scores appear to be inaccurate when items have different point values and originate form other tools

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1472]
Category subtotals appear to be providing inaccurate percentages when items originating from other tools with different percentages are in place along with traditional GB items. See the following screenshot:

![image](https://cloud.githubusercontent.com/assets/11447474/11875188/7cd06a60-a4b1-11e5-8070-f51cd2c98844.png)

In this image, the first student (Albert Albertson) should have a subtotal score of 76.19% ((90+60+10) / (100+100+10)). However, it's reporting a subtotal percentage of 145.45%.

While I'm not entirely sure what's happening here, a simpler example is available in the 4th row (John Fitz Gerald). This student should have a subtotal score of 63.63%, yet the score reported is 700%. This appears to be because it's taking a 10/10 for the Assignments score and delivering 100%, then adding another 600% (60/10) to the original score.

**Comment by steveswinsburg** [comment]
Yeah sounds like it's adding percentages together. I wonder if the other tool (Assignments) sends the score as a percentage rather than the point value. Need to investigate.

**Comment by steveswinsburg** [comment]
@kyleblythe could you please retest this? I've done some category calculation work in other tickets and can not reproduce this calculation error. There are a couple of PRs in train to be merged.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

I think I've figured out what was causing this issue. It doesn't seem to necessarily have to do with items originating from other tools after all. Rather, it's caused by an item being excluded from course grade calculations. I created another issue for this ( #1590 ). We can probably go ahead and close this one.
