### ISSUE TITLE
Hide Cat Subtotals From Spreadsheet View When No Items are Present

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1487]
If no items have been added to a given category, hide the category's subtotal column from the GB spreadsheet interface.

**Comment by steveswinsburg** [comment]
Also noticed that if you have categories set, then choose no categories, then the categories continue to show. These should be suppressed.

**Comment by steveswinsburg** [comment]
@kyleblythe categories are shown in a bunch of places other than spreadsheet view, ie show/hide items, student summary window etc. We need to discuss the behaviour for these as well (tomorrow's call?)

**Comment by steveswinsburg** [comment]
Discussed on call. If categories are turned off, but an assignment is in a category, the categories are still showing the in the show/hide item panel and the grade summary panel. These should be suppressed.

**Comment by steveswinsburg** [comment]
Found a bug in this with the student view, fixing it and will send a new PR for that page.

**Comment by kyleblythe** [comment]
Confirmed.
