### ISSUE TITLE
Readonly cells show an input

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1492]
Introduced a bug with the input refactor which displays the input for readonly cells e.g. for external tools:

<img width="378" alt="screen shot 2015-12-22 at 1 26 30 pm" src="https://cloud.githubusercontent.com/assets/608337/11946538/d5eacef4-a8af-11e5-9915-1db8f34bef58.png">

**Comment by payten** [comment]
PR also fixes another issue introduced with the input refactor changes:

While I was in there I also found a bug whereby a programmatic change of input wasn't triggering an "onchange" event. For example, when a [0-9] key is pressed we use jQuery to set the value on the input e.g. $input.val(newValue).  In IE or Chrome this does not mark the input as 'changed'.  To resolve this we now trigger a custom javascript event and bind to this in Wicket.

**Comment by payten** [comment]
Oops.. and PR also fixes the toolbar styling illustrated in the screenshot above.

**Comment by steveswinsburg** [comment]
Done, ready for test.

**Comment by kyleblythe** [comment]
Confirmed!
