### ISSUE TITLE
Grade item menu items are not working in Firefox

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1496]
When using Firefox, the grade item menu items are not working (edit item details etc). There doesn't appear to be any error in the console.
The add gradebook item button and window appears correctly and the cell menu items (grade log, add comment etc) are working.

Everything seems to work ok in Chrome.

**Comment by payten** [comment]
Ah yep, so I relied on the `focus` event on links to keep the menu open, however, Firefox on OSX doesn't   include anchors in the tab index by default so there will never be a focus event triggered :cry: (http://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox).  I'll investigate a workaround.

**Comment by steveswinsburg** [comment]
Nice one.

**Comment by kyleblythe** [comment]
Confirmed!
