### ISSUE TITLE
Gradebook static resources are not cached by the browser

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1517]
.. as the response header don't provide a last-modified or cache-control, e.g.
<img width="977" alt="screen shot 2016-01-05 at 3 54 44 pm" src="https://cloud.githubusercontent.com/assets/608337/12107897/0d457c94-b3c5-11e5-8f23-b7a6bb12b7cb.png">

**Comment by payten** [comment]
PR adds a filter to the web.xml to add cache-control headers to the static resource responses, which will instruct browsers to cache the resource for 7 days (as per other Sakai tools). 

I've also added the `portal.cdn.version` to custom page resources (js, css) to allow for easy cache breaking.

**Comment by jeffpasch** [comment]
Confirmed!
