### ISSUE TITLE
"Edit Item Details" for Items Originating from Other Tools

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1529]
For items originating from other tools, the "Edit Item Details" option should still be available in the column header dropdown.

This lightbox window should, as with GB1, prevent users from editing the item's title, due date, and point value. However, it should provide the ability to:

* Mark the item as extra credit
* Assign the item to a category
* Select/deselect the release/course calculation options.

**Comment by steveswinsburg** [comment]
There is a hard restriction on editing an externally maintained assignment in the GradebookService. This will need to be changed so that only the above fields can be edited.

**Comment by steveswinsburg** [comment]
Created https://jira.sakaiproject.org/browse/SAK-30202 for the backend change.

**Comment by steveswinsburg** [comment]
Left the other PR open for a few days, haven't had any feedback or issues, merged. This is ready to test now.

**Comment by kyleblythe** [comment]
Beautiful - confirmed!
