### ISSUE TITLE
Add/Edit gradebook item category dropdown has blank first entry

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1548]
Add/Edit gradebook item category dropdown has blank first entry rather than a 'Select One' placeholder text.

<img width="391" alt="screen shot 2016-01-09 at 4 54 56 pm" src="https://cloud.githubusercontent.com/assets/129129/12214658/db604076-b6f1-11e5-9185-58cc6a7f9861.png">

**Comment by kyleblythe** [comment]
Confirmed.
