### ISSUE TITLE
Gradebook interface usability improvements

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1560]
From 1/7/2016 tech call:

1. Fix popover inside of student drill down can be cut off: http://www.screencast.com/t/Nd4UdAKwS
2. When no weighting, hide 0% on Grades tab: http://www.screencast.com/t/jl2P7N7fFv
3. Fix comment bubble alignment: http://www.screencast.com/t/5NKBcaZu9pN0
4. Ensure disabled inputs are visibly disabled: grey out include in course calc text: http://www.screencast.com/t/S57ON8GFj and EC when EC not allowed in EC Category: http://www.screencast.com/t/Ax5ygu44Z
5. Change “Add a Category” button in Settings to a link
6. Include text that says “Weighting for the categories must equal 100%” that shows up beneath categories (next to “Add a Category”) whenever the total doesn’t equal 100%

**Comment by kyleblythe** [comment]
Hi @payten ,

These all look great. Re: no. 4 above - the visible greying out of disabled inputs doesn't appear to be working in Chrome (though this might be a morpheus issue?):

![image](https://cloud.githubusercontent.com/assets/11447474/12335220/0927125e-bacc-11e5-87ec-5d2b73113d28.png)

**Comment by payten** [comment]
Hm.. @kyleblythe, would you be able to clear the cache and try again?  Now that we've enabled browser cache for the gradebook JS and CSS I've found myself having to clear my cache all the time!

**Comment by payten** [comment]
Hey @kyleblythe, annoyingly I'm seeing grey checkboxes locally and on SBX1. I have a feeling this may have been due to caching of the CSS.  Do mind having another test but clear your browser cache first?

**Comment by kyleblythe** [comment]
Hey @payten ,

Sorry about the delayed response on this one. So, I've cleared cache and I think we're seeing the same thing - the checkbox is greyed out, but the text is still displaying normally. Is it possible to make the text greyed out as well when the checkbox is disabled? Thanks!

**Comment by payten** [comment]
Hm.. I think we can fudge the grey text for the checkbox fields by customising the HTML and using some fancy CSS.

Two things to keep in mind:
1) this will only be for checkboxes.  We won't be able to easily apply similar styles for any other disabled field labels (dropdowns, textfields) without a major refactor our form HTML or by adding custom behaviours with JavaScript or Wicket.
2) this will be unique to GradebookNG.

**Comment by kyleblythe** [comment]
Confirmed.
