### ISSUE TITLE
Click on flag in fixed header doesn't invoke popover

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1572]
Raised in 14/1 tech call: "Popover on icon for coming from another tool, oddness on click: http://www.screencast.com/t/Q10OTUjFDT8" noticed as a lag in displaying the popover.

I believe this could be due to a bug in the javascript which wasn't correctly proxying the focus/click from the fixed header through to the real header cell.

**Comment by kyleblythe** [comment]
Confirmed.
