### ISSUE TITLE
Give indication that score changed in final and category average

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1574]
When setting a score, provide a visual cue that course grade and category average values have also been updated.  This could be a green fade-in / fade-out as per the success behaviour on a recently updated score cell.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/12488583/4e5f80ea-c03a-11e5-84b4-70d764cb9d1f.png)
