### ISSUE TITLE
Category Subtotal Scores Are Inaccurate When There is an Item Not Included in Grade Calculations

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1590]
If you have several items in a category, and uncheck the "Include in Course Grade Calculations" checkbox (or uncheck the "Release to Students" checkbox), the subtotal scores begin to incorrectly calculate for that category. Instead of averaging the scores, it begins to add the unreleased item's score to the average of the other items.

Example of a subtotal score when all items are included in grade calculations: http://www.screencast.com/t/i7yeinoSC0

The same subtotal score once an item has been excluded from grade calculations:
http://www.screencast.com/t/5u8ctYYmQGfz

**Comment by steveswinsburg** [comment]
The issue here is that the total points possible is only collected if its included in course grade calcs, but the total points earned is collected regardless.

**Comment by kyleblythe** [comment]
This is awesome @steveswinsburg . Great stuff, thanks! Confirmed.
