### ISSUE TITLE
Category row title repositions/flashes when scrolling vertically

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1605]
Reported in tech call 21/Jan:

> When scrolling downward, once the fixed column header appears, the Category row title appears on the far left, then disappears and fades into its center position: http://www.screencast.com/t/SmdEg1e0N

**Comment by kyleblythe** [comment]
Hi @payten ,

This is looking great - when scrolling vertically, the fixed category headers display in the same position that the other headers do. However, it looks like there's a new bug associated with this. Now, after an initial scroll or two, it looks like while the title in the initial category header continues to adjust, the titles in the 2nd, 3rd, etc. category headers do not:

http://www.screencast.com/t/cWsVJ5LyI

**Comment by kyleblythe** [comment]
Beautiful. Confirmed.
