### ISSUE TITLE
Improve usability of sorting actions and cell focus

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1607]
From tech call 21/Jan:

> Include the iconography that Payten showed in the jquery tablesorter into column headers to display that something is sortable. Maybe we can also move the up/down arrows that display when something is sorting to also appear on the far-right of the column header?
>   Related: Can we highlight the column header(s) that are currently sorting?

And possible change here:

> Firefox isn’t highlighting cells that are currently in focus
>   It IS actually highlighting, just a subtle dash.
>   Investigate override outline in cell context only to replicate chrome outline for all browsers

**Comment by payten** [comment]
Changes from 28/Jan tech call: 
- Remove double arrow icon from unsorted column
- Change link text to be black (as per standard font)
- On hover, show text as link color with underline

**Comment by payten** [comment]
From 1/28 tech call:

> Proposed update: Remove the “double arrow” (as this introduces yet another icon into the column header), but have the up/down arrows when actively sorted appear in the new position to the right of the item title. Modify the styling of the item title to not display as links. Upon hover, however, provide the blue text to signify that they can be clicked.

**Comment by steveswinsburg** [comment]
PR merged, ready to roll for testing.

**Comment by kyleblythe** [comment]
Beautiful - looks perfect. Thanks, @payten!

Confirmed.
