### ISSUE TITLE
Permissions page shows empty dropdown when no TAs in site

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1613]
If a site has no TA's, the instructions are printed properly but the dropdown still renders. This needs to be hidden.

<img width="640" alt="screen shot 2016-01-24 at 10 36 53 pm" src="https://cloud.githubusercontent.com/assets/129129/12536001/24073a0a-c2eb-11e5-8735-9de99191dcf9.png">

**Comment by kyleblythe** [comment]
Confirmed.
