### ISSUE TITLE
Changing the grading schema after model updated can fail to rerender

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1628]
In Settings, if you change the grading schema type and click save, then change it again, it should re-render. However because we are now preserving the model between requests, its no longer being reloaded.

This causes weird display behaviour.

**Comment by steveswinsburg** [comment]
Hey @payten flicking this to you if you would like to take a look. Have a look at the category panel, I think I did something similar to maintain the state (setModelChanged off the top of my head?)

**Comment by payten** [comment]
Hm, I'm probably missing something but I can't seem to replicate the issue as described.  However, I'm seeing that the "Letter Grades with +/-" isn't providing fields for the + or - letters at all (only shows A-D,F).  Could that be the issue?

**Comment by payten** [comment]
Ah.. I think I see the issue.  The `configuredGradeMappingId` isn't updated once the model is saved.  PR impending.

**Comment by kyleblythe** [comment]
Confirmed.
