### ISSUE TITLE
GradebookNG drop/keep highest/lowest not working.

### ISSUE THREAD

**Issue by willkara** [sakaiproject/sakai#1631]
Drop Lowest, Keep Highest, Drop Highest are not functioning. 
I made a GradebookNG a Attendance categories that Keep Highest 5. 
There were 6 Attendance items worth 1 point each. I gave the student five 1s and one 0. 
The grade was 83.something (5/6), not 100, if it were to keep the highest 5.
![screen shot 2016-01-27 at 10 50 18](https://cloud.githubusercontent.com/assets/3278887/12619057/6c589a56-c4e4-11e5-8809-c2084b4fc6bb.png)
![screen shot 2016-01-27 at 10 49 36](https://cloud.githubusercontent.com/assets/3278887/12619056/6c501976-c4e4-11e5-9a81-09980b092a86.png)
![screen shot 2016-01-27 at 10 47 40](https://cloud.githubusercontent.com/assets/3278887/12619058/6c5f9a0e-c4e4-11e5-8f11-841ab63aaa15.png)

**Comment by steveswinsburg** [comment]
This has already been reported in #1420.
