### ISSUE TITLE
Add dropdown to Course Grade header

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1639]
Within the course grade header, provide a dropdown menu that we can add various actions to.
This has been split out from the original issue (#1369) as it is a smaller piece of work that is required for a few other tickets.

**Comment by steveswinsburg** [comment]
I think that we also need this added to the individual course grade cells. The overall one is fine for some actions but not the 'per student' actions

**Comment by kyleblythe** [comment]
Confirmed.
