### ISSUE TITLE
Modify error text when invalid text is entered into cat weighting in Settings, then saved

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1697]
Current error message that is displayed when invalid text is entered into weight column for Categories & Weighting in Settings, then saved is:

The value of 'weight' is not a valid Double.

http://www.screencast.com/t/Esos6XhG

Should display error message of "The value entered in "Weight" field is not a valid number.

**Comment by steveswinsburg** [comment]
There is no field labelled 'weight' so I made the text:
"The category % entered is not a valid number."

**Comment by kyleblythe** [comment]
Confirmed.
