### ISSUE TITLE
Inaccurate percentage issue in Cat & Weighting when using decimals

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1698]
When entering odd decimal percentages into the "weight" field of Categories & Weighting (e.g. 79.8% and 20.2%), the percentage total can display inaccurately, totally 99.99% instead of 100%:

http://www.screencast.com/t/Tlpjokei8

**Comment by steveswinsburg** [comment]
I was able to reproduce another bug in this so I have fixed it in a separate PR

**Comment by kyleblythe** [comment]
Confirmed.
