### ISSUE TITLE
Error notification in cell persists after editing cell contents

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1700]
After producing an error in-cell, clearing out the contents of the cell does not always cause the red cell bg color to be cleared (not consistent):

http://www.screencast.com/t/jBz7Eiw1t

**Comment by kyleblythe** [comment]
Ah, ok, I see what's causing this to continue to occur. If you enter an invalid character into a cell and get the current triangle-warning error message in-cell, the previously saved score still appears in the cell. If you click into the cell again, don't change anything (since a valid score is appearing) and click out/hit the return key, the old error message still persists.

This will get addressed by the most recent requirements noted in issue #1380 .

**Comment by steveswinsburg** [comment]
#1380 is closed so I'm going to close this one also. If problem persists, reopen 👍
