### ISSUE TITLE
"Saving..." / "All Changes Saved" notification text at top of GB Grades screen

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1701]
Immediately to the right of the "+ Gradebook Item" button at the top of the Grades screen, add a persistent, non-obtrusive plain-text notification that displays the current save status (a la Google Docs).

Example: 

* When grades have been entered and are in the process of being saved, the text should display as "Saving..."

* When all grades have been saved, the text should display as "All changes saved."

If there is an error saving, ideally the text here could provide information re: the affected cell (either in the form of coordinates [i.e., student name and grade item] or by providing a link that would scroll to/highlight the affected cell).

**Comment by payten** [comment]
Sounds good.

Just to confirm, the position of the notification is such that it would only be visible when the user is scrolled to the top of the page.  When scrolled down the page and out of the view, it will remain out of view?

Also, if there are multiple error'ed cells, would they all be listed in this notification? Or just for the latest cell updated?

**Comment by kyleblythe** [comment]
Hi @payten ,

To your first question - yep, that sounds good. This is just some extra peace of mind, so it's ok for it to not be visible when scrolled down.

As for the second question - after chatting with Jeff on this, we realized it might not make sense to provide details in the plain text notification, when error messages are already appearing in red boxes above the "+ Gradebook Item." So instead, if there's an error, perhaps we can just have the plain text notification state "An error was detected." The error itself can then appear in place of our existing "Oh dear" error message in the red box at the top of the screen.

**Comment by payten** [comment]
Coolies.

One more question about the errors, should this error state be noted if invalid entries are detected?  Currently there are two kind of "errors":

1. Entering a string `abc` results in an invalid message and a yellow exclamation flag, which differs to
2. An exception from the service resulting in a red exclamation flag e.g. caused by entering a super long value `123456789`.

They kind of feel like they would invoke the same error state... except one is critical (service blew up) while the other is due to user error :confounded:

**Comment by kyleblythe** [comment]
Hi @payten ,

Sorry, realized I never responded to this. Might be worth talking through this one during this week's call.

Right now we're delivering error messages directly in the affected cell. Is it necessary to include errors in the "Saved" notification? It could just say "Errors were detected. See cell notifications below" or something to that extent.

**Comment by kyleblythe** [comment]
Hey @payten ,

Currently, this looks like a pretty obtrusive notification at the top of the screen (when you enter a score, the notification appears and pushes all of the other content on screen downward):

![image](https://cloud.githubusercontent.com/assets/11447474/14898937/8e1db0b6-0d57-11e6-8872-5b911b299f91.png)

I'm wondering if it's possible to, like with Google Docs, provide a very basic next notification to the right of "Add Gradebook Item." This could, even when the tool is first loaded, say "All changes saved." Then, as content is added, it can show "Saving..." if the save action takes longer than [x] milliseconds/seconds. It could then switch back to "All changes saved." And if there's an error/loss of connectivity, we could replace the text with "Error saving" and have a more obtrusive error message appear at the top of the screen (which happens currently anyway).

**Comment by kyleblythe** [comment]
Much better :)

I'm wondering if we could maybe move this alert to be aligned left, so that it maybe displays to the right of the "Add Gradebook Item" button, rather than centered. And maybe it could be persistent, a la Google. So even when you first enter the tool, it will say "All changes saved."

I also don't know if we need the grey container around the text. I think plain text would be fine (bc, again, this doesn't have to draw people's attention at all, it's just a great notification to have).

![image](https://cloud.githubusercontent.com/assets/11447474/15052849/b7b33b00-12cd-11e6-8898-4a2bbb4b0eb5.png)

Tricky, though, as I'm noticing that this doesn't appear for the TA, because they don't see the row that "Add Gradebook Item" displays on...is it possible to still have this notification appear, perhaps just to the far-left, above the filter/show-hide row?

**Comment by kyleblythe** [comment]
YES! @payten , you rock. This looks perfect.

![image](https://cloud.githubusercontent.com/assets/11447474/15215643/77531ea0-1821-11e6-9c43-eca9fbdd3c04.png)

Confirmed and closed!
