### ISSUE TITLE
Improve performance of scroll

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1753]
From tech call 18 Feb.

Scrolling on the gradebook spreadsheet page can be laggy with larger datasets.  Investigate if we can improve scroll performance and what refactoring needs to be done to achieve this.

**Comment by payten** [comment]
Hi @kyleblythe.  This PR has been merged now and contains some improvements page load time and scroll performance.  It might be just worth doing a quick poke-test to make sure the world isn't broken.. but hopefully it should *feel* faster :speedboat:

**Comment by kyleblythe** [comment]
Hey @payten,

I can definitely seem some faster loading and improved scrolling performance in average-sized courses. Nice! We can discuss during our call.

**Comment by payten** [comment]
From #1790, here's what was in the first iteration of fixes:

>Here's a breakdown of the techniques to do so... for scroll render performance:
> - remove animations where possible
> - move all non-necessary actions from the scroll event critical path
> - simplifying the fixed header HTML
> - cache element widths used in fixed column/header calculations
> -move toolbar from scrollable container so it doesn't need to be positioned/rerendered and change the > - fixed columns to the position: fixed rather than absolute
> - move all render actions into a single scroll handler, wrapped with a call to window.requestAnimationFrame() to ensure that the minimum amount of redraws per scroll event are invoked
>
> To improve page load times:
>
> - move the generation of the category header to the Wicket template. Ideally this would be a part of the existing DataTable, but there's not clear way to add multiple header rows (I'll leave this as a TODO).
- use setTimeouts to move non-essential javascript from the load critical path
- move as much CSS and element attribute changes to the Wicket template where possible
ensure the category average columns are in the correct order in the Wicket template so the javascript doesn't have to manually move them around
- To improve the speed in showing a dropdown menu, I had to refactor how we handle closing the popovers. I've also made a first pass at ensuring jQuery.find calls are more specific to improve selector performance. More work can be done here.

**Comment by payten** [comment]
Some more things to do:
- reduce size of the cell HTML where possible by removing popovers, CSS, data attributes where possible
- also try removing the input field and inserting that on demand
- aim to dynamically load in as much as possible

The goal will be to reduce the footprint/bytes of each cell so that larger gradebooks don't freak out.

**Comment by kyleblythe** [comment]
Confirmed - scroll performance on GB's with ~50 students is working much better!
