### ISSUE TITLE
Points/Categories Only: Display Logic & the Enter Key

### ISSUE THREAD

**Issue by lgekeler** [sakaiproject/sakai#1777]
Steps to reproduce:
1). Add GBNG to site
2). Click Settings
3). Expand All, accept default "Points only" 
4). Click "Categories Only"
4) Type in Assignments, hit enter key (category disappears)
5) Type in Assignments, hit tab (nothing happens)

Expected behavior: Tab or Enter both save the category and open a new category, placing the cursor in the field ready to type again.
Acceptable solution: Tab does the above, while Enter does nothing.

**Comment by kyleblythe** [comment]
Currently, the tab takes you to the next area of focus (i.e., from the category "title" field to the "%" field, which I think is consistent with the tabbing behavior seen elsewhere.

The "Return" key issue definitely shouldn't be removing entire categories, however, and ideally should invoke the "add a category" action, as you described.

Thank you for pointing this out - much appreciated!

**Comment by steveswinsburg** [comment]
While we are on this I noticed the drag handle for the categories has an underline, at least in FF:
<img width="35" alt="screen shot 2016-02-25 at 7 20 59 am" src="https://cloud.githubusercontent.com/assets/129129/13300259/6318c270-db93-11e5-91e7-882c76649d68.png">

**Comment by kyleblythe** [comment]
Ah, yep! That's related to the icon issue I captured in #1424, which is providing the category drag-n-drop.

**Comment by kyleblythe** [comment]
Confirmed!
