### ISSUE TITLE
Recommendations from accessibility audit

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1789]
- [x] add labels to tab list so it can be identified as a tab list:
> The Active tab is static text, unselected tabs are links. In order to make the tabs more recognizable to screen reader users,  add "tab" and "tab selected" to the tab labels as hidden text

- [x] remove aria-haspopup from any action that invokes a dialog.  This ARIA attribute is meant for popup menus not dialogs.

- [x] ensure all dialogs have a meaningful label and aria-labelledby matches accordingly
> The (Add Gradebook Item) dialog is labeled by an empty H3 element, which means the dialog has no name. Instead, the "Add Gradebook Item" H2 should be used to label the dialog.

- [x] give the sections filter dropdown a title or aria-label

- [x] ensure aria-haspopup is used instead of aria-popup

- [x] add aria-pressed attribute to the "Group by Categories" toggle button to illustrate it's current state

- [x] make the "Show / Hide" menu panel navigable with up/down arrow keys

- [x] update the table markup:
> The &lt;table&gt; element has role="grid", but the &lt;tr&gt; and &lt;td&gt; elements do not have any roles. They should be given role="row", role="gridcell", role="columnheader" and role="rowheader" appropriately. 
> Currently the column headers are marked up as role-less TD's, they should be TH elements with scope="col" and role="columnheader" attributes. 
> Since the column headers contain a lot of information and controls, they should be given a simple name through both the abbr and aria-label attribute. This way, if a cell has its corresponding  column header announced, it will only announce the abbr value and not all the other contents of the column header cell.

- ~~XX dynamically update the tabindex attribute instead of applying `tabindex=1` to all cells~~
>The cells themselves are all in the tab order due to tabindex="0" attributes. To unclutter the taborder, the value should be changed to -1. The focusable elements inside the cells can still be in the tab order, and the cells themselves can be reached through arrow key nav. In order to keep the grid itself part of the tab order, the currently active (i.e. highlighted) cell should always have a tabindex value of 0. This means that as keyboard focus is given or removed from a cell the cell's tabindex value should be updated (to "0" and "-1" respectively).

- [x] add a label to the dropdown menu action in a cell
> The dropdown buttons should describe which column or cell they apply to in their aria-label value. They should also be given a role="button" attribute, and an aria-expanded attribute that is set to "false" when the dropdown is collapsed and "true" when the dropdown is expanded.

**Comment by payten** [comment]
I struck the "dynamically update the tabindex attribute instead of applying `tabindex=1` to all cells" task for now as this would require quite a large refactor of the keyboard navigation code.  Perhaps an alternative would be to offer a quick way for screenreaders to jump over the table or jump to the beginning of the table?

**Comment by payten** [comment]
These changes are now merged @kyleblythe.  Many of the accessibility changes are under the hood and within the HTML DOM and can be confirmed via the inspector.  In regard to testing, I think we just want to keep an eye on any regressions as many of the changes will only be truly testable via a screenreader.

**Comment by kyleblythe** [comment]
Closing this one out.
