### ISSUE TITLE
GradebookNG language not depends on Sakai User Preferences

### ISSUE THREAD

**Issue by raulsv** [sakaiproject/sakai#1792]
The GradebookNG language not depends on Sakai User Preferences. The GradebookNG language only depends on the browser language.

Steps to reproduce the issue:

1. Change the user language in the User Preferences.
2. Go to GBNG. The tool language has not changed.
3. Change the browser language.
4. Go to GBNG. The tool language has changed.

**Comment by kyleblythe** [comment]
Was able to replicate. Thanks!

**Comment by jonespm** [comment]
I'm not sure what it's using to determine the language but the order for Sakai to be consistent is either to use the system language or get the language from the resource loader if logged in. Browser language currently isn't considered by the ResourceLoader.

the getObject call here is basically the pattern.

https://github.com/rsf/SakaiRSF/blob/master/src/java/uk/ac/cam/caret/sakai/rsf/locale/SakaiLocaleDeterminer.java

**Comment by steveswinsburg** [comment]
It was using the built in Wicket Locale detector. I've changed it to use the same pattern as in Profile2.
