### ISSUE TITLE
Cannot add or edit any grade item

### ISSUE THREAD

**Issue by raulsv** [sakaiproject/sakai#1794]
Steps to reproduce the issue:

1. Create 2 categories (it doesn't matter if they are weighted or non weighted categories).
2. Create a grade item and assign it to a category.
3. Change the GBNG mode to "No categories".
4. Try to add or edit a grade item. Both options don't work.

**Comment by kyleblythe** [comment]
Thanks for find this bug, @raulsv !

**Comment by raulsv** [comment]
You're welcome @kyleblythe

**Comment by steveswinsburg** [comment]
Getting this console error:
`TypeError: self._CATEGORY_DATA[category] is undefined`

**Comment by payten** [comment]
Hm.. this shouldn't have been closed.

**Comment by kyleblythe** [comment]
Confirmed.
