### ISSUE TITLE
Retain "edit mode" in next cell after setting a score and hitting return 

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#1813]
Also from the accessibility audit performed on the GradebookNG tool but more related to usability.

It was suggested we look to retain the "edit mode" as the user makes changes in a cell, essentially focusing on the input rather than the cell as return submits the score.

Is the ability to hit a number key when focused on the cell enough?  Or would it make more sense for the user to see the input and out-of label as they progress through the recording their scores (as per the original prototype http://paytengiles.com/nyu/gradebook-prototype/)?

**Comment by payten** [comment]
From dev call:
- 'tab' key should retain standard tab flow, so tab when in "edit mode", should tab to the next focusable element in the tab flow.
- 'arrow' keys navigate to next cell and retain edit mode if cell is editable

**Comment by kyleblythe** [comment]
Confirmed!
