### ISSUE TITLE
New Display Column for GradebookNG running Course Grade

### ISSUE THREAD

**Issue by lgekeler** [sakaiproject/sakai#1825]
Add to options for display of running course grade:
Display the grade point value assigned to the letter grade along with the letter grade. Displays to students and to instructors.
(Does not involve calculating the GPA, only displaying the grade point value).

https://docs.google.com/document/d/1KuGqA8KIs0H1ZZZGbgaMfVfcqATjBCyHse2rYiAvorw/edit?usp=sharing

**Comment by steveswinsburg** [comment]
#1367 will provide course grade points as well as a toggle to hide and show so this might be resolved with that. It should be in very soon.

**Comment by steveswinsburg** [comment]
This is being resolved as a separate piece of work with ND. Closing this ticket.
