### ISSUE TITLE
Non released item: Wrong message

### ISSUE THREAD

**Issue by raulsv** [sakaiproject/sakai#1842]
Steps to reproduce:

1. Create a grade item which is not released to students.
2. A wrong message is displayed when you place the mouse over the 'eye' icon: "Gradebook Item has been released and is visible to students."

Please see the attached image.

![not released](https://cloud.githubusercontent.com/assets/10761548/13422300/29d19d2a-df94-11e5-8abd-d57af5a51513.png)

**Comment by steveswinsburg** [comment]
This was fixed about a week ago, please update. Cheers.

<img width="341" alt="screen shot 2016-03-01 at 9 08 10 pm" src="https://cloud.githubusercontent.com/assets/129129/13423880/bc102744-dff1-11e5-8760-83298775230c.png">

**Comment by raulsv** [comment]
Sorry I was testing in the "11.x Maintenance Branch on Oracle" due to the weekly 11 qa test fest:
https://docs.google.com/document/d/1cGMEvgDh_BiIX1mWR2YBnH1cFBNPwQEiZ5Fbju4aCyw/edit#

Regards,
Raúl
