### ISSUE TITLE
Category header inaccurate, displaying wrong items, scroll pop up animation lost

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1856]
There's a little bit of weirdness going on with the category header display when grouped by category. The category header itself is correct (in this case, Homework should be the first category), but the items contained therein are actually those that belong to the "Participation." Additionally, the item "Final," which belongs to the "Final" category, is showing up _after_ the category subtotal for Participation, still within the "Homework" category.

![image](https://cloud.githubusercontent.com/assets/11447474/13504994/f98ad25a-e144-11e5-89f1-dcf3f0d78afc.png)

Also, the styling of the percentage in the category header is now a little hard to read, and the subtle fade-in animation following scroll has been lost - it now just pops into place.

**Comment by payten** [comment]
I think the ordering problem will be fixed in #1789 which is awaiting merge.  Will double check once that has been merged.

**Comment by payten** [comment]
Hi @kyleblythe.  I think this was resolved in the PR for #1789 which contained a little refactor of the code responsible for sorting those columns.

**Comment by kyleblythe** [comment]
Hey @payten ,

Yep - the category ordering is working great. Might it be possible to change the styling of the category percentages a bit? Right now the percentage text seems to have a white drop-shadow, which makes it a little hard to read:

![image](https://cloud.githubusercontent.com/assets/11447474/13848061/80f03a00-ec26-11e5-88cf-3b4950d388c4.png)

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/14287121/99be0f14-fb1f-11e5-8623-6d39f4447e29.png)
