### ISSUE TITLE
Category association still shows up in items' "Edit Item Details" screen when categories have been disabled

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1857]
When you have previously created categories, then gone back and disabled categories and weighting, you will still see the category association (as well as all of the category dropdown options) in items' "Edit Item Details" screens.

![image](https://cloud.githubusercontent.com/assets/11447474/13505135/af23e08e-e145-11e5-86ac-0eec1c9cd400.png)

**Comment by steveswinsburg** [comment]
Ah good catch. Will fix. I think this was just going off the assignment itself having a category.

**Comment by kyleblythe** [comment]
Confirmed.
