### ISSUE TITLE
Some buttons in interface are empty

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1858]
For some reason, some of the buttons in the interface are empty (and only show their contents on mouseover):

![image](https://cloud.githubusercontent.com/assets/11447474/13505789/c6092914-e148-11e5-9972-ce2a791cc2da.png)

This may be a Morpheus issue, but wanted to drop it in.

**Comment by payten** [comment]
Hm.. it seems that the Morpheus styles are conflicting with the Bootstrap button styles, whereby Morpheus is forcing white text and Bootstrap is setting a white background. 

We're not the only tool that use Bootstrap, so I presume this is a wider issue.  However, we could remove all Bootstrap button styles and allow Morpheus to control their styles? I might be wrong, but I think we'd lose the ability to distinguish between buttons as Morpheus has a single button-style e.g. Submit would look like Cancel.

**Comment by steveswinsburg** [comment]
Probably worthwhile raising this as a bug for Morpheus. I thought it was ok to use bootstrap styles so someone has broken something.

**Comment by jonespm** [comment]
I noticed this today in content too. There's a lot of javascript errors about missing fonts and icons too.

https://jira.sakaiproject.org/browse/SAK-30481

**Comment by kyleblythe** [comment]
They're showing up now, which is great. Just as a quick note - they are showing up as plain text, though:

![image](https://cloud.githubusercontent.com/assets/11447474/15215862/9fefed6a-1822-11e6-8813-21ebaaaaa82a.png)

Do we want this to by styled as a plain grey button, or stick with text? I'm ambivalent.

**Comment by payten** [comment]
Yep, let's change all btn-link buttons to use btn-default so we consistently have a grey button for secondary actions.

**Comment by kyleblythe** [comment]
These are looking much better - thanks! Quick note - it looks like their alignment is a little off when they're sitting next to a blue action button:

![image](https://cloud.githubusercontent.com/assets/11447474/15372865/9a5b1a44-1d10-11e6-89c2-73050f884434.png)

![image](https://cloud.githubusercontent.com/assets/11447474/15372867/a09a4ede-1d10-11e6-9f9e-68337c27a73e.png)

**Comment by payten** [comment]
The slight button differences has been fixed through changes delivered in SAK-31187.

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/15611705/a2624ec0-23f9-11e6-8f81-6e5e652b9dc2.png)
