### ISSUE TITLE
Double header cell when scrolling in Firefox

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#1914]
When scrolling in GradebookNG, the student header cell is being copied and is floating down with the scroll.

<img width="880" alt="screen shot 2016-03-11 at 7 13 49 am" src="https://cloud.githubusercontent.com/assets/129129/13683064/dd9d8e88-e758-11e5-8030-77ca7704d682.png">

**Comment by payten** [comment]
Any tips on replicating this one? I haven't had much luck.

**Comment by steveswinsburg** [comment]
Verified. Thanks @payten :cake:
