### ISSUE TITLE
Category weights are rounded in the grades main table

### ISSUE THREAD

**Issue by raulsv** [sakaiproject/sakai#1927]
Steps to reproduce the issue:

1. Create 2 weighted categories. c1: 25.5% and c2: 74.5%
2. Create 2 grade items and assign them to the categories.
3. The categories weights are rounded to 26% and 75% in the grades main table.

Please see the attached images.

![image1](https://cloud.githubusercontent.com/assets/10761548/13777457/a43c56b4-eab0-11e5-8158-2d81ed5ef539.png)

![image2](https://cloud.githubusercontent.com/assets/10761548/13777456/a43c04ca-eab0-11e5-9b7e-0f3250b8c90b.png)

**Comment by steveswinsburg** [comment]
Hey @payten is there any rounding going on here or are you displaying exactly what the Assignment/Category is giving you?

**Comment by payten** [comment]
Ah yep, sorry.  I assumed integer values. PR submitted which will round this display string to two decimal places (as per other double values in the tool).

**Comment by steveswinsburg** [comment]
Hi Raul, @payten has fixed this and it is ready to test :+1:

**Comment by raulsv** [comment]
Thanks! It works fine. Tested in https://trunk-oracle.nightly.sakaiproject.org/portal.

**Comment by kyleblythe** [comment]
Confirmed and closed.
