### ISSUE TITLE
Item titles should be truncated after a certain length

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1931]
there doesn't appear to currently be a limit on Gradebook item title length.

![image](https://cloud.githubusercontent.com/assets/11447474/13792490/76979d5a-eac8-11e5-82e1-f5f3b983f1a1.png)

We should impose a limit of [x] characters, and potentially use an ellipsis in the middle of the item's title, so as to show the beginning and end of the item title.

**Comment by steveswinsburg** [comment]
Will use `StringUtils.abbreviateMiddle()`.
@kyleblythe, what length should we have? 25, 30?
Also will this only be in the spreadsheet view or in the student summary as well?

**Comment by steveswinsburg** [comment]
Set at 45 which is about the max I could make it for two lines of column header without having it trimmed:

<img width="559" alt="screen shot 2016-03-16 at 9 01 50 pm" src="https://cloud.githubusercontent.com/assets/129129/13808496/6a8821fe-ebba-11e5-8107-3f717839909a.png">

In the show/hide panel:
<img width="353" alt="screen shot 2016-03-16 at 9 01 56 pm" src="https://cloud.githubusercontent.com/assets/129129/13808490/65b0b588-ebba-11e5-9450-6b0703d87d42.png">

In review mode, no truncation:
<img width="603" alt="screen shot 2016-03-16 at 9 02 47 pm" src="https://cloud.githubusercontent.com/assets/129129/13808511/78f9f690-ebba-11e5-9ac5-f0b02f4164a5.png">

Top banner, no truncation:
<img width="1048" alt="screen shot 2016-03-16 at 8 57 41 pm" src="https://cloud.githubusercontent.com/assets/129129/13808345/d37ce9ca-ebb9-11e5-8de5-cde869a0da97.png">

Edit grade item, no truncation:
<img width="444" alt="screen shot 2016-03-16 at 8 59 21 pm" src="https://cloud.githubusercontent.com/assets/129129/13808393/030cd056-ebba-11e5-90cf-4b60a99864c2.png">

**Comment by kyleblythe** [comment]
Hey @steveswinsburg ,

This was fast! Thank you :) I think the truncation works great. Quick note:

* The text is butting up pretty closely to the right edge of the item. Maybe we can have the text wrap a little sooner, and cut it down a few more characters (maybe 40 instead of 45?) so that there's a little more padding on the right:

![image](https://cloud.githubusercontent.com/assets/11447474/13847880/c432a8a8-ec25-11e5-87cc-2200d696f399.png)

* Would it be possible to use ellipses instead of just cutting off the text. Ideally, if we could place the ellipses in the middle of the text (perhaps at the end of the first line?), so that the truncation shows the beginning of the item title on the first line and the end of the item title on the second line?

**Comment by steveswinsburg** [comment]
Ellipsis in the middle is definitely there. I have added a margin so it doesn't overlap. See screenshot.
![screen shot 2016-06-16 at 10 58 23 pm](https://cloud.githubusercontent.com/assets/129129/16117587/3466e048-3416-11e6-8835-6b860294d007.png)

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16269224/761a80ec-385f-11e6-82b8-994f84957ee5.png)
