### ISSUE TITLE
Empty Category Header Row Appears When No Categories are Enabled:

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#1961]
![image](https://cloud.githubusercontent.com/assets/11447474/13848407/03fdee82-ec28-11e5-8b4f-53605b3871ed.png)

**Comment by payten** [comment]
Hi @kyleblythe.  Any tips on how to reproduce this?  Did you have categories and then disable them? Did resetting the tool fix it? Thanks.

**Comment by kyleblythe** [comment]
Hi @payten ,

Yep, I did the following:

1. Set up GB with categories & weighting and items
2. Go back and disable categories & weighting
3. the category header row should still appear. Upon reset, it should still appear.

I'm seeing it in this site: https://sandboxclasses1.home.nyu.edu/portal/site/0866a09a-9673-4d31-8a2c-e8a9f2c0b1dd/tool/4fe51b5b-75b4-4a13-960a-1a421445aeaa

**Comment by kyleblythe** [comment]
Confirmed.
