### ISSUE TITLE
Wicket Ajax error when attempting to add new GB items

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2014]
Laura Cira reported a wicket ajax debug error when attempting to add new GB items in an empty, cleared cache version of the GB.

**Comment by payten** [comment]
Hi @kyleblythe.  Are there any more details on this bug available? A stacktrace/log would be awesome!

**Comment by steveswinsburg** [comment]
This could have been caused by a timeout. Once the app is put into production mode that box will go away and the error should ideally be handled by the portal. But yeah a stacktrace would be great.

**Comment by kyleblythe** [comment]
Hey @steveswinsburg & @payten ,

Apologies, but I haven't been able to replicate the issue. Will continue to play around, and if I'm able to get the error to occur I'll capture a stacktrace for it.

**Comment by steveswinsburg** [comment]
Note that we are now in production mode so you will likely get a different error, from the portal ideally.

**Comment by steveswinsburg** [comment]
Closing this to get it out of the way, reopen if you see it again 🐢
