### ISSUE TITLE
Grade Items rolled up into "Uncategorized" category when No Category setting is enabled

### ISSUE THREAD

**Issue by lgekeler** [sakaiproject/sakai#2063]
Use these settings: [http://www.screencast.com/t/o4dgw0MZxQ8](url)

No Categories are configured for use in this Gradebook.

The "Uncategorized" bucket is still displayed in the Student Grade Summary: [http://www.screencast.com/t/PByjx3wXY](url)

**Comment by kyleblythe** [comment]
Another good catch :) Thanks, @lgekeler !

When no categories have been enabled in the GB, items should display in the Grade Summary/Student Review Mode/Student View without any sort of category header.

For reference, here's how this displays for students in GB1: 

![image](https://cloud.githubusercontent.com/assets/11447474/14153311/58e47828-f685-11e5-9e00-53e5847504ea.png)

**Comment by kyleblythe** [comment]
Confirmed!
