### ISSUE TITLE
NPE when sorting by category

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2091]
The category comparator that is in Assignment makes a couple of assumptions that can cause an NPE when sorting.
1. That sort order is not null.
2. That category is not null.

For example:
````
return one.getSortOrder().compareTo(two.getSortOrder())
````
and:
````
one.getCategory().equals(two.getCategory())
````

Note that this was from an old site so might not manifest in new sites however would be a problem for anyone upgrading.

**Comment by kyleblythe** [comment]
Unable to replicate - this one seems to be resolved. Can always re-open if we're able to reproduce.
