### ISSUE TITLE
Add more granular exceptions in GradebookService when grade is not valid

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2119]
From #1380 

We need to add more exceptions to the GbService so that it is clear what the actual problem was when saving a grade that was invalid.

"There's no quick way to split up the errors in the current service code without refactoring how `isGradeValid` interacts with `identifyStudentsWithInvalidGrades` and `saveGradesAndComments`. 

This could have impacts on anything using the gradebook service.

**Comment by jeffpasch** [comment]
won't fix
