### ISSUE TITLE
Course grade override panel can be formatted with 'null' if no data exists

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2141]
I found a case in a new site where there was no data and the course grade override log panel data was formatted with null strings. In addition the `<br>` is being output explicitly.
This needs a bit of attention to handle the case where no data exists.
![screen shot 2016-04-07 at 7 42 55 am](https://cloud.githubusercontent.com/assets/129129/14333959/9ecbd4e8-fc94-11e5-8ff4-ae5053803b98.png)

**Comment by steveswinsburg** [comment]
The output of the BR tag is fixed in #2473, need to check the other cases.

**Comment by steveswinsburg** [comment]
See also http://www.screencast.com/t/QaCDJwH2XCU, can also get a 0/-1 presumably a division error, when items with grades are excluded from course grade.

**Comment by kyleblythe** [comment]
Confirmed.
