### ISSUE TITLE
Comment flag in cell not displayed when there's a comment but no score

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#2143]
The comment for a particular cell is only retrieved from the service if the cell has a score.  This means the comment flag for an empty cell is not displayed even if a comment has been added for a particular grade.

To replicate:
1. Find a grade cell that has never had a score set before
2. In the cell's menu, select Edit Comment
3. Enter a comment and hit "Save Comment"
4. Cell will render with the speech bubble flag within the cell
5. Reset the tool via the breadcrumb
6. The cell no longer shows the speech bubble flag

**Comment by payten** [comment]
@jeffpasch, @kyleblythe, @steveswinsburg - I just rediscovered this issue. Not sure it's a priority , but if we let it go perhaps we should hide the "Edit Comment" menu option until there's a grade entered?

**Comment by jeffpasch** [comment]
Hi Payten. I believe we have at least some instructors that use gradebook for providing seating assignments for exams, using the comments field in a grade item without inputting an actual grade. Maybe other schools do similar things...so probably a good one to try to get in if possible.

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/15215958/f8542eee-1822-11e6-92ae-f05294e8eded.png)

![image](https://cloud.githubusercontent.com/assets/11447474/15215963/010706ce-1823-11e6-8ea8-c2b9f3ecef0e.png)
