### ISSUE TITLE
Show/Hide Grade Item regressions

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#2166]
- [x] Student info column headers continue when scrolling down - http://www.screencast.com/t/JA1fVeuk41 
- [x] Column width when hiding items - http://www.screencast.com/t/NBlZ0RpVQe 
- [x] Hide All is retaining some parts of the columns - http://www.screencast.com/t/AczPXtpA 
- [x] "Showing X of Y items" label no longer in sync with visible/hidden columns

**Comment by kyleblythe** [comment]
Confirmed!
