### ISSUE TITLE
Date options for adding an item in GradebookNG are missing labels/un-intuitive.

### ISSUE THREAD

**Issue by willkara** [sakaiproject/sakai#2176]
When you're manually adding an item in GradebookNG, the options for specifying a date seem to be a little messed up.

- They're not flush with the input box.
- No labels for what they are/do.

![screen shot 2016-04-08 at 11 37 38](https://cloud.githubusercontent.com/assets/3278887/14389181/6c1a2964-fd7f-11e5-8944-cee8a05da3eb.png)

**Comment by payten** [comment]
Related to #1858.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/15215981/16939c78-1823-11e6-91c8-76de17fb408c.png)
