### ISSUE TITLE
Change WEB-INF/web.xml configuration to deployment

### ISSUE THREAD

**Issue by jonespm** [sakaiproject/sakai#2225]
I believe that both in master and 11.x we can just change this wicket configuration over to deployment. If you want to start with the wicket debug (for development) all you need to do is enable the JAVA_OPT

 -Dwicket.configuration=development

This was an issue in the past on profile2 when it got in a few times without being changed, but it for sure should be changed in 11.

**Comment by payten** [comment]
Closing. Deployment mode is on.. and it's beautiful.

**Comment by jonespm** [comment]
Thanks! I run with that option now in dev all the time too which is nice that all tools come up with the window.
