### ISSUE TITLE
As TA, grades cannot be edited on Gradebook with disabled categories

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#2234]
To replicate,

1. Create a Gradebook with Categories and a TA with GRADE access to All Categories and All Sections/Groups.
2. Login as the TA and cells should be editable
3. As instructor, change the gradebook to No Categories to disable categories
4. Login as the TA and cells have become locked despite TA permissions remaining unchanged

**Comment by kyleblythe** [comment]
Confirmed.
