### ISSUE TITLE
Disabled categories show in permission settings form for TAs

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#2235]
When categories have been disabled, any pre-created categories still show up in the Permission settings "Add Rule" form.

If no categories, should the "All Categories" dropdown be hidden?

Also when checking permissions, if "no categories" is selected, should any previous category-scoped permissions created for the TA assume "the entire gradebook"?  I guess it comes down to a syncing issue between the category settings and category-scoped permissions.

**Comment by kyleblythe** [comment]
Confirmed.
