### ISSUE TITLE
As TA, "Set Score for Empty Cells" doesn't appear when you have grade for "All sections/groups" selected

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2272]
This probably relates to the changes made in #1376, since it's now looking to specific sections wherein grading access is provided.

**Comment by kyleblythe** [comment]
This is up and running. However, interesting issue:

When the TA has a single rule providing grade access for "All sections/groups," the individual sections/groups do not appear as selectable options in the "Set Score for Empty Cells" dropdown, even though they can filter by section/group in the primary filter on the Grades screen:

![image](https://cloud.githubusercontent.com/assets/11447474/14899500/47d05fd4-0d5a-11e6-975f-6c655e76629b.png)

Is there a way to provide cascading section permissions for "Set Score for Empty Cells" when grading access for "All sections/groups" is applied?

**Comment by payten** [comment]
Interestingly, when categories are enabled everything is peachy.. this only happens when the Gradebook has categories disabled.  Will dive in...

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/15052801/682087f0-12cd-11e6-8e1a-4494e5f53050.png)

![image](https://cloud.githubusercontent.com/assets/11447474/15052739/14acf4fa-12cd-11e6-883b-d4ce5ca1f612.png)
