### ISSUE TITLE
"Categories" TA permission dropdown should be disabled when "No Categories" are selected in Settings

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2273]
When you save TA permissions with a category selected, then change the GB's settings to "No categories," the TA suddenly has view permission for ALL GB items.

Either:

1. The category dropdown should be disabled, frozen with "All GB items" displayed, or
2. Perhaps the "Category" dropdown gets replaced with an item-level dropdown, where permissions can be applied to individual GB items.

**Comment by payten** [comment]
While option (2) is definitely the groovier of the two, it'd require enhancing the data model and services to support it - permissions are tied to a category and group and would need to be extended to relate to a specific grade item.

I've gone ahead with option (1) for now.

**Comment by kyleblythe** [comment]
Beautiful! Confirmed.
