### ISSUE TITLE
Sections/Group dropdown should only show groups TA can see

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2297]
Split out from #1366:

Currently, the TA's section/group filter dropdown shows as "All Sections/Groups," regardless of which section(s) the TA has access to:

![845901e0-fb21-11e5-84d6-5370bb8f238d](https://cloud.githubusercontent.com/assets/129129/14708411/139e9312-080e-11e6-9b6e-e39e661a1e43.png)

I think we had discussed the following:

If the TA does not have grade or view access to all sections/groups, this filter should reflect the sections/groups to which they do have access. So, for example, if a GB has 4 sections, and the TA has access to grade section 001 and view section 002, then the filter should default to "Available Sections/Groups" with the dropdown options showing the sections/groups. I think that'll clarify this a bit.

And, if the TA has grade/view access for only one section/group, I don't think there needs to be a dropdown at all. It can just say "Section 001 - Showing 7 Students". Does that make sense?

**Comment by payten** [comment]
Reopening.. as hasn't been tested yet.

**Comment by kyleblythe** [comment]
Fantastic. Confirmed!
