### ISSUE TITLE
GradebookNG shows student count but no students, if there are no items

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2299]
If there are no gradebook items but there are students, GradebookNG shows the count of students, but doesnt actually show them.

See screenshot:

![screen shot 2016-04-21 at 11 11 08 pm](https://cloud.githubusercontent.com/assets/129129/14709925/91fa5d42-0816-11e6-83cc-f8e01e087005.png)

One solution might be to always show the students.

**Comment by kyleblythe** [comment]
Would it be possible to hide the row containing the dropdown, "showing x students" and "showing x of y items" when there are no GB items?

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/15052650/a7ee5a98-12cc-11e6-8cab-106cc3bf4134.png)
