### ISSUE TITLE
Category grade showing for Uncategorised item in student review mode

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2381]
The category grade is being shown for the Uncategorised column. Not sure when this crept it or if it was just overlooked.

![screen shot 2016-04-28 at 9 01 48 pm](https://cloud.githubusercontent.com/assets/129129/14883898/937d92f6-0d84-11e6-8944-98b94d6a4942.png)

**Comment by steveswinsburg** [comment]
@kyleblythe are you please able to verify this is an issue? I am in a feature branch and can't switch out just yet.

**Comment by kyleblythe** [comment]
Hey @steveswinsburg ,

I think we resolved this one a little while back. I'm not seeing this in master/sandbox1 when "No categories" is set.

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/15052620/85f0c76e-12cc-11e6-8be8-e38a11c0af36.png)
