### ISSUE TITLE
TA view - when TA does not have access to view final course grade, do not show green "Update" highlight for course grade and include a lock icon

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2471]
Currently, when a TA does not have the ability to view the final course grade, a dash appears in the Course Grade column. However, as they enter scores, the Course Grade cell will still highlight green, with the dash persisting.

To prevent confusion, the course grade cells should not flash green when the TA does not have the ability to view the final course grade. Additionally, lock icons should display in all course grade cells.

The popover message could say something along the lines of "You do not have viewing permissions for the course grade".

**Comment by kyleblythe** [comment]
Confirmed!

@jeffpasch , do we need a lock icon to display in the course grade column cells when the TA doesn't have access to view the course grade? The dash may be clear enough.

**Comment by steveswinsburg** [comment]
@kyleblythe should this one be closed?

**Comment by kyleblythe** [comment]
Ah, yep! This can be closed.
