### ISSUE TITLE
<br> appears in "Points" column for course grade override lightbox

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2473]
![image](https://cloud.githubusercontent.com/assets/11447474/15053032/96574e78-12ce-11e6-9f38-a200a0505641.png)

**Comment by steveswinsburg** [comment]
Ah I noticed this in a different area and fixed it. Will do the same.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/15216050/70845b96-1823-11e6-84fe-c650b8c63551.png)
