### ISSUE TITLE
Bootstrap/Morpheus anomalies 

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#2508]
Dropdowns don't show arrow and have text clipped, e.g.

<img width="420" alt="screen shot 2016-05-11 at 9 45 46 am" src="https://cloud.githubusercontent.com/assets/608337/15165943/58010414-175d-11e6-9590-85c7217ca141.png">

Also, some buttons go blank in their :active state, e.g. the Done button from the student summary modal goes blank upon mousedown.

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/15216064/83d8de7e-1823-11e6-9f64-bbcdbcbfa341.png)
