### ISSUE TITLE
Bug when saving a grade, the grade can disappear

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2531]
I think this may have something to do with the new saving mechanism (or the ONE_PASS_RENDER).

Sometimes the message gets stuck on 
`Saving...`
 and the disk icon or green tick appears, then the grade disappears.

In the log, newGradeAdjusted gets reported as null which means that the blank grade was sent to the backend service for saving, even though I type a number.

Hard to reproduce, may just be some code out of sync in my browser.

**Comment by payten** [comment]
On second sitting, I can't seem to replicate this one.  @steveswinsburg, have you seen it pop up again?

**Comment by steveswinsburg** [comment]
Not lately but will let you know if I do 👌

**Comment by steveswinsburg** [comment]
Ok this is now happening constantly on Firefox. Doesn't appear to be doing it in Chrome.
What happens is I enter a grade then press enter/click away, the grade disappears and the Saving.... stays there.

**Comment by payten** [comment]
Boo.. I'm not seeing that locally or on sandbox1 using Firefox on both OSX or Linux.  Let me guess.. are you on Windows? I'll see if I can track down a VM.

**Comment by steveswinsburg** [comment]
Windows? Wash your mouth out! I'm on OS X. I'll try a different computer
and report in.

**Comment by payten** [comment]
Ha! :)  Thanks

**Comment by steveswinsburg** [comment]
Haven't seen this for a while, may have been an local environment issue.

**Comment by kyleblythe** [comment]
Closing this one out.
