### ISSUE TITLE
Notify user when no longer connected to internet

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#2537]
Present an alert to the user letting them know that they are no longer online, similar to what Gmail and Google Docs does. Placement will be the same as mark's notification that favorites have been updated. e.g. http://www.screencast.com/t/SsybViZkJy

It's important for GB users to know that they are offline since they could enter many grades in the spreadsheet without them being saved.

**Comment by payten** [comment]
Related to #1581.

**Comment by payten** [comment]
@jeffpasch, what wording would you like for the message?  Google shows a lightning-bolt icon and message "Trying to connect." if I'm right.

I was thinking something along the lines of "Connection timeout. Changes cannot be saved while offline."? Icon?

**Comment by payten** [comment]
Ignoring the "pants".. this is what I have at the moment:

<img width="1262" alt="screen shot 2016-05-13 at 11 04 17 am" src="https://cloud.githubusercontent.com/assets/608337/15234956/9a95e5d0-18fa-11e6-825b-f530e2a30ef1.png">

**Comment by payten** [comment]
Btw, a nice way to test is via the Chrome developer console - you can disable the network by throttling it to zero:

<img width="1269" alt="screen shot 2016-05-13 at 11 24 05 am" src="https://cloud.githubusercontent.com/assets/608337/15235297/5d4cb4d0-18fd-11e6-8612-f90599851830.png">

**Comment by jeffpasch** [comment]
Yup, looks great. Thanks! 
And good to know, re: the console!

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/15372929/ecf7c3c4-1d10-11e6-8366-0ac4d8e8a842.png)
