### ISSUE TITLE
XML/XPath library clarification

### ISSUE THREAD

**Issue by cannonpalms** [sakaiproject/sakai#2549]
Currently we depend on all of the following for XML handling:

- simple-xml-2.6.jar
- jdom-1.0.jar
- jaxen-1.1-beta-10.jar
- dom4j-1.6.1.jar

Can someone clarify for me the need for all 4? Would narrowing to one XPath expression parser and one xml parser be beneficial? If this isn't possible, why?

**Comment by ottenhoff** [comment]
Hi Cannon,

Yes, one parser would absolutely be beneficial. Sakai is a kernel + tools project so tool developers have the freedom to choose their own dependencies. If you were interested in consolidating these parsers, the contribution would definitely be appreciated, reviewed, and merged if solid.

**Comment by cannonpalms** [comment]
I was looking at a potential consolidation job. I have some time this weekend so I'll see what can be done.

**Comment by cannonpalms** [comment]
After some initial investigation, I'd like to create a few utils within the kernel to handle XML operations. Seeing as though hibernate requires dom4j, I think dropping jaxen in favor of dom4j for XPath support would be the best option. Any qualms there?
