### ISSUE TITLE
inconsistent confirmation message for add gradebook item

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#2591]
Change styling of confirmation message for add gradebook item to be consistent with other parts of gradebook (and other Sakai tools):

Grades tab:
![2016-05-18_12-08-58](https://cloud.githubusercontent.com/assets/11447476/15366280/9692e76c-1cf1-11e6-89ff-5d276d3a1534.png)

Settings Tab:
![2016-05-18_12-07-54](https://cloud.githubusercontent.com/assets/11447476/15366294/a881215a-1cf1-11e6-8a1b-023eef62bbd5.png)

**Comment by kyleblythe** [comment]
We have proposed a tweak to the morpheus "okcolor" styling for the "messageSuccess" class to bring these confirmations in line with the info boxes/bootstrap in general.

JIRA [SAK-31272](https://jira.sakaiproject.org/browse/SAK-31272)
