### ISSUE TITLE
No validation error message presented when entering invalid item point value in "Add Gradebook Item" screen.

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2592]
To replicate:

1. Click "Add Gradebook Item"
2. Provide title
3. enter an invalid score in the point value field (e.g., "d").
4. Click "Create."

The item will not get created, yet no validation error message appears. Ideally, red text would appear beneath the point value, providing the integer info we supply for our error messages.

![image](https://cloud.githubusercontent.com/assets/11447474/15367021/1832f16a-1cf5-11e6-881a-dd9e5eebe69c.png)

This validation is missing in the "Edit item details" screen as well.

**Comment by kyleblythe** [comment]
Note: this error can also be reproduced in GB1

**Comment by steveswinsburg** [comment]
This appears to be fixed by other work. @kyleblythe, reckon you can validate?
![screen shot 2016-06-16 at 11 06 28 pm](https://cloud.githubusercontent.com/assets/129129/16117764/125a13d4-3417-11e6-8309-eed3b81677ef.png)

**Comment by kyleblythe** [comment]
Hmm...sorry @steveswinsburg , I'm still seeing this issue. SBX1 just rebuilt a couple of mins ago, and here's a recording of my attempt to create a new GB item with an invalid point value:

http://www.screencast.com/t/jZ7N2XP6aw2

Note - this is happening both with categories & weighting and without.

**Comment by steveswinsburg** [comment]
Ok I can see this now as well 👎

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16855365/0618b3a0-49e3-11e6-9756-6b4bea28051f.png)
