### ISSUE TITLE
Firefox - tabbing issue

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2593]
On Firefox, it is not possible to tab to dropdown menus in the column headers or in individual cells.

Behavior is working as expected in Chrome.

**Comment by payten** [comment]
Hi @kyleblythe.  I think this one is an O/S and browser configuration issue.

For OSX, Firefox honours the operating system keyboard configuration.  This can be changed via System Preferences > Keyboard and then by selecting All Controls option below:

<img width="780" alt="screen shot 2016-05-19 at 8 55 11 am" src="https://cloud.githubusercontent.com/assets/608337/15377532/bc2e23ca-1d9f-11e6-94c9-8a6fef000101.png">

For other operating systems, Firefox has an option which allows users to include/exclude links from the tab flow - this can be found by navigating to `about:config` and changing the `accessibility.tabfocus` entry to `7`.

It's certainly a little obscure, but I like to assume that keyboard savvy Firefox users would have this all sorted out.  It's worth noting that a Firefox user would not be able to navigate through the standard Sakai page and navigation links using the tab key without modifying their configuration.

**Comment by kyleblythe** [comment]
Ah, that's a really great point @payten . Thanks for the explanation - I had no idea! You learn something new every day :)

Ok, looks like this one's a non-issue. Closing it out. Thanks for taking a look!
