### ISSUE TITLE
Tomcat startup and app deployment

### ISSUE THREAD

**Issue by lq1800** [sakaiproject/sakai#2634]
I am trying to deploy master branch on latest Tomcat v8 (8.5.2) however I get NPE on every war deployment. This seems to originate in Tomcat (https://bz.apache.org/bugzilla/show_bug.cgi?id=59606). 
Same error comes on 11.x branch. 

Is there any fix for this problem ?

Exact stack trace is available [here](https://gist.github.com/lq1800/30fed72e5b65827fc7dbc95df7f9fc37)

I am using java version "1.8.0_05" on mac
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

**Comment by bjones86** [comment]
@lq1800 the Sakai community does not currently use GitHub as an issue tracking system or a help management system.

Please post your question to the Sakai developer's mailing list. You can find information on the various mailing lists and how to subscribe, etc @ https://confluence.sakaiproject.org/display/PMC/Sakai+email+lists
