### ISSUE TITLE
Student info columns display incorrectly when scrolling w/o categories enabled

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2647]
When scrolling in a GB without categories, the student info column header layer that appears is not consistent with the static column headers. It "jumps" downward, displaying the empty row header that appears when you have categories enabled:

![image](https://cloud.githubusercontent.com/assets/11447474/15540510/bf57901c-2255-11e6-9cdc-673a8dc51de3.png)

**Comment by payten** [comment]
Hi @kyleblythe, I'm having trouble replicating this one locally or on SBX1.  Have you seen it pop up again recently?

**Comment by kyleblythe** [comment]
Have not been able to reproduce. Closing this one out.
