### ISSUE TITLE
accesskeys

### ISSUE THREAD

**Issue by mclare** [sakaiproject/sakai#2653]
Great work on the accessibility.  Can I convince you to add a few accesskeys to the instructor view http://webaim.org/techniques/keyboard/accesskey ?

In a two item course with 100 students, it would be 400 tabs to move top to bottom students' row with the keyboard.

An accesskey or simple key command for jumping lines would be a big help!  BUT, searching might be an equally appealing solution.

The existing <accesskey> to jump to content makes an OK "jump to top" command, and it's easy to have too many commands, but maybe a jump to search accesskey or simple key command would also help?

**Comment by mclare** [comment]
Please label me: GradebookNG

Also, for your consideration, tools like Google Sheets capture ctrl + f and provide their search instead of the browser's.  Would this be a possible approach here?

**Comment by payten** [comment]
Great, sounds good.  Do you have any best practice advice for avoiding browser and screenreader conflicts?

**Comment by mclare** [comment]
How about <accesskey> + f (typically CTRL+ALT+f) - I don't think there's the possible of too much inference of that.

**Comment by steveswinsburg** [comment]
Just to confirm here, @mclare are we just after an access key to focus the search box so that students can be filtered?

**Comment by mclare** [comment]
You got it.  Seems like really useful affordance for those using keyboard nav over the current 2 tabs per row navigation to get to the correct record, or back to [the new!] filter.

**Comment by kyleblythe** [comment]
Confirmed!

**Comment by payten** [comment]
Hi @mclare, while testing accesskeys in GradebookNG I've noticed a few new `accesskey` attributes pop up in 11.x and it seems that some of those within a tool conflict with those defined in the outer portal e.g. `accesskey="c"` is used to jump to content in the portal and to also cancel a form in some tools.  The issue being we can't be sure a browser or screenreader will support duplicate accesskeys.

The `f` access key for this issue still seems to be unique!  However, I'm looking to add a few more accesskeys to GradebookNG to improve keyboard navigation and want to be sure I don't introduce any conflicts (or bump into any future portal accesskeys!).  Are there any policies or guidelines for adding accesskeys to Sakai tools? Or is it just best to double check against those in portal at the time and go from there? Thanks!

**Comment by mclare** [comment]
Hi @payten 

We certainly don't want conflicts!  What is GradebookNG using C for?  I'm not familiar with GradebookNG's use. 

Thanks

**Comment by payten** [comment]
GradebookNG doesn't use 'c'.  I was thinking of adding 'g' for the **g**rades table so you can easily jump to the table from the student **f**ilter and elsewhere.

Forums, Gradebook Classic and Podcasts all have instances of accesskey='c'.

**Comment by mclare** [comment]
Thanks,  I'll take a look when I have access to a full computer later today. 

Those tools shouldn't use c as it will be a conflict with "jump to continent". Here's the list of other global accesskeys in Sakai if it helps. https://sakai.screenstepslive.com/s/sakai_help/m/50750/l/463927-accessibility-information  G should be fine, but access keys have a history of unfortunate conflicts in edge cases (like maybe "find again").

**Comment by payten** [comment]
Ah true.  Perhaps `T` for table would be better? That doesn't seem to conflict with anything in the portal either.  Thanks for the help/doco!
