### ISSUE TITLE
Table caption

### ISSUE THREAD

**Issue by mclare** [sakaiproject/sakai#2655]
Please add a short table caption, with advice for instructors using alternative navigation like a keyboard http://webaim.org/techniques/tables/data#caption

_Very brief_ advice on how to access the context menus and perhaps about the search functionality would help.

In the past Sakai has had issues with overly verbose table summaries (Professional accessibility report on Sakai 2.9 https://confluence.sakaiproject.org/pages/viewpage.action?pageId=86769783 ).  Brevity is important.

Label: GradebookNG

**Comment by steveswinsburg** [comment]
Hey @mclare, if you suggest some text I can add this really easily.
Cheers.

**Comment by mclare** [comment]
Sure, once #2653 is resolved.

**Comment by steveswinsburg** [comment]
Hey @mclare, #2653 is in, do you have preferred text for this?

**Comment by mclare** [comment]
How's this:
"Rows of student names. Columns of gradebook items. Press enter key in a cell to add or edit a grade. Two tabs to move through each cell.  Filter list with accesskey F."

**Comment by jeffpasch** [comment]
It works with the voiceover on mac when I tab to it from the top: http://www.screencast.com/t/JCJ0E8t69TuJ

However, if I tab to it from the other direction (i.e., back into it with SHIFT+Tab ) I don’t get the text. Is that by design?

Also, fyi: ChromeVox seems to work well in general, but does not pick up that text for some reason.

**Comment by jeffpasch** [comment]
Ah, @payten pointed out you can get to that bit with ChromeVox by using ChromeVox + n + t

**Comment by jeffpasch** [comment]
@mclare I think this is good, but could you give it a look?

**Comment by mclare** [comment]
Tested with ChromeVox https://trunk-mysql.nightly.sakaiproject.org/.  Looks and sounds great.

**Comment by jeffpasch** [comment]
Thanks @mclare  This one is confirmed!
