### ISSUE TITLE
Student Drill Down should reflect category grouping of main gradebook

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#2671]
Currently this always displays as grouped by cat in the student drill down. This is Low priority. 
![2016-05-26_17-38-40](https://cloud.githubusercontent.com/assets/11447476/15591030/c60f5318-2368-11e6-8977-6362f603b57f.png)

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16121342/e2f27444-33b0-11e6-8e45-14663b0ba7f0.png)
