### ISSUE TITLE
Additional Export Options (to match those available in the "Course Grades" screen of GB1)

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2686]
When exporting the GB on the Import / Export screen, provide a text link below the "Download" button entitled "Advanced Options." Selecting this will open a lightbox window that allows users to customize what is included in the export, and select a .pdf export format. The defaults ("Student Name," Student ID," "Gradebook Item Scores" and "Gradebook Item Comments") will be selected and appear at the top. Additional options will be available below, and will include:

* Last Log Date
* Course Grade
* Calculated Course Grade
* Grade Override
* Total Points 

(Note re: Points - we may want to restrict the ability to export Total Points if categories & weighting are enabled)

When any of these options are selected/de-selected and modified from the default, text should be highlighted informing the user that this export can not be imported back into the Gradebook.

Mockup:

![image](https://cloud.githubusercontent.com/assets/11447474/15617908/165be2c2-2419-11e6-82bb-bc9550f48ba0.png)

EFFORT: **High**
PRIORITY: **High**

**Comment by payten** [comment]
Hi @steveswinsburg.  I've starting looking into this one and have the form ready to go and just looking into the PDF and Excel format generation.  The old Gradebook uses the `org.sakaiproject.jsf.spreadsheet.SpreadsheetUtil`.  Should I use the same? Or are there preferred/newer/nicer ways that I should be investigating?

**Comment by payten** [comment]
It seems like the JSF SpreadsheetUtil has some smarts for breaking a very wide table into multiple tables  so they render nicely as a PDF.  I'm also questioning the usefulness of the PDF export.  Notwithstanding it could be a bit of work make it render nicely if we have to reimplement the CSV-to-PDF transform.  @steveswinsburg, has this been done elsewhere in the app?

**Comment by steveswinsburg** [comment]
Yeah IIRC we discussed the PDF support on the call (maybe last week but sans Payten) and thought about dropping PDF in favour of Excel being able to export to PDF directly (I think it can on Windows now?).

For Excel I would be looking at https://poi.apache.org/spreadsheet/ directly, which is what the `SpreadsheetDataFileWriterXls` uses anyway 👍

**Comment by payten** [comment]
Great, thanks @steveswinsburg.  I'll omit PDF and look to add Excel.  That makes good sense to me!

**Comment by payten** [comment]
Hi @kyleblythe.  The advanced options are ready for testing now.  I haven't implemented PDF or XLS export though... maybe they're not required?

**Comment by kyleblythe** [comment]
This is looking really great, @payten! Thanks for the work on this. So, re: the PDF export option...I'm inclined to agree with your and @steveswinsburg 's opinions. That said, PDF export **is** an option in GB1, so I'm not sure how we feel about leaving an existing option out of GBNG. What do you think, @jeffpasch ?

So a few issues/add'l notes I've found with the advanced export:

- Currently, clicking the "Advanced options" link opens a hidden collapsed menu **above**. I get why this is the case, as it positions the "Download" button below. It seems a little unintuitive, however (especially because you then have to click "Advanced options" again to close the menu, and it's located below the menu you're trying to close).

![image](https://cloud.githubusercontent.com/assets/11447474/15933569/3b702f04-2e2e-11e6-9a46-c932fac7117e.png)

I'm wondering if we want to either have these advanced options open in a lightbox window with their own "Download" button at the bottom of the window, or if we want to disable the default "Download" button when "Advanced options" is selected, and instead have a separate "Download" button become visible/active within the accordion menu. That way, the accordion menu could open **below** the link, which seems more intuitive.

- Right now, regardless of whether any "Advanced options" are selected, the whole "Export" process remains visible on **all** screens in the Import/Export process:

![image](https://cloud.githubusercontent.com/assets/11447474/15933467/dacb6146-2e2d-11e6-90aa-18200a903e3f.png)

This should be hidden once you click the "Continue" button on the first screen to import a spreadsheet.

- Lastly, is there a way to have the import recognize when there are any columns from the "Advanced options" export? Ideally, I think we'd like to actively prevent the import process from taking place if any columns outside of the standard export are in place.

**Comment by jeffpasch** [comment]
Yup, I think we could leave out the export to PDF, since it can be done in Excel. And we can leave out the XLS option as well. 
We can discuss the "advanced options" stuff more today.

**Comment by payten** [comment]
Improvements: 
- [ ] rename "Advanced Options" to "Custom Export"
- [ ] open in a modal with a new download button in the modal
- [ ] button in modal is labelled "Download Custom Export"
- [ ]  original button downloads normal export and label "Export Gradebook"
- can we detect when a custom export has been imported?? and throw an error?
 - [ ] YES: by prefixing all custom export columns with a `#`

Fixes:
- [ ] Export shouldn't be showing on every step of the import wizard.. fail.

**Comment by kyleblythe** [comment]
Very nice, @payten - this is working great :)

So, one quick thing. The custom export should probably, by default, have only the options that are in the regular export checked by default. Currently, "Course grade" is selected by default, but that should probably be an opt-in selection like the other custom export options that aren't in the standard export.

Also, it looks like the "Course Grade" option doesn't have the `#` prefix in place:

![image](https://cloud.githubusercontent.com/assets/11447474/16129549/1d3c292a-33d3-11e6-8a1d-c34a3ae24888.png)

**Comment by kyleblythe** [comment]
Confirmed - nice!

Export defaults:
![image](https://cloud.githubusercontent.com/assets/11447474/16312590/76497a3e-3943-11e6-88da-0600352be1b3.png)

"#" prefix:
![image](https://cloud.githubusercontent.com/assets/11447474/16312619/989f9032-3943-11e6-8c97-2438625fbc10.png)
