### ISSUE TITLE
If TA has access to a 'group' and 'all', group filter is not shown.

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2698]
If a TA is granted access to a specific group (in a category) and then all 'sections and groups', the code sees only one group and renders just that group title. However all members are listed.

**The settings:**
![screen shot 2016-05-31 at 10 26 30 pm](https://cloud.githubusercontent.com/assets/129129/15674176/c19ab240-277e-11e6-83ea-d5b5cda7d1be.png)

**The view:**
![screen shot 2016-05-31 at 10 25 21 pm](https://cloud.githubusercontent.com/assets/129129/15674195/d47f597e-277e-11e6-98ab-916ad6eaf4ef.png)

**Comment by steveswinsburg** [comment]
Auto closed? Annoying. Reopened for verification.

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/15755231/e258e488-28c9-11e6-8989-4a781fe568e7.png)
