### ISSUE TITLE
If imported spreadsheet creates a new item, and title/point values are modified, original values are used instead

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2717]
In import/export, if a new item is detected you are taken to the create screen.

The title and point values are prepopulated. However if they are edited, the next screen shows the original values. But when the assignment is actually created, it uses the edited value.

**Comment by steveswinsburg** [comment]
@kyleblythe what workflow would you like here? For discussion.

**Comment by kyleblythe** [comment]
This is a good catch, Steve! The confirmation screen should definitely show the edited title/point value.

**Comment by steveswinsburg** [comment]
This will be done as part of the work in #1356

**Comment by jeffpasch** [comment]
Yup! Looks like this is now working correctly.
