### ISSUE TITLE
If items are detected but nothing is selected, you get a blank confirmation screen

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2718]
See screenshot

![screen shot 2016-06-02 at 10 36 35 pm](https://cloud.githubusercontent.com/assets/129129/15744950/845e8e66-2912-11e6-9dbd-635936ed72d5.png)

**Comment by kyleblythe** [comment]
We should probably disable the "Continue" button until at least one checkbox is selected.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16490564/38c937b6-3ea8-11e6-8bce-b70284f41ce5.png)
