### ISSUE TITLE
During import, if new gb item is being added but it already exists, the exception is not caught

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2719]
Caused by: org.sakaiproject.service.gradebook.shared.ConflictingAssignmentNameException: You cannot save multiple assignments in a gradebook with the same name

**Comment by steveswinsburg** [comment]
SHould add this, as per the main add/edit item panel:
````
try {
						assignmentId = AddOrEditGradeItemPanel.this.businessService.addAssignment(assignment);
					} catch (final AssignmentHasIllegalPointsException e) {
						error(new ResourceModel("error.addgradeitem.points").getObject());
						success = false;
					} catch (final ConflictingAssignmentNameException e) {
						error(new ResourceModel("error.addgradeitem.title").getObject());
						success = false;
					} catch (final ConflictingExternalIdException e) {
						error(new ResourceModel("error.addgradeitem.exception").getObject());
						success = false;
					} catch (final Exception e) {
						error(new ResourceModel("error.addgradeitem.exception").getObject());
						success = false;
					}
````

**Comment by steveswinsburg** [comment]
This is done but it is part of #1356

**Comment by jeffpasch** [comment]
I imported two new items. I then changed the name of one of them to be the same as an existing item. I'm able to continue through the workflow until I hit Finish on this page, which is where I get the exception:  
![2016-08-04_02-37-17](https://cloud.githubusercontent.com/assets/11447476/17392720/2a088050-59ed-11e6-9776-13d746e7eab7.png)

So, I guess I could import a whole bunch of items and one of them has the same name as something already imported, I'll get that error but I won't know which one has the problem. Would it be possible to serve that error at the point at which the users hits next in the workflow?
![2016-08-04_02-50-26](https://cloud.githubusercontent.com/assets/11447476/17392882/44ed629a-59ee-11e6-8ab1-e18b19f12c7f.png)

I did notice something else here. If I import two new items and I give them the same name, the system will allow me to hit finish without an error:
![2016-08-04_02-58-45](https://cloud.githubusercontent.com/assets/11447476/17393102/71870ff8-59ef-11e6-978a-75eac4f9b1dd.png)

It looks like only one of the items gets imported though. I've also tried making them different point, and still only one of them will get imported. So maybe we want another check at the end of the process to see if we have the same name appearing twice in this final list before import.

**Comment by steveswinsburg** [comment]
The title check is only done when the item is actually created, as it uses the GbService. It could certainly be changed to be earlier and check if the item exists with that name, before creating.

The second is because it ignores dupes right at the beginning. I agree and think that it should chuck the file out at that point instead of silently ignoring.

**Comment by jeffpasch** [comment]
Works as designed. Will create a separate issue to enhance this. So...confirmed!
