### ISSUE TITLE
"percentage" mode - category subtotal calc errors

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2781]
The category subtotal (and possibly course grade? my math skills are not up to the challenge of figuring that out) don't seem to be reflected correctly when in "Percentage" mode.

Note: for the following, I'm using categories & weighting.

![image](https://cloud.githubusercontent.com/assets/11447474/15904527/5de7cbaa-2d7f-11e6-8291-1eea61c6e452.png)

In the image above, you can see that there are three items with scores and different relative item weights (one worth 300, one worth 100, and one worth 200).

For Julio tester, a cat subtotal score of 31.67% is reported. However, they should have a 53.33%. Maybe I'm mistaken, but I think the calculation for this should be:

( (.4 * 300) + (1.0 * 100) + (.5 * 200) ) / (300 + 100 + 200) = .5333

Likewise, Taifa tester is reporting a cat subtotal score of 15%. This should be 30%, with the calculation for this being:

( (0 * 300) + (.75 * 200) ) / (300 + 200) = .3

**Comment by steveswinsburg** [comment]
Category subtotal doesn't take into account percentages. This needs to be added. Likewise for letter grades, otherwise you get this error:
````
aused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:175)
	... 61 more
Caused by: java.lang.NumberFormatException: For input string: "A-"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.apache.commons.lang.math.NumberUtils.createDouble(NumberUtils.java:698)
	at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.calculateCategoryScore(GradebookServiceHibernateImpl.java:3041)
````

**Comment by steveswinsburg** [comment]
Maths above looks correct. I think the backend is using the percentage numbers when doing it though, which would cause the discrepancy, it should use the actual underlying point values.

**Comment by steveswinsburg** [comment]
In terms of the calculations, if I add the three assignments above, then it correctly reports 53.33%. However If I add the fourth (homework 1) and don't add a score, then it drops to 31.67%, which is what you are seeing. So the calculations are correct but the backend is reporting a score for the student for that assignments (probably 0) when in percentage mode. When it points mode it is correct.

**Comment by steveswinsburg** [comment]
I've had a look in the backend. It is adding up percentages rather than the actual score:

When in points mode:
````
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: 100.0
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: 100.0
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: 120.0
````

When it percentage mode:
````
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: 100.0
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: 50.0
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: 40.0
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: null
grademap for studentUuid: d19589e6-17de-481f-b25d-407fa2c7ccec: null
````

**Comment by steveswinsburg** [comment]
Ok this is done and in PR.

**Note** I havent fully tested letter grade support as my environment wasn't support it correctly, and I am about to board for a flight. But it shouldn't explode anymore.

**Comment by payten** [comment]
Hm... it auto-closed.. gosh. *reopens issue*

**Comment by payten** [comment]
Wha?... auto-closed again...

**Comment by kyleblythe** [comment]
Confirmed! The cat subtotal scores are reflecting accurately:

![image](https://cloud.githubusercontent.com/assets/11447474/16268816/d6ca9e4c-385d-11e6-9a27-d223e08921bd.png)

@steveswinsburg , can you elaborate re: the letter grade support? In sbx1, although "Letter Grade" shows up as a selectable option in GB1, I can't seem to actually enable it, regardless of whether GBNG is enabled in the site or not.

**Comment by steveswinsburg** [comment]
@kyleblythe Yeah that was the problem I was having as well on latest master. Maybe its broken again in GB Classic? I thought I had it working at one point. (I didnt touch it, I swear).
