### ISSUE TITLE
"percentage" mode - issue with way scores are reported from external tools

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2782]
1. With percentage mode enabled, create a GB item with a relative item weight of 200.
2. Create a GB item with a point value of 200 and associate with the existing GB item.
3. Provide student a score out of 200 (e.g., 100).

Score is accurately reflected in GB cell as a 50%.

Now, change the score in the GB to a 60%. This should get reflected back in Assignments as a 120/200 pts. However, the Assignments tool will now report a score of 60/200 pts, as it treated the GB percentage as a point value.

**Comment by steveswinsburg** [comment]
I think this is, at least in part, due to this https://jira.sakaiproject.org/browse/SAK-31049

**Comment by kyleblythe** [comment]
This is an existing GB issue, dating back to GB1 & 2.9. Closing this one out.
