### ISSUE TITLE
If double-clicking "Add Gradebook item," possible for multiple lightboxes to open

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2791]
If double-clicking the "Add Gradebook Item" lightbox (that is, clicking "Add" again before the first lightbox appears), then two lightboxes will open.

Not immediately noticeable, unless you move the first lightbox out of the way. May want to prevent the button from being clicked more than once.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/11447474/15936469/254022d8-2e39-11e6-8e87-0766b33fa382.png)

**Comment by kyleblythe** [comment]
Confirmed!

**Comment by payten** [comment]
In large grade books, the button is only disabled for moment before re-enabling (add/edit takes longer than 2 seconds).

**Comment by payten** [comment]
Reopened as the button on the Add/Edit form becomes re-enabled before the page unloads/redirects. This is easier to replicate in larger gradebooks.  The PR #2915 adds some JS to handle this case.

**Comment by kyleblythe** [comment]
Confirmed.

http://www.screencast.com/t/7JYAM75Kee
