### ISSUE TITLE
Detect and ignore custom export columns in the Gradebook import

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#2796]
Custom export columns will be prefixed with `#` to allow for filtering in the import process.

**Comment by steveswinsburg** [comment]
What was the behaviour we wanted with the column prefixed with the # again?

**Comment by jeffpasch** [comment]
I'm getting this error message:
![image](https://cloud.githubusercontent.com/assets/11447476/17226149/f1835ed8-54d5-11e6-8060-98f1a4f89e8e.png)

Is that the expected behavior, or should it be allowing the import to happen and just ignore those columns?

**Comment by steveswinsburg** [comment]
Noticed that the same message is returned if the file could not be read, or the file was empty so I will split that out to make it clearer. Will need to test with some additional files.

**Comment by steveswinsburg** [comment]
Also, the regex for # needs to allow any characters afterwards because `#assignment1 [100]` doesn't work.

**Comment by steveswinsburg** [comment]
The error messages are now more granular. Also regex has been fixed to allow any chars after the #. Addressed in #3107.

**Comment by jeffpasch** [comment]
Tested with '#assignment1 [100]' and looks too be working. Noice. :metal:
Closing this one out.
