### ISSUE TITLE
'All changes saved' appears even if there are no gradebook items

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2806]
In a new site, the 'All changes saved' appears even if there are no items. May be missing a visible state check.
![screen shot 2016-06-12 at 9 58 03 pm](https://cloud.githubusercontent.com/assets/129129/15991017/e1d7f180-30e8-11e6-9ddb-8027d04cd73f.png)

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16268547/dca3db7c-385c-11e6-8e3e-945907724dc2.png)
