### ISSUE TITLE
Percentage Mode: Grade Summary needs to display percentage-centric values

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#2849]

**Comment by kyleblythe** [comment]
Hi @payten ,

Looks good! One quick thing - currently, when there's a null value for a student, the "%" symbol still displays.

![image](https://cloud.githubusercontent.com/assets/11447474/16268427/6f0ad2aa-385c-11e6-9b85-5c0741afc377.png)

Can we set the score to display as empty when there's a null value?

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16490216/ad3497b4-3ea6-11e6-9e42-719c61bfb95e.png)
