### ISSUE TITLE
add ARIA attribute to categories in Grades table

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#2914]
add ARIA attribute to categories in Grades table for screenreader to recognize them as categories

![image](https://cloud.githubusercontent.com/assets/11447476/16322689/f8c80640-3972-11e6-9ab7-12676a391719.png)

**Comment by kyleblythe** [comment]
Hi @payten - this looks good!

![image](https://cloud.githubusercontent.com/assets/11447474/16490065/25777490-3ea6-11e6-937e-ccd4b127f34c.png)

Quick question. The tooltip for the category header seems to only show the category name...will screenreaders also pick up the category's percentage weighting? If not, we might want to include that in the tooltip as well.

**Comment by payten** [comment]
Hm.. yeah.  It would be good to include the weight, so the label might read "Category: cat1, Weight: 50%" - does that seem ok?

**Comment by kyleblythe** [comment]
Confirmed - looks good!

![image](https://cloud.githubusercontent.com/assets/11447474/16597310/366c5e04-42c6-11e6-8b06-c58196e5c582.png)
