### ISSUE TITLE
Category subtotal not displaying by default

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2940]
For instructors/TAs, the category subtotal is not populating upon initial load/refresh of the page. It does, however, display once a value gets changed and the subtotal gets updated.

![image](https://cloud.githubusercontent.com/assets/11447474/16395177/a6dd53e6-3c86-11e6-9c22-f5c682e49b21.png)

This might be related to #2935 ?

**Comment by payten** [comment]
This looks like it was introduced with the percentage grading changes 🐛  PR submitted!

**Comment by kyleblythe** [comment]
Back in action! Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16490025/f8125d30-3ea5-11e6-8b02-e96a5c4de591.png)
