### ISSUE TITLE
Allow GradebookNG to use its built-in letter grading schema.

### ISSUE THREAD

**Issue by fgeraci** [sakaiproject/sakai#2954]
GradebookNG does not have an option to save grades as letters. This has to be added under:
Settings > Grade Entry

This is partly because the gradebook service is filtering grades-listing request from gradebook tools which the letter-grading option on in GradebookServiceHibernateImpl doesn't check for this.

[PR](https://github.com/sakaiproject/sakai/pull/2955)

**Comment by kyleblythe** [comment]
Hi @fgeraci ,

As per our convo in #2955 , closing this for now, as this requirement's captured in @jonespm 's issue #2730 .

Thanks!
