### ISSUE TITLE
Update secondary button styling in GB to match Sakai standards

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#2979]
Update the styling of secondary buttons (e.g., "Cancel") in the interface to retain the same blue used throughout Sakai for primary/secondary buttons.

Exceptions to this rule, however,  could be things like the "Group by Category" and "Show/Hide Items" buttons in the spreadsheet view. Precedence for this kind of exception can be found with the "Options" buttons in Overview:

![image](https://cloud.githubusercontent.com/assets/11447474/16531493/b52a8efc-3f9a-11e6-9d3f-771336b809df.png)

**Comment by steveswinsburg** [comment]
Hey @payten are you ok to manage this one? 🚙

**Comment by payten** [comment]
@kyleblythe, do you think "Add Gradebook Item" on the main Grades page should be grey too?  I'll make the spreadsheet toolbar buttons grey, but not sure about the "Add" button or "Export Gradebook" on the "Import / Export" tab.

**Comment by payten** [comment]
I have to admit, I'm too sure about these changes.  After updating the buttons it really feels like a step backwards in usability.  I have a PR ready to go and I'll deliver it asap given the 'priority' status.  But I feel like we should revisit this when given the chance.

**Comment by kyleblythe** [comment]
Hi @payten ,

This looks good. Thanks for the update! And yep, I like that "Add Gradebook" item remains an active button color, and think that the grey buttons work in the spreadsheet interface.

Agreed that this is a less-than-ideal solution in terms of UX. Looking forward to adding the secondary button classes throughout Sakai for a future point release!

![image](https://cloud.githubusercontent.com/assets/11447474/16597251/e42a092a-42c5-11e6-8753-194c915077d5.png)

Confirmed (and thanks again!)
