### ISSUE TITLE
TA unable to see Uncategorised item if 'all categories' selected

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#2986]
As reported in #2956.

**Comment by steveswinsburg** [comment]
Investigation: TA can see the columns but not the data in the uncategorised columns

**Comment by steveswinsburg** [comment]
The PR that @payten is kindly about to merge 🍰 should fix this issue. The uncategorised items were being skipped when permissions were present for a TA 😵 😿

**Comment by steveswinsburg** [comment]
Reopened due to PR merge auto close.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/16668652/e90537f8-445f-11e6-9c5c-a13c7646cd6d.png)
