### ISSUE TITLE
"EC" in-cell icon doesn't appear for items originating from other tools

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3006]
Currently, if a score above the maximum points allotted is given within an external tool (e.g., Assignments, T&Q), there's no in-cell "+" icon for these scores in GB.

This is because we only allow one icon in-cell, and external tools use the "lock" icon.

Looking to a future version, perhaps we should have a new, combo icon to represent this scenario. A lock with a "+" within?

**Comment by jeffpasch** [comment]
Pushing this one off until we make table changes.

**Comment by kyleblythe** [comment]
Confirmed. Nice!

![image](https://cloud.githubusercontent.com/assets/11447474/18888622/19898012-84c7-11e6-83ab-576b3976c9b9.png)
