### ISSUE TITLE
Student View / Grade Summary Screen - assignments appear even when released to other groups

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3036]
Currently, if an item originating from assignments is released to a specific group, the assignment title will show up in the grade summary & student views for every student, regardless of group affiliation.

**Comment by steveswinsburg** [comment]
At first glance it doesn't actually look like the gradebook service is doing any filtering on groups at all. The check is that if the user is a student just get them all except the unreleased ones.

**Comment by steveswinsburg** [comment]
Lol why does github automatically close these  _sometimes_?!

**Comment by kyleblythe** [comment]
Confirmed.

Assignment released to section 002 group:
![image](https://cloud.githubusercontent.com/assets/11447474/16952735/77385046-4d98-11e6-904a-97e01084a165.png)

Resulting GB view for member of section 001 group:
![image](https://cloud.githubusercontent.com/assets/11447474/16952749/883344b4-4d98-11e6-9b1d-f38a05553095.png)
