### ISSUE TITLE
Authentication - Question

### ISSUE THREAD

**Issue by deinok** [sakaiproject/sakai#3041]
Hi, I'm developing an Android App.
My question is:
Is there any way to login through the API?

**Comment by steveswinsburg** [comment]
Hi, Yes you can login via  REST service.
{code}
URL : {SAKAI_PORTAL_URL}/direct/session/new
Parameters: _username and  _password
{code}

There is also an OAuth capability. But you are best asking on the Sakai Developer list sakai-dev@apereo.org

Visit groups.apereo.org to sign up or post.
