### ISSUE TITLE
Custom Export window remains open after file is downloaded

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#3049]
On Firefox, if you choose a custom export, the window remains open even after you download the file. It's not immediately apparent that the file has already downloaded. Perhaps the window should close?

If it is opened again, should the checkboxes that were checked previously be checked again? This will complicate things.

**Comment by steveswinsburg** [comment]
Discussed 26/8/2016:
Close the window when file is downloaded
On reopening, just use defaults.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg and @payten ,

The window is closing as expected. However, when re-opening, it looks like the window is retaining its former state (see the following screencast):

http://www.screencast.com/t/vf7gv1jh1fe

I have to say, though...maybe that isn't a bad thing? Something we can revisit during our call.
