### ISSUE TITLE
Do not allow gradebook item names to start with * or # when creating a new item in the UI

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#3055]
Import/Export now reserves these characters.

Provide a warning when user tries to add an * or # at the beginning of normal item creation via the GB interface, notifying them that this format is reserved exclusively for importing GB comment columns (Note: possibly even in the gradebook service?).

This forms part of #1356

**Comment by steveswinsburg** [comment]
Also need to disallow `[` and `]` in the name as that will muck up the import

**Comment by jeffpasch** [comment]
Comfirmed
![image](https://cloud.githubusercontent.com/assets/11447476/17230079/75270e1c-54e8-11e6-842f-34b811ea956c.png)

**Comment by jeffpasch** [comment]
Working as expected. @jeffpasch Will create new issue to account for [ and ] in the name.
