### ISSUE TITLE
error message background hangs around in import workflow

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#3100]
In the following site: https://sandboxclasses1.home.nyu.edu/portal/site/5017eb20-9ef6-4a67-b303-fa4851f9b63e/tool/d08adb01-b6fd-4eae-ba55-bf50f93d6bd7 
1. Upload the attached  - gradebook_export-jwp1.csv, which has an error in it (a bunch of repeated square brackets)  https://dl.dropboxusercontent.com/u/12079741/gradebook_export-jwp1.csv
2. You'll get the "The file you uploaded was not formatted correctly" error at the top of the screen.
3. Upload the attached -gradebook_export-jwp2, which should be all good.  https://dl.dropboxusercontent.com/u/12079741/gradebook_export-jwp2.csv
 
4. As you move to the next step in the workflow, the background of the error message hangs around: 
![image](https://cloud.githubusercontent.com/assets/11447476/17231308/26e0df2e-54ef-11e6-9c83-e0737b8eb22e.png)

**Comment by steveswinsburg** [comment]
This will be resolved via #3107.

**Comment by jeffpasch** [comment]
HI @payten I'm still getting this issue, with the steps repeated above. http://www.screencast.com/t/n9hWKQXqy

**Comment by payten** [comment]
Hm.. it looks like the pull request I thought had this fix didn't, but the pull request I just merged should!  I daresay the next build should pick those changes up and save the day 🌈  I'll double check in the A.M.

**Comment by jeffpasch** [comment]
confirmed.
