### ISSUE TITLE
In FF, Cannot Create GBNG Items under certain conditions

### ISSUE THREAD

**Issue by master-bob** [sakaiproject/sakai#3116]
Within Firefox 47:

1. Go to the default unconfigured Gradebook tool 
2. Click on the "Settings" tab
3. Click on the "Grades" tab
4. Attempt to "Add Gradebook Item"
  - Fill out Title, Points, Due Date, and both (Release item to students / Include item in course grade) check boxes checked.
5. Receive an error
  - In Master:
  - - Title required and must be unique. Points required and must be a number greater than zero.
  - In 11.x / 11.0:
  -  - Points required and must be a number greater than zero.

This behavior is present if going to any tab (not just "Settings").

**Comment by payten** [comment]
I can confirm this is an issue in both Master and 11.x, but only occurs in Firefox and not Chrome.

@steveswinsburg, any idea why the wicket form validation would be different for different browsers? It seems the `title` TextField required IValidationError error is being raised, even if the input has a value.  I'll delve deeper, but let me know if you've seen this happen before.

**Comment by payten** [comment]
@steveswinsburg, the issue may relate to this https://issues.apache.org/jira/browse/WICKET-3404, whereby the ModalWindow outputs a form element by default so any form elements within the modal content become invalid and subsequently stripped by Firefox.  Chrome/IE/Safari seem to be a little more lenient on the invalid HTML.

**Comment by steveswinsburg** [comment]
Oh that's a bit yucky. Maybe we just move the validation into the onValidate/onSubmit instead, and do it ourselves? There are other parts where we do that.

**Comment by payten** [comment]
Hm... I gave that a go and wasn't able to get the inputs to sync back to the form model 😕 

Also,  this doesn't seem to be limited to the Add Grade Item form.  Set Score for Ungraded hangs on Firefox if submitted following the steps above.

**Comment by payten** [comment]
Hm.. tinkering after a :beer:... in Firefox, when the form works, the POST results in a 200 OK.  When the form fails, the POST results in a 302 Redirect.  Could this be related to render strategy?

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/17592552/bf526fae-5fb0-11e6-97f2-deeda0e1334a.png)
