### ISSUE TITLE
Throw Exception Error When User Tries to Import Comment Column Without Corresponding Item Column

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#3127]
From #1356 item 3.
If the user attempts to import a comment column (e.g., “* Week 3 Homework”) and there is not a matching item column title (either in the uploaded spreadsheet file or already in the Gradebook), provide an error message stating “[x] comment column does not have a corresponding Gradebook item.”

Note: Since this throws an exception, to capture the offending column I need to modify the exception and add the field name. This is straightforward but I thought I would get the current message in and see how it looks first. Let me know.

**Comment by jeffpasch** [comment]
Hi Steve. When I upload a .csv file with an orphan comment, this is what I see: 
![2016-08-04_02-09-57](https://cloud.githubusercontent.com/assets/11447476/17392267/3cd5e6d0-59ea-11e6-8dbe-260e463324c5.png)

So, no error message. 

If I then select only that blank item, I go to the next screen it shows nothing to import:
![2016-08-04_02-07-56](https://cloud.githubusercontent.com/assets/11447476/17392305/68d1a81e-59ea-11e6-8339-05b4b62ba0e3.png)

I click Finish, and nothing gets up loaded.

However, if I select both the blank item AND another item that has changed, I get to this screen:
![2016-08-04_02-20-10](https://cloud.githubusercontent.com/assets/11447476/17392323/8a9bb1a6-59ea-11e6-9f32-294e100546ce.png)

If I then click Finish at that point, I get this error:
![2016-08-04_02-24-52](https://cloud.githubusercontent.com/assets/11447476/17392358/df7bb96e-59ea-11e6-815a-0a1f0d4bf759.png)

I used this site: https://sandboxclasses1.home.nyu.edu/portal/site/5017eb20-9ef6-4a67-b303-fa4851f9b63e

With this file: https://dl.dropboxusercontent.com/u/12079741/crap-gradebook_export-5017eb20-9ef6-4a67-b303-fa4851f9b63e.csv

**Comment by jeffpasch** [comment]
Looks like the NYU build hadn't completed successfully when I checked this before. This is confirmed: http://www.screencast.com/t/6ArJ8FWT4I
