### ISSUE TITLE
Error importing  *.csv file in gradebook

### ISSUE THREAD

**Issue by mpldev** [sakaiproject/sakai#3150]
Version of Sakai 11.0

[error importing *.csv file to gradebook.txt](https://github.com/sakaiproject/sakai/files/404791/error.importing.csv.file.to.gradebook.txt)

**Comment by steveswinsburg** [comment]
````
Caused by: java.lang.IllegalArgumentException: null parameter passed to getAssignmentScoreString
	at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getAssignmentScoreString(GradebookServiceHibernateImpl.java:2366)
````

Can you attach the csv? 
Also, is this on master on 11.0?

**Comment by mpldev** [comment]
on 11.0, this is the csv file

[csv-file.txt](https://github.com/sakaiproject/sakai/files/406909/csv-file.txt)

**Comment by steveswinsburg** [comment]
Student ID and Student Name can't be translated. I'll update the instructions and the template so they are more 'fixed'. I'll also ensure this error is caught. Thanks.

**Comment by steveswinsburg** [comment]
On master I get:
`09-Aug-2016 22:08:02.007 ERROR [http-nio-8080-exec-114] org.sakaiproject.gradebookng.business.util.ImportGradesHelper.parseCsv Error reading imported file: class org.sakaiproject.gradebookng.business.exception.GbImportExportInvalidColumnException : Invalid column header, skipping: Auto-y-Coevaluacion [10]
`
which gives:
`The file you uploaded was not recognised as a CSV or Excel file.`

This isn't quite right so I will correct the exception handling to return a better error 👍

**Comment by steveswinsburg** [comment]
Instructions are ok as they indicate it should be as per the template. I have added some fixes to #3165.

**Comment by jeffpasch** [comment]
Hey @steveswinsburg. So now, when I try to update that csv file kyle attached above (with spanish translations for the first two column headers), I'm seeing a nicer error:

![image](https://cloud.githubusercontent.com/assets/11447476/17761889/1908a734-64d9-11e6-82d2-2bc22e0f06a2.png)
  
I also noticed that even when I change the language to spanish in Preferences, the exported CSV now has english column headers.

If the above all the expected outcome? If so, this one can be closed.

**Comment by jeffpasch** [comment]
confirmed. No longer producing stack trace. Giving nicer error.

**Comment by ottenhoff** [comment]
On nightly2 master, I go to a course, Download the CSV, then try to Import the same CSV and receive:

The file you uploaded was not recognised as a CSV or Excel file.
