### ISSUE TITLE
Detect when Gradebook Item already exists or was previously entered during import process

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#3152]
This builds on https://github.com/sakaiproject/sakai/issues/2719

In the new item creation workflow during the import process, check to see if (1) an item with the same name already exists in the gradebook and (2) if the same name was used for a previous new item in the current import. Therefore, perform this check when the user hits the Next or Back buttons in the workflow: 

![2016-08-08_01-11-21](https://cloud.githubusercontent.com/assets/11447476/17469954/33c5f606-5d06-11e6-9d59-2cb1cfe4b7ab.png)
 
Btw, I also noticed that Item names are case sensitive, so it's possible to have two items with the same name but with different cases. This looks to be the case in GB Classic as well. However, I was able to cause a stack trace when using the same name but just a different in capitalization in the same import. Creating another issue for that.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/18365446/bbedb134-75e0-11e6-9dc0-bdbdfb25ea03.png)
