### ISSUE TITLE
Theme picker for site not working

### ISSUE THREAD

**Issue by luklapp** [sakaiproject/sakai#3173]
After adding a new theme, the dropdown in site settings still only shows "*default*". 

I followed the instructions here: https://github.com/sakaiproject/sakai/blob/master/reference/library/src/morpheus-master/compile-skin.md

In the skin folder, there are two folders now: morpheus-default and morpheus-test.

Settings (sakai.properties):
skin.default=default
skin.repo=library/skin
disable.course.site.skin.selection=false
portal.templates=morpheus

![snip20160810_3](https://cloud.githubusercontent.com/assets/6569846/17553490/56e09310-5f06-11e6-8633-5eb6944840fb.png)

**Comment by steveswinsburg** [comment]
Hi, We currently only use github for tracking issues with GradebookNG. Could you file this over at http://jira.sakaiproject.org? This will hopefully be rectified soon. Unfortunately you will need to create an account on that site to log the bug.

**Comment by luklapp** [comment]
Hey @steveswinsburg, thanks for your reply. I created a ticket here:
https://jira.sakaiproject.org/browse/SAK-31666
