### ISSUE TITLE
Checkbox still appears checked, showing an item is included in grade calculations, even if it is currently "uncategorized"

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3179]
To replicate:

1. Have a GB set up without Categories & Weighting.
2. Create multiple items and have them included in grade calculations.
3. Turn on Categories & Weighting.
4. Edit one item and add to a category.
5. Edit any other item. The checkbox for "Include in Grade Calculations" remains checked, but the box is greyed out and not clickable.

![image](https://cloud.githubusercontent.com/assets/11447474/17591550/ab0f1f82-5fac-11e6-8155-2b071a01ac99.png)

The item is _not_ included in grade calculations, as the greying-out reflects, but the checkbox should not be checked.

**Comment by kyleblythe** [comment]
And, on a related note, items that are currently "uncategorized" are not showing the "eye-slash" icon denoting that these items, since they do not belong to a category, should not be included in grade calculations.

![image](https://cloud.githubusercontent.com/assets/11447474/17591736/646395da-5fad-11e6-98a8-abfebf0ca373.png)

Note that the actual recording of scores is working as expected, so this is purely cosmetic.

**Comment by steveswinsburg** [comment]
Discussed 12/8/2016:
When making this change in settings, go through and update all of the uncategorised items to remove the 'include in course grade' setting.

If an instructor changes their mind they will have to set the category and checkbox for an item, but that is ok.

**Comment by steveswinsburg** [comment]
PR #3204 fixes both issues, implemented as per earlier comment.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/17788589/6cece3b4-655c-11e6-8aa0-b665368ca8ec.png)
