### ISSUE TITLE
If you only have an extra credit item in a category w/ a score attached, the category subtotal should not update

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3180]
Because of the way that grade calculations work, extra credit items within a category do not apply a score UNLESS there is already a non-extra credit item in place within the category that is also supplying a score.

Example:

EC item only in category, worth 10 points. Student receives a score of 9. No non-EC item in place:
9 / 0 = 0

EC item in category, worth 10 points, and normal item worth 50 points. Student receives a score of 9 on EC, a score of 30 on normal item:
(9 + 30) / 50 = 78%

The course grade calculations are currently working as expected in GBNG. However, if you have an EC item only in a category and a student receives a score, the category subtotal is displaying a percentage for the category. Since the denominator is 0, however, the category should still reflect a "-" in the subtotal column:

![image](https://cloud.githubusercontent.com/assets/11447474/17592328/e6eaf546-5faf-11e6-9d19-811afe6ea2c9.png)

**Comment by steveswinsburg** [comment]
Discussed 12/8/2016:
If category only has EC item, don't try to calculate category total.
If category has normal items without scores and an EC item with a score, don't try to calculate category total either.

**Comment by steveswinsburg** [comment]
I've adjusted the logic in the calculation of the category score which makes the above two conditions equivalent. Items without a score are excluded from the calculation anyway.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/17903559/f14c26c0-6939-11e6-90df-c981fb4ff0ac.png)
