### ISSUE TITLE
Create course site is not available for admin user

### ISSUE THREAD

**Issue by mpldev** [sakaiproject/sakai#3205]
There's no possible to create course sites with the default deploy in the target versions, then I edit the following realms, adding admin user  and set maintain role with all functions enabled in:
  !group.template.course 
  !matrix.template.course 
  !site.template.course 

But the result is the same and catalina.out log don't show anything related to course site creation.

Target versions:
11.0 deploy in august 4
11.x deploy in July 29

Tomcat version: 8.0.36

![site-tool](https://cloud.githubusercontent.com/assets/20426825/17744948/867deaa0-646f-11e6-944e-a7e12eb97fe5.PNG)

![site-tool-en](https://cloud.githubusercontent.com/assets/20426825/17745003/cde5fbe4-646f-11e6-8692-94f015b33e1a.PNG)

![realmid](https://cloud.githubusercontent.com/assets/20426825/17745638/3fc198ca-6472-11e6-9a29-6daf98e12b19.PNG)

![edit realm group-template-course](https://cloud.githubusercontent.com/assets/20426825/17745643/43fb9ad0-6472-11e6-825a-0f8b0b39b0d2.PNG)

**Comment by steveswinsburg** [comment]
Hi @mpldev  - the github issue tracker is currently only for gradebook issues. Please file this issue at https://jira.sakaiproject.org. Thanks.
