### ISSUE TITLE
With percentages on, '%' disappears from grade label after focus

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#3211]
To replicate:
1. Have a Gradebook set to percentages
2. Have a Grade Item with some grades
<img width="565" alt="screen shot 2016-08-18 at 1 19 53 pm" src="https://cloud.githubusercontent.com/assets/608337/17760910/7bcd5fbe-6546-11e6-9d8a-b967b659359a.png">
3. Click on the grade cell to enter "edit mode"
<img width="569" alt="screen shot 2016-08-18 at 1 20 28 pm" src="https://cloud.githubusercontent.com/assets/608337/17760939/93a6e24a-6546-11e6-8eb9-9160307ad23e.png">
4. Without changing the grade, click 'return' or the 'down arrow' to navigate away from the cell
5. Grade is rendered without '%'
<img width="567" alt="screen shot 2016-08-18 at 1 21 58 pm" src="https://cloud.githubusercontent.com/assets/608337/17760965/c5728478-6546-11e6-8c94-9d74db7d80e9.png">

**Comment by kyleblythe** [comment]
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/17788671/d3c1baec-655c-11e6-9fd2-14d751d242a5.png)
