### ISSUE TITLE
Changing large grade results in error

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#3212]
To replicate:
1. Have a large grade e.g. 1,000,000:
<img width="553" alt="screen shot 2016-08-18 at 1 24 58 pm" src="https://cloud.githubusercontent.com/assets/608337/17761032/3782307c-6547-11e6-8d4a-2efc0a18dbbd.png">
2. Try to change to back to something smaller e.g. 10:
<img width="554" alt="screen shot 2016-08-18 at 1 25 08 pm" src="https://cloud.githubusercontent.com/assets/608337/17761039/42888142-6547-11e6-88ca-df4214ce1631.png">

**Comment by kyleblythe** [comment]
Confirmed.
