### ISSUE TITLE
Columns move around on import screen when toggle between show/hide item w/ changes

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#3222]
![image](https://cloud.githubusercontent.com/assets/11447476/17790008/af18bc3a-6562-11e6-94e2-8395ccd77ac6.png)

![2016-08-18_16-41-34](https://cloud.githubusercontent.com/assets/11447476/17790010/b18b3290-6562-11e6-8a3e-e7ef7600fb30.png)

**Comment by kyleblythe** [comment]
Confirmed.
