### ISSUE TITLE
Import - If creating new item w/ comments column only, import process shows status of "unknown," completes import w/ no action

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3223]
If you add a new comments column in the .csv file w/ no corresponding item points column, you are able to proceed through the import process.

The import selection screen shows a blank item with a status of "unknown":

![image](https://cloud.githubusercontent.com/assets/11447474/17789985/9aad68d6-6562-11e6-9148-c6a336d6c340.png)

You then get a blank confirmation screen, and when finalizing the import, a green confirmation status stating "Gradebook items imported successfully." Nothing was imported, however.

We should probably either exclude this column from the import altogether, provide an item creation screen, or provide an error?

**Comment by steveswinsburg** [comment]
This was fixed in #3127 but a slight refactor broke it. A good case for unit tests :(
Fixed in latest PR #3239.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/17902153/217bfcd6-6934-11e6-9abf-2294c9b21c31.png)
