### ISSUE TITLE
Updated comments are not displaying a checkbox for their associated item

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#3225]
![2016-08-18_16-56-10](https://cloud.githubusercontent.com/assets/11447476/17790505/bc9570d6-6564-11e6-8b1e-6983b9bcc2ac.png)

**Comment by kyleblythe** [comment]
To address this, provide an indented checkbox for the comments row **only** when there are updated comments.

In the case of an item and its comments being updated, provide checkboxes for both. Selecting the item's checkbox will automatically check the corresponding comment row's checkbox.

Additionally, to provide additional visual clarity, move the "Title" column closer to the checkbox column.

Mockup:

![updated checkboxes](https://cloud.githubusercontent.com/assets/11447474/17909457/90a658cc-6952-11e6-9739-59989c64c757.png)

**Comment by steveswinsburg** [comment]
Closing as this is wrapped up in #3274.
