### ISSUE TITLE
For new items, do not show comments row. 

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#3226]
Comments row for a new item currently shows as "Update". If not in the spreadsheet, don't show at all.

![image](https://cloud.githubusercontent.com/assets/11447476/17790600/36cc0cc0-6565-11e6-9779-b79139704ff8.png)

**Comment by steveswinsburg** [comment]
Hey @jeffpasch I am not seeing this problem. If you are still seeing after the latest PRs are merged, could you please attached the CSV you used?

![screen shot 2016-08-22 at 9 04 04 pm](https://cloud.githubusercontent.com/assets/129129/17852733/0e3ef674-68ac-11e6-87eb-7b0e8c8e28e1.png)

**Comment by kyleblythe** [comment]
Maybe this was fixed? When I look at master now, I see:

- new item comments columns marked as "New," when present in the spreadsheet

- no comments columns accompanying new items, when not present in the spreadsheet

![image](https://cloud.githubusercontent.com/assets/11447474/17902033/a2ceaa14-6933-11e6-82ea-de467c979c9c.png)

Can this one be resolved?

**Comment by kyleblythe** [comment]
Not sure if this issue should be closed, as we may need to reverse any updates that were made for this ticket, so as to have new items' comments appear in #3274. Sorry, @steveswinsburg and @payten :(

**Comment by steveswinsburg** [comment]
I think I'll just track everything over at #3274 to make this simpler to manage.
