### ISSUE TITLE
Import - on item selection screen, items do not reflect the ordering of the GB or the downloaded spreadsheet

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3253]
The ordering of the items on the item import selection screen does not match that of the GB itself or of the downloaded spreadsheet, making it difficult to locate the correct items to select.

GB ordering:
![image](https://cloud.githubusercontent.com/assets/11447474/17908287/d7c99e4e-694d-11e6-8eea-d561fdac1d7a.png)

Spreadsheet ordering:
![image](https://cloud.githubusercontent.com/assets/11447474/17908340/13cb9758-694e-11e6-9ac0-6bec1d287e87.png)

Import screen ordering:
![image](https://cloud.githubusercontent.com/assets/11447474/17908355/20fd42c8-694e-11e6-903b-73d5709ea722.png)

**Comment by steveswinsburg** [comment]
It would be easiest to order by the imported file column order, would this be ok @kyleblythe ?

**Comment by kyleblythe** [comment]
Yep! I think that works great, and would be most intuitive for folks, as it'd reflect any ordering changes they made in their spreadsheet file.

Thanks, @steveswinsburg !

**Comment by steveswinsburg** [comment]
Ok I will order the items in the selection screen to match that of the imported file. However were you referring to the ordering changes flowing through to the actual order within the gradebook? That may be able to be done but we'd need to think about if that was indicated as an 'update'?

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

Great, thanks! And no, I don't think it's necessary to have the changes flow through into the ordering of the GB itself - I think it's important that instructors set that ordering explicitly within the tool, especially considering we have both the grouped & ungrouped orderings.

**Comment by kyleblythe** [comment]
Confirmed.

Spreadsheet:
![image](https://cloud.githubusercontent.com/assets/11447474/17975009/2d6f5e42-6ab6-11e6-9273-eb3194862076.png)

Import Screen:
![image](https://cloud.githubusercontent.com/assets/11447474/17975026/37d5b80e-6ab6-11e6-9d88-8f3343acb038.png)
