### ISSUE TITLE
Provide a warning when changing the grading schema from "Letter Grades with +/-" to "Letter Grades" when there are grade overrides with +/-

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3258]
If the instructor has provided course grade overrides to students, supplying +/- scores, and then they try to change the grading schema from "Letter Grades with +/-" to "Letter Grades," provide a warning dialog confirmation upon clicking "Save changes":

> Warning: Your Gradebook contains manual course grades containing +/- values. Changing your grading schema will convert these to standard letter grades. Continue?

What do you think, @jeffpasch @steveswinsburg @payten ?

**Comment by steveswinsburg** [comment]
I think we would want this check a bit wider to cater for any other
permutations.

Options:

1. If scheme being changed and there are any grade overrides at all,
present the warning.

2. If there are any grade overrides that don't map to the new scheme ( ie A
in letter grade with +/- scheme has a mapping of A in letter grade only),
then present the warning.

The problem with 2 is if the letter mappings match but the percent mappings
don't, it could be weird. Maybe safer to just do 1?

Wdyt?

sent from my mobile

**Comment by steveswinsburg** [comment]
Also is this just a warning or are we actually converting any data?

sent from my mobile

**Comment by jonespm** [comment]
Yeah, in the particular case we had the user actually had completely different letters in one scheme verses another defined. It wasn't simply just the +/- differences. They had things like I, WD, NC that were mapped. So because these didn't map to anything in the schema they would cause errors. They'd also cause errors it seems if they switched to a new schema that didn't have them as it wouldn't know how to map them.

I don't really know how big an issue our specific case is, but I think the message should be general. And rather than converting data it should just say that any override grade unable to be mapped will result in a score of 0.

**Comment by jonespm** [comment]
It looks like in the original gradebook, if you have grades that don't map with the new schema it doesn't let you change it, it just says.

"You have manually entered course grades of the grade type "Letter Grades with +/-". To change the course grade type, you must first undo all manually overwritten course grades."

Seems like a pain to fix. I don't know what's worse having to have the instructor removing all grades first or having them all calculate to 0. 

I think in the best world you could change types but it would have an alert marker by the grade override in the UI that it wasn't in the schema and was automatically set to 0. But I know how we're talking about edge case feature creep. ;)

**Comment by steveswinsburg** [comment]
Discussed 26/8/2016:
When saving, if there are unmappable grades, present a warning and reset the schema back to what it was.

**Comment by steveswinsburg** [comment]
#3285 has a PR with this functionality. Note that I did not reset the grading schema back to what it was previously as we have avoided that for other warnings. So it looks like this:
![screen shot 2016-08-30 at 10 38 08 pm](https://cloud.githubusercontent.com/assets/129129/18089285/81143e78-6f02-11e6-9c01-08ea9565bc3a.png)

**Comment by steveswinsburg** [comment]
Note there is a DB conversion for this. But it is not essential, it's just dropping an unused column.

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/18182737/328572fa-705f-11e6-9c35-8a1e5d0dda35.png)

**Comment by smarquard** [comment]
This statement in sakai_11_1-11_2_mysql_conversion.sql has the wrong table case for mysql:

ALTER TABLE gb_grade_record_t DROP COLUMN user_entered_grade;

should be

ALTER TABLE GB_GRADE_RECORD_T DROP COLUMN user_entered_grade;

**Comment by jonespm** [comment]
Thanks @smarquard I noticed this today and will fix
