### ISSUE TITLE
Use the portal exception handling mechanism when Gradebook encounters uncaught exception

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#3292]
See if we can leverage the Sakai portal's exception handling (form, emails, etc) instead of just showing the stacktrace.

**Comment by steveswinsburg** [comment]
Have a look in GradebookNgApplication - there is a RequestCycleListener which intercepts checked Exceptions and redirects to ErrorPage which is our own 'Something went wrong' page. It might need a bit of a rework to pass off to the portal exception handler.

If not, we could just rework ErrorPage to do a similar thing and have a collapsed stack trace maybe.

**Comment by payten** [comment]
Hm.. you were right @steveswinsburg , there's no nice and obvious way to incorporate the portal error handling into the wicket world 😞 

I've had a go, by wrangling the request cycle to hit the portal's `ErrorReporter.java`.  This seems to somewhat worky: https://github.com/sakaiproject/sakai/compare/master...payten:3292-error-reporter

What do you think?  I have a feeling the portal ErrorReporter assumes it will be rendered within an iframe.  That would be ideal, as submitting a report wouldn't then take the user away from the tool.  However, I couldn't see an easy way to deliver the error report within an iframe in this context.

**Comment by steveswinsburg** [comment]
Hey @payten, just going to assign this to me so I don't forget about having a look. Then will let you know 🐭

**Comment by payten** [comment]
I wasn't super excited about the solution above, so I had a look at the other wicket apps in Sakai.  It looks like Delegated Access re-raises any exceptions which brings it to the attention of the portal error handler.  Perhaps that's the right approach here. 

I think the only issue with that approach is that any exceptions that occur on an AJAX request are returned as a 500s may be missed be the user (it's logged in the console but Wicket doesn't catch the exception and do anything meaningful with it).  An approach might be add a global AJAX error handler to insert the exception into the page upon receiving it.  Maybe something like this: https://github.com/sakaiproject/sakai/compare/master...payten:3292-exception-handling

Still not a perfect solution, but maybe getting warmer.

**Comment by jeffpasch** [comment]
No good solution for this at this time. Closing.
