### ISSUE TITLE
"Uncategorized" category does not appear when editing a categorized item

### ISSUE THREAD

**Issue by JulianneMorgan** [sakaiproject/sakai#3311]
The category for "uncategorized" shows as a blank area in the dropdown list when I want to move a gradebook item that is in a category to the uncategorized category. 

Steps to reproduce: 

1. Create a gradebook item and assign it to an existing category
2. Click on Edit Item Details
3. From the "Category" drop down, the first blank area is actually the "uncategorized" category, but the text indicating that information does not appear. 

![image](https://cloud.githubusercontent.com/assets/22077379/18351159/095cfaa4-75a7-11e6-8115-d79d807575c4.png)

Users probably do not typically need to move something to uncategorized, but it may be helpful to see the name. It may also be helpful if the uncategorized category appeared at the bottom of the dropdown list rather than the top.

**Comment by kyleblythe** [comment]
Thank you, @JulianneMorgan ! This is a great catch, and seems like a very reasonable remedy. The GB team will look into this.

**Comment by steveswinsburg** [comment]
Discussed 9/9/2016:
Add 'Uncategorized' to replace the blank and add to the bottom (as categories in the list respect the ordering of the categories in the gradebook)

**Comment by kyleblythe** [comment]
Confirmed:

![image](https://cloud.githubusercontent.com/assets/11447474/18566087/7614e9d6-7b60-11e6-8ef2-6585fae1cc57.png)
