### ISSUE TITLE
Cannot add new GBNG item to new category to new Site in 11.x when in FireFox.

### ISSUE THREAD

**Issue by willkara** [sakaiproject/sakai#3312]
Steps to reproduce:

1. Create new site with gradebook
2. Create categories
3. Try and add an item to a category

It looks like it's not noticing the title/points when you try and save it. Normally, the "include in course grade" box is checked when you assign to category.

We had one of our Instructional Designers test it out in 11.x AND trunk and she was only able to reproduce it in 11.x.

[Here's a video](https://ru-stream.rutgers.edu/media/gradebook+in+Firefox/1_8hvem0sq).

And here's an image
<img width="551" alt="screen shot 2016-08-29 at 11 49 41 am" src="https://cloud.githubusercontent.com/assets/3278887/18354013/184eb3b2-75b2-11e6-9df6-5850882b4d64.png">
 of the error.

**Comment by steveswinsburg** [comment]
IIRC this was fixed recently as it was to do with the form validation not firing?

**Comment by payten** [comment]
Fixed in #3116.  The patch is present in master however it hasn't been merged into the 11.x branch.  The PR with the patch has the 11.2 milestone so might be merged soon?

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/18971644/c52da8b0-8663-11e6-8e03-0c39027ed180.png)
