### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mathiasrw** [sakaiproject/sakai#3366]
https://github.com/sakaiproject/sakai/blob/master/samigo/samigo-app/src/webapp/js/utils-emi.js#L70 needs to replace `undefined`with `'undefined'` to be a real "type of" check.

**Comment by steveswinsburg** [comment]
Hi, currently the github issue tracker is only for gradebook issues. Please file this at jira.sakaiproject.org.

Thanks.

**Comment by mathiasrw** [comment]
As mentioned in #3319 Its too much of a hassel to do the signup and JIRA thing for adding 2 chars. 

Its fine that you closed this issue, but please remember to get rid of the bug.
