### ISSUE TITLE
Unable to create GradebookNg item under fr_CA configuration

### ISSUE THREAD

**Issue by mameawadiop** [sakaiproject/sakai#3369]
We have all our locale configurations (server, tomcat, browser ...) using fr_CA and we get an error message when we try to create an item in Gradebook, see image.

![gradebookng-create-error](https://cloud.githubusercontent.com/assets/11739503/18714915/43d0544a-7fe5-11e6-9e31-e368bf811863.png)

**Comment by mameawadiop** [comment]
Also there is a TODO associated to the line causing the error 

	
**AddOrEditGradeItemPanelContent.java**
`		// TODO date format needs to come from i18n
		final DateTextField dueDate = new DateTextField("duedate", new PropertyModel<Date>(assignmentModel, "dueDate"),
				"mm/dd/yyyy") {
`

**Comment by payten** [comment]
Hi @steveswinsburg, is there a system-wide setting for date formats we can access? Or should GradebookNG add one to its own properties file?

**Comment by steveswinsburg** [comment]
I thought there was a way to get the defaults from the Locale but I think I am thinking of another app where these are injected. This would actually be good for Sakai to do, so that each tool doesn't have to do it in its own way.

**Comment by steveswinsburg** [comment]
@mameawadiop this has been merged to master. If you pull the latest and add this to your `GradebookNgApplication_fr_CA.properties` translation file, give it a shot:

````
format.date = yyyy-MM-dd 
format.datetime = yyyy-MM-dd HH:mm
````

**Comment by mameawadiop** [comment]
Hi Steve,

I will check and let you know.
