### ISSUE TITLE
Duplicate TA rules are allowed

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#3370]
Instructors are able to create duplicate permissions for a given TA:
![image](https://cloud.githubusercontent.com/assets/11447476/18741474/711b6262-807d-11e6-9cc9-892e20deb525.png)

We should have validation to catch this.

**Comment by steveswinsburg** [comment]
Should we error on this or just silently discard/consolidate them?

**Comment by steveswinsburg** [comment]
We only have one feedback panel so the messages are combined. See screenshot.
![screen shot 2016-09-30 at 8 56 32 am](https://cloud.githubusercontent.com/assets/129129/18975257/33dd97ba-86ec-11e6-8db3-5eaa9e1c9e56.png)

**Comment by jeffpasch** [comment]
Yup. That works really well. :shipit:

**Comment by kyleblythe** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/11447474/19083745/6d5fe7ca-8a31-11e6-88e3-7c82acb933d5.png)
