### ISSUE TITLE
Updates to student drilldown

### ISSUE THREAD

**Issue by jeffpasch** [sakaiproject/sakai#3371]
- [ ]  When the course grade is not released to students, display "Not released to students*" to the right of the course grade. (see below)

- [ ]  Change the asterisk text at the bottom of the screen to read: "*To release final course grade to students, go to Settings and select "Display Final Course Grades to Students." (see below)

![image](https://cloud.githubusercontent.com/assets/11447476/18741783/f65e118a-807e-11e6-9dc3-1f053d454576.png)

- [ ] To ensure the asterisk test is always visible, pull it outside of the scrolling area to right above the "Previous student" text:
![image](https://cloud.githubusercontent.com/assets/11447476/18741958/d0343222-807f-11e6-8d6a-ff9b52bfd09e.png)

- [ ]  To save real estate at the top of modal, pull the course grade, Grouped by Category, and Expand all, Collapse all onto the same row.  Pull course grade value closer to field name:

![image](https://cloud.githubusercontent.com/assets/11447476/18742078/62136302-8080-11e6-90db-0fe6c07d6be6.png)

- [ ]  If possible, provide a fixed table header.

**Comment by kyleblythe** [comment]
Confirmed! Awesome. I'm seeing:

* Not release to students text to the right of the course grade
* Updated text
* Text appearing at bottom of screen
* Buttons are appearing in-line with the course grade

![image](https://cloud.githubusercontent.com/assets/11447474/18971474/26f71096-8663-11e6-8f09-1d922e080b78.png)

* And the fixed header!

![image](https://cloud.githubusercontent.com/assets/11447474/18971497/39bb8d38-8663-11e6-97ab-f21677047c05.png)

Closing this one out.
