### ISSUE TITLE
Support for the comma as a decimal mark

### ISSUE THREAD

**Issue by PhilRancourt** [sakaiproject/sakai#3375]
Many countries uses the comma as the decimal mark (Spain, France, South Africa, French Canada, etc). GradebookNG should eventually support the comma as a decimal mark.

**Comment by steveswinsburg** [comment]
This would need to be a display only feature as I don't think the `,` is supported as a decimal mark in the database (at least in MySQL, Oracle may support it via the NLS settings). So it could be translated going in and then back out again.
ref: http://stackoverflow.com/questions/8669212/change-decimal-separator-in-mysql

**Comment by jonespm** [comment]
It looks like in gradebook classic this is done in the app for both entry and display and it's stored always as a decimal in the database.

https://jira.sakaiproject.org/browse/SAK-17985

**Comment by steveswinsburg** [comment]
Yep and that's the simplest way to do it too - we can just pass the grade through a formatter before displaying it.

**Comment by steveswinsburg** [comment]
Closing this in favour of #3930.
