### ISSUE TITLE
Numerical Response wieghts

### ISSUE THREAD

**Issue by Itenium** [sakaiproject/sakai#3391]
Good day

When a test and quizzes is set up, with numerical response I have problems that have multiple answers.

For example. 
For a rectangle with side A = 1 m, B = 0.5 m, Determine the 
Area {0.5} m^2
Circumference {3] m

At this stage Sakai assigns the same mark for each answer.  In this case 50% for each correct answer given

I would like a additional feature where one can change the weights.
Thus the first answer need to count for example 75% and the second answer needs to count 25%.

Thank you very much

**Comment by steveswinsburg** [comment]
Hi, currently the github issue tracker is only for gradebook issues. Please file this at jira.sakaiproject.org.

Thanks.
