### ISSUE TITLE
Drag/Drop Items in GBNG temporary

### ISSUE THREAD

**Issue by willpagan** [sakaiproject/sakai#3401]
It appears that when reordering items by drag/drop, the order is only temporary.  If you refresh the tool, or switch to ta different tool and come back to NG, the order returns to it's original state.

If you use the move left/move right option from the item dropdown, then the new order is maintained.

Here's a screencast showing the behavior in both Chrome and FireFox.
http://www.youtube.com/watch?v=fmu6rPfza7s

**Comment by steveswinsburg** [comment]
Hi Will,
What version of Sakai are you using? If you took a version before 11 was released then you likely don't have the fix in #1336 which resolves this issue. If you are unsure you could check the commit log to see if you have the commits in that issue.

Cheers.

**Comment by willpagan** [comment]
Thanks Steve!
