### ISSUE TITLE
Category Grade Does not Calculate correctly w/EC Item

### ISSUE THREAD

**Issue by master-bob** [sakaiproject/sakai#3411]
When a category has an Extra Credit (EC) item within it, the category score accounts the EC item as a regular item.

For example:
![image](https://cloud.githubusercontent.com/assets/6335721/18957538/81f8ffe4-862d-11e6-8aac-e898e7eca834.png)

EC is an extra credit item out of 10 points. Exam is out of 100 points. Victor has a score of 0/10 for the EC and 100/100 for the Exam. His correct category score should be 100% ( (0+100)/100 = 100%).

Let's say he received 5 points in the EC item. His score should then be 105% ( (5+100)/100 = 105%). Currently it is calculated as 95.45%.
![image](https://cloud.githubusercontent.com/assets/6335721/18957672/f4feaafc-862d-11e6-953d-8a4b31ba0c44.png)

**Comment by steveswinsburg** [comment]
Similar to #3180.

**Comment by steveswinsburg** [comment]
FYI this has been merged to 11.x already but is still in ready for test. We will communicate a better way to handle this shortly.

**Comment by kyleblythe** [comment]
Confirmed in trunk:

![image](https://cloud.githubusercontent.com/assets/11447474/19279656/43b8b684-8fb0-11e6-8479-8a32e6dc024c.png)
