### ISSUE TITLE
Final Grade Mode

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#3431]
Requested by Notre Dame.
A column that can be filled with whatever a faculty member wants to show as the 'final grade' in their class--this is to allow instructors who have grading methods that are not covered by GradebookNG (and may never be covered due to things like 'curving grades').

Both direct input and import should be supported.

For the upload it would probably make sense to just have the grades going directly into the Course Grade Override rather than an additional column. We could provide an option where the gradebook is in 'course grade only' mode so only that column appears. Initially, the direct entry will still be via the course grade override window, but the rules around the validation will be relaxed.

**Comment by steveswinsburg** [comment]
Discussed 7/10/2016: Provide a special column format in the upload that will be used. This will allow others to make use of this feature also.

**Comment by steveswinsburg** [comment]
Note: Course Grade Formatter has been updated to remove the percentages from Instructor display when in this mode. need to confirm this change.
Also, 'Show Points' should probably be disabled also.

Need to think about what the student sees as well. Should any of the settings be disabled in the Course Grade Display section?

**Comment by steveswinsburg** [comment]
This is now awaiting PR

**Comment by steveswinsburg** [comment]
A new property is added to sakai properties to enable this:
`gradebook.enable.finalgrade=true`

As well as a new setting in GradebookNG settings to activate it per site (if enabled globally). This then allows an instructor to optionally import the final course grade.

Both direct input via the course grade override window and importing the data in bulk are supported.

For importing, the column must be prefixed with a `$`

**Comment by lgekeler** [comment]
@steveswinsburg Do you have access to https://experimental.nightly.sakaiproject.org/ to add gradebook.enable.finalgrade=true to sakai.properties ? It's not there yet so I'm unable to test. Is it on another server? https://experimental.nightly.sakaiproject.org/sakai/sakai.properties

**Comment by steveswinsburg** [comment]
Ah yes I will add to the experimental set.

**Comment by steveswinsburg** [comment]
Done. Rebuilt daily at around 12:30PM and 12:30AM Eastern.

**Comment by lgekeler** [comment]
I thought we'd be able to type directly into the course grade box without clicking on the comments box? [https://www.screencast.com/t/2NXFpYob]

**Comment by steveswinsburg** [comment]
No, the editing is currently done via the Course Grade Override option.

**Comment by lgekeler** [comment]
Please change and allow the Course Grade column to be edited spreadsheet style like the Gradebook Item columns are.

**Comment by lgekeler** [comment]
How do I test the Import of Final Course Grade via .csv? What should I name the column header? Anything else special? I used the "Export Gradebook" function because the "Custom Export" says it can not be used for an Import (although that claim seems off to me). Standing by...

**Comment by steveswinsburg** [comment]
The direct entry is going to take significantly more work because that field is not setup like that. Original spec was to retain the course grade override workflow.
For importing, see comment above: "For importing, the column must be prefixed with a $"
Cheers.

**Comment by lgekeler** [comment]
![customizedexportscannotbeloadedback](https://cloud.githubusercontent.com/assets/5331541/22515938/3b62f092-e872-11e6-963d-e053787f224e.png)

This Note is no longer true. The wording for the Custom Export should be changed.
Maybe:
Note: You must include "Student ID" to be able to import back into Sakai.

The note gets much longer if you try to include specialized instructions here; I'm not sure where to put the note about the $ symbol, but that absolutely needs to be part of the solution.

**Comment by lgekeler** [comment]
![finalgrademodenote](https://cloud.githubusercontent.com/assets/5331541/22516153/de8305c8-e872-11e6-95c9-c5b5c53a7d24.png)

This note is confusing. I don't think instructors will understand what "normal gradebook column" means. What about:

Final Grade Mode allows you to enter any score or value into the Course Grade column as a Grade Override. Additionally, prefixing $ to the "Grade Override" column header exported from Sakai will allow you to bulk import the Course Grade from your own spreadsheet calculations. You can still optionally add other gradebook items as desired.

**Comment by lgekeler** [comment]
I was able to enter 30 characters as a course grade. How long is the field? Since the column width can't be changed, I think the field should be set to wrap when it exceeds the column width.

**Comment by lgekeler** [comment]
Display Error in Modal Window:
![modalgradeoverridedoesnotdisplaynewgrade](https://cloud.githubusercontent.com/assets/5331541/22516773/e294726c-e874-11e6-98f7-294502216b0f.png)

But after clicking, the modal window matches the display of the larger gradebook.
![manualclicksavecourseoverride](https://cloud.githubusercontent.com/assets/5331541/22516793/f520372c-e874-11e6-8022-bb957182a593.png)

**Comment by lgekeler** [comment]
Gradebook Item Import Selection

1) the informational note, although consistent with other note styles, does not meet the accessibility contrast requirements.

I don't think most people see these anyway. They don't in the "Import from Site" when being told it has been queued...

Change Request: Implement Course Grade Override as a regular column up above like the other columns. The need for the informational note then goes away.

2nd Choice, Give the note the same styling the notes above have, dark black text on blue background.
![gradebookcustomimport](https://cloud.githubusercontent.com/assets/5331541/22517080/eff9250a-e875-11e6-9713-e2598748e1e0.png)

**Comment by steveswinsburg** [comment]
Difficult to track all of this here so I am editing your comments and adding mine in italics :)

**Comment by steveswinsburg** [comment]
@lgekeler - see the following screenshots for the new instructions. This should make it clear on both the import and export pages what the file conventions are. Let me know if you want anything adjusted.

 ![screen shot 2017-02-08 at 8 09 55 am](https://cloud.githubusercontent.com/assets/129129/22711679/2bcf9554-edd6-11e6-813a-50967b18ba4f.png)
![screen shot 2017-02-08 at 8 09 49 am](https://cloud.githubusercontent.com/assets/129129/22711680/2c30527c-edd6-11e6-9244-b2bf5650939f.png)

**Comment by lgekeler** [comment]
Custom Export looks nice.  I think it's good. I can follow up doing more QA to verify when this change gets merged to experimental.

**Comment by steveswinsburg** [comment]
@lgekeler ok this is in master now. This will be on nightly and experimental soon.

**Comment by steveswinsburg** [comment]
Oh whoops, it wasn't merged but is now.

**Comment by lgekeler** [comment]
@steveswinsburg Thanks Steve. I'll be able to test this today. I also noted on a listserve that Duke is looking at a grade column that would hold either mid or final grade and have that value pushed to an SIS, Peoplesoft in their case. That is a scenario I wasn't even thinking about but it's a valuable one. What are your thoughts about supporting it?

**Comment by lgekeler** [comment]
# PLEASE HOLD OFF. I want to discuss these design flaws internally before we put anymore into this.

@steveswinsburg @kyleblythe @jeffpasch I'm testing on https://experimental.nightly.sakaiproject.org/ . There are problems. Not sure if they're related to this change or not. Here was my workflow in https://experimental.nightly.sakaiproject.org/portal/site/AEKU_731H_3640/

1. In GB settings I chose: No Categories, Points and selected "Final Grade Mode" box. Just below, I was still able to insert categories (FAIL), which I did (instructors will do this!): https://www.screencast.com/t/oSPbiUIp
2.I proceeded to the GB's blank screen and clicked "Add Gradebook Item." Named my item "Hwk 1". Pressed "Create." Received this screen: https://www.screencast.com/t/tag8xday
3. Changed title to "Hwk1". Removed Chk box "Include Item in course grade calculations". Pressed Create. Received this screen: https://www.screencast.com/t/lPhGBggLG
4. Returned to Setup and Removed the bogus categories. Returned to GB screen. This time students were listed and the headers looked like this: https://www.screencast.com/t/ftxyAMnNCn

Problem Assessment:
1. Should not be allowed to create categories, if choices preclude categories.
2. Error message is ambiguous.

**Comment by lgekeler** [comment]
# PLEASE HOLD OFF. I want to discuss these design flaws internally before we put anymore into this.
@steveswinsburg @jeffpasch @kyleblythe 
Testing site: https://experimental.nightly.sakaiproject.org/portal/site/AEKU_731H_3640/

Gradebook Export/Import with GB Settings here and no categories: https://www.screencast.com/t/wRhMxUgVlb8 (Points, Enable Final Grade Mode, Display to Students, Course Grade Formatted as Points).

1. **Custom Export**, default columns + Course Grade (default: StuID, StuName, GB Itms & Comments). 
2. Open .csv Note that Course Grade column header is prefixed with #, indicating the column is not re-importable.
3. Attempt Import, verify # column does not appear on UI of columns to import.
4. Change # to $, create course grades including: 255 char, 30 char, A+, D-, P, F, 110%, 100%, -49, -0, +0, Text sentences. 
[gradebook_export-AEKU_731H_3640.csv.txt](https://github.com/sakaiproject/sakai/files/797049/gradebook_export-AEKU_731H_3640.csv.txt)
5. Observed all data types imported with the exception of +/- 0 (as expected). Columns wrap as expected to fit width.

Problem: If Final Course Grade mode is checked, why doesn't the export assume that the Course Grade column should be prefixed with $ instead of #?

**Comment by lgekeler** [comment]
# PLEASE HOLD OFF. I want to discuss these design flaws internally before we put anymore into this.

@steveswinsburg @jeffpasch @kyleblythe 
Testing site: https://experimental.nightly.sakaiproject.org/portal/site/AEKU_731H_3640/

Gradebook Export/Import with GB Settings here and no categories: https://www.screencast.com/t/wRhMxUgVlb8 (Points, Enable Final Grade Mode, Display to Students, Course Grade Formatted as Points).

**Gradebook, Import, then Adjust Grade Manually**
1. The grade imported for Brandt Auer "B-" was manually changed to "C". It's misleading for the former value for the GradeOverride cell to be contained in the "Calculated Grade" column. Here: https://www.screencast.com/t/8LsH2H0a
2. Added manual grades to Hwk1 and Hwk 1 for Brandt Auer.
3. Turned to Grade Override modal for Brandt Auer and clicked the link "Revert to calculated course grade." This reverted to the previous Grade Override, Not to using the column for calculations (and according to settings, this would be X points / Y points). https://www.screencast.com/t/Zn0lJK00l

**Problem**: "Revert to calculated course grade" could be construed by a user of Final Grade Mode as a way to see what Sakai would've calculated the grade as if they hadn't imported or overrode the grade with whatever their text was. 

**Problem**: Returning to GB Settings and UNchecking the Final Gradebook Mode results in an error rather than a return to Sakai calculated grades. It would be the expectation that the instructor would want to see what that grade is, or use that grade. https://www.screencast.com/t/rK0ev4r4wD

**Comment by jonespm** [comment]
Your issues with adding items (Hwk1) (and getting Title required and must be unique) should be resolved after the next build by #3970

**Comment by kyleblythe** [comment]
Hi @lgekeler ,

These are some great points you've raised! Responses inline below:

> 1. When Final Grade Mode is selected, if there are settings which are mutually exclusive, they should be unchecked and locked. If Final Grade Mode is deselected, the other options again become available (unlocked).

Are there any settings that are mutually exclusive w/ final grade mode? Having tested in experimental trunk, it appears that final grade mode is compatible with "No categories," "Categories only," and "Categories & Weighting". If there are any mutually exclusive options, I would say that, if final grade mode is enabled, these other options should be disabled; and, if any of these options are enabled, final grade mode should be disabled. Automatically deselecting options on the user's behalf (and without providing indication to the user) could lead to confusion - better to disable the other mutually exclusive option and provide an informative tooltip.

> 2. Instead of a Note about being unable to choose Categories & Weighting when the user has chosen Points, Categories & Weighting should also be unavailable for selection. These controls should also not assume instructor's will make selections from top to bottom.

Agreed 100%. In fact, this appears to be a bug that arises when you ONLY have "points" enabled. As you can see here, if I have any other final grade selections enabled, these two options are indeed mutually exclusive:

https://www.screencast.com/t/Jh9RY1mpH

I will create a separate git issue for this.

> 3. There is no way we should have TWO Export Grade functions, a button and a link. Users will ignore the link every time. A single bottom, with selection options and StuID and Name pre-selected is all we need. For the field "Course Grade" we need two different .csv build sequences. If Final Grade Mode is selected, the Course Grade could be Imported & therefore the .csv build should include the header with the $ sign. If Final Grade Mode is not selected (again, at the time of Export), the course grade column will be prefaced with the # sign (better yet, if simple English communicated "ExportOnly."

This was something we debated for a long time during the original scope of the GBNG project, with the idea that the "custom export" link option would deliver a spreadsheet file with additional columns that users should _not_ attempt to re-upload back into the Gradebook. The standard export (the button option) would deliver a file that could be easily edited and re-imported.

One option, here, could be to keep the "custom export" as-is. It's still a series of additional columns that users should not attempt to re-upload.

What if, then, the custom course grade column (prefixed with the '$' ) was _automatically_ added to the standard export whenever "Final Grade Mode" is selected? This would effectively make the custom course grade column a separate column from the '#' prefixed course grade column that appears in the "custom export" window. It would also make the functionality of the final grade mode more explicit, as it adds additional bits into the export. A textual note could also appear above/below the "Export Gradebook" button only when "Final Grade Mode" is enabled, informing instructors of the presence of this add'l field in the standard export.

What do you think?

> When Final Course Grade Mode is "on" the gradesheet needs to allow spreadsheet style input down the column just like any other column. The column width can be reduced to 30 characters. 255 character input is unnecessary. Thanks.

This sounds like a really useful addition to the tool. And again, its presence really signifies that "Final Grade Mode" adds additional functionality when enabled.

Thanks!

**Comment by steveswinsburg** [comment]
Hi @lgekeler,
1. Let me know if there are any settings that need to be adjusted in regards to final grade mode.
2. I will look at Kyle's bug and fix it.
3. We can certainly add the final grade column to the standard export, if enabled. Would that resolve this?
4. This may be a considerable change. It was specifically ruled out in the original design, but I am happy to change if this is essential.

I'll start on 2. Let me know about the others. Regards.

**Comment by lgekeler** [comment]
@kyleblythe @steveswinsburg 

Quoting Kyle above, 

> Are there any settings that are mutually exclusive w/ final grade mode? Having tested in experimental trunk, it appears that final grade mode is compatible with "No categories," "Categories only," and "Categories & Weighting". If there are any mutually exclusive options, I would say that, if final grade mode is enabled, these other options should be disabled; and, if any of these options are enabled, final grade mode should be disabled. Automatically deselecting options on the user's behalf (and without providing indication to the user) could lead to confusion - better to disable the other mutually exclusive option and provide an informative tooltip.

**Comment by lgekeler** [comment]
Except for the suggestion on note books, the original final  grade mode patch can be backed out of experimental and put on ice. Hopefully forever. I have talked the original requester out of this feature by giving him my guaranteed that @3432 will be implemented in a way that will allow Sakai to be useful to having it automatically curve his grades for him, instead of doing so in an export, re-import course grade mode. @steveswinsburg @jeffpasch @kyleblythe

**Comment by steveswinsburg** [comment]
Hi @lgekeler, ok I will back this out. Just a note, experimental is actually master plus some settings so I'll find the code relating to this and remove it from master. @kyleblythe @jeffpasch are you ok with this being pulled out? No one else needs it?

Once piece remains from above -> Info boxes standardised to be **after** the settings they refer to. Yes?

**Comment by lgekeler** [comment]
@kyleblythe @jeffpasch From our Zoom meeting Friday afternoon, I can say yes, the piece that remains "in" is that Info boxes are standardized to be after the settings they refer to. If you guys have a minute, would one of you confirm for @steveswinsburg ?

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

I think placing the info box for "Display Final Course Grade to Students" after the final grade options to which it refers to makes sense - thanks!

**Comment by steveswinsburg** [comment]
OK textbox adjusted and final grade mode feature removed. PR at #4095.

**Comment by steveswinsburg** [comment]
Code removed. I'll close this one off.

**Comment by ottenhoff** [comment]
So was the intent here to remove everything? I see some remnants of this PR in master (e.g., GradingType.java)

**Comment by steveswinsburg** [comment]
I left in anything relating to the ongoing refactor of the GradebookService to tidy it up. I understand this is probably making this difficult to merge so my suggesting is to take the latest classes of everything back to 11 where possible.
