### ISSUE TITLE
Skip students who have dropped the class during import process

### ISSUE THREAD

**Issue by JulianneMorgan** [sakaiproject/sakai#3471]
An instructor may export the Gradebook spreadsheet at the beginning of the semester then run into the following warning while importing if a student has dropped the class: "A student was found in the imported file but they could not be found in the site."

If possible, it'd be nice to just skip over the row for the student who is no longer in the class. If that's not possible, the warning should identify the student(s) who have dropped. When there are 50+ students in a class, it can be difficult to identify which students are causing the problem.

**Comment by steveswinsburg** [comment]
Agreed, we should skip over the student instead of failing.

**Comment by kyleblythe** [comment]
Confirmed in trunk.
