### ISSUE TITLE
Support for Plain-Text E-Mails

### ISSUE THREAD

**Issue by h-2** [sakaiproject/sakai#3526]
I am aware that many people use HTML in E-Mails, but there are many reasons not to, among them security issues and rendering problems on the receiver side. I don't want to receive html e-mail and I don't want ot encourage my students to use it so it would be really helpful if I could turn it off in Sakai.
I do think that it shouldn't be default, at least if the text actually contains no formatting, but it would already  be start if I could just turn it off manually.

Thanks for the otherwise great system :+1:

**Comment by bjones86** [comment]
@h-2 we currently do not use GitHub Issues for Sakai, except for the GradebookNG project (confusing, I know...).

If you would like to see an option to turn off HTML emails in Sakai, please submit a JIRA feature request ticket @ https://jira.sakaiproject.org

Also of note: most -- if not all -- half decent email clients allow you to choose if HTML emails are rendered in HTML or forced down to plain text.
