### ISSUE TITLE
Student grade summary PDF print not printing all pages

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#3549]
Raised in the Sakai Virtual Conference:

"Rutgers question: Are other users having trouble with the Print feature on Grade Summary? Ours works like print screen... can't print more than the first screen... I mean, all the single student's grades, not just the first screen of her grades :)"

**Comment by payten** [comment]
I can replicate this locally and on nightly:

<img width="1017" alt="screen shot 2016-11-03 at 9 09 16 am" src="https://cloud.githubusercontent.com/assets/608337/19949355/440fa6f4-a1a5-11e6-8b64-b10642e4ced5.png">

The table is being clipped at a certain fixed height and also the fixed header is showing up too.

**Comment by kyleblythe** [comment]
Confirmed in trunk:

![image](https://cloud.githubusercontent.com/assets/11447474/21892989/327d1a14-d8a7-11e6-8d35-cef595f7b5a9.png)
