### ISSUE TITLE
GradebookNG prevents Timeout from Occuring

### ISSUE THREAD

**Issue by master-bob** [sakaiproject/sakai#3563]
When on the GradebookNG tool on master, the session timeout will never be reached.

I tested this by doing the following:

1. Start two sessions in Sakai (using different browsers or private browsing)
2. In Session A, navigate to the GradebookNG tool
3. In Session B, navigate somewhere so that you have done something
4. Leave both sessions alone for a time greater than the timeout period
5. Come back to it where Session A will still be active and Session B will be logged out

**Comment by payten** [comment]
Thanks @master-bob.  This is indeed an issue.  The gradebookng tool has two AJAX polls that may keep the user session from timing out - one for detecting concurrent changes and the other for detecting a dropped connection.

@steveswinsburg do you know if there's a way we can do to avoid reseting the session's `lastAccessedTime`?  I believe the "dropped connection" ping doesn't need to even touch the user session as it's more of a proof of life endpoint.  However, the concurrent edits call will definitely invoke the user's session.

**Comment by smarquard** [comment]
Adding auto=true as a parameter to the AJAX polls should fix this. For example:

/portal/timeout?auto=true
/portal/presence/mercury?output_fragment=yes&auto=true&_=1479120797887

**Comment by payten** [comment]
Thanks @smarquard, I'll give it a go!

**Comment by payten** [comment]
Worked a treat, thanks @smarquard.  PR submitted.

**Comment by master-bob** [comment]
Our local testing confirmed that #3584 fixes this issue.

**Comment by steveswinsburg** [comment]
@ottenhoff has this actually been merged to 11x or is this targeted for a merge?

**Comment by ottenhoff** [comment]
https://github.com/sakaiproject/sakai/commit/a694591810bbeb0518851486e6d97ac11a2a2b8a

**Comment by payten** [comment]
Ah, sorry, thanks @ottenhoff!

**Comment by steveswinsburg** [comment]
Just FYI, the commits will not link up in the Github thread unless you put HASH then the number. That's why we couldn't see it 👍
