### ISSUE TITLE
Popovers broken in GradebookNG

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#3580]
The Bootstrap popover plugin is no longer being included, so GradebookNG tooltips are broke broke:
![screen shot 2016-11-14 at 10 01 33 am](https://cloud.githubusercontent.com/assets/608337/20249625/79a8ad2e-aa51-11e6-8de4-8566a7dd7b10.png)

**Comment by payten** [comment]
I think I see an issue.  GradebookNG scripts load in the <head> which means it picks up a different version of jQuery.  I guess we either need to move our scripts to load after `$PBJQ` loads or instead load our own version of jQuery.

```
> $ == jQuery
true
> jQuery == $PBJQ
false
> jQuery.fn.jquery
"1.12.4"
> $PBJQ.fn.jquery
"1.11.3"
> jQuery.fn.popover
undefined
> $PBJQ.fn.popover
b(b){return this.each(function(){var d=a(this),e=d.data("bs.popover"),f="object"==typeof b&&b;(e||!/destroy|hide/.test(b))&&(e||d.data("bs.popover",e=new c(this,f)),"string"==typeof b&&e[b]()…
```

**Comment by payten** [comment]
This is broken again with the Bootstrap upgrade to 3.3.7.

**Comment by kyleblythe** [comment]
Confirmed that popovers are working in trunk.
