### ISSUE TITLE
Settings page appears to have issues, javascript error "sortable is not a function"

### ISSUE THREAD

**Issue by jonespm** [sakaiproject/sakai#3602]
When going to the settings page on the currently nightly, the following javascript error occurs

`gradebook-settings.js?version=:31 Uncaught TypeError: self.$table.find(...).sortable is not a function(…)`

This is on this line
```
  // setup jQuery sortable on rows
  self.$table.find("tbody").sortable({
```

This error may be related  to other errors on this page. For instance changing from "No categories" to categories causes this error

`morpheus.scripts.min.js?version=67215f1:460 Uncaught TypeError: Cannot read property 'top' of undefined(…)"`

Though that looks changed from #3554 and may be unrelated too?

**Comment by kyleblythe** [comment]
Confirmed in trunk.
