### ISSUE TITLE
Category Grade Incorrect when Uncategorized present in Student Review Mode

### ISSUE THREAD

**Issue by master-bob** [sakaiproject/sakai#3616]
This is within 11.x, as I can't test master at the moment (due to #3602 ).

When a Gradebook is set up with Categories and has items with point values which are uncategorized, the uncategorized items get counted as part of other categories on the Student Review Mode (backed by StudentGradeSummaryGradesPanel.java). This causes the category score to be incorrect.

See the following screenshots:
![Gradebook view](https://cloud.githubusercontent.com/assets/6335721/20541842/d876cf26-b0cc-11e6-81a0-53ce08abc7a3.png)

Grade Summary - Correct:
![Grade Summary - Correct](https://cloud.githubusercontent.com/assets/6335721/20541882/f54a035c-b0cc-11e6-8a38-3f88f636c981.png)

Student  Review Mode - Incorrect
![Student Review Mode - Incorrect](https://cloud.githubusercontent.com/assets/6335721/20541908/1bfc91f4-b0cd-11e6-8d44-75f05892159c.png)

**Comment by ottenhoff** [comment]
This bug is a huge deal!!!!!!

Wow we need to get this merged into 11.x .... doing it now .....
