### ISSUE TITLE
When scrolled to the right, clicking on student name does not bring up overview

### ISSUE THREAD

**Issue by master-bob** [sakaiproject/sakai#3631]
This was tested on 11.x, as I was unable to add more than one item on master.

When a sufficient number of items are added to GradebookNG, a scroll bar appears. When a user scrolls to the right, clicking on the student name does not bring up the student overview panel. A user must scroll back to the left to be able to view the student overview (aka the Grade Summary panel) by clicking on their name.

**Comment by steveswinsburg** [comment]
Hey @payten could you cast an eye over the PR? Cheers.

**Comment by kyleblythe** [comment]
Confirmed. Clicking on student name while spreadsheet is scrolled opens the grade summary screen.
