### ISSUE TITLE
Possible for Fixed Header to Hide first row when scrolled right

### ISSUE THREAD

**Issue by master-bob** [sakaiproject/sakai#3651]
It is possible for the fixed header to hide the first row when scrolled right.

![image](https://cloud.githubusercontent.com/assets/6335721/20814056/22233b80-b7e6-11e6-8613-1ae3b51f81ab.png)

Steps to reproduce:
1. Go to the GradebookNG tool
2. Add some Items (enough so that the horizontal scroll bar is present, you may also resize the window)
3. Go to Settings-> and turn on Categories
4. Go back to Grades, and select Group By Category
5. Go back to Settings, and turn off Categories
6. Go to Grades, see the first row being obscured

**Comment by kyleblythe** [comment]
Confirmed.
