### ISSUE TITLE
Student view: the Course Grade overlaps the blue box below

### ISSUE THREAD

**Issue by mkelseyND** [sakaiproject/sakai#3725]
<img width="930" alt="gbng" src="https://cloud.githubusercontent.com/assets/20171201/21547539/bd73d278-cdb4-11e6-9ca3-a0d2a4848c99.png">
Viewing Gradebook as a student, the Course Grade section overlaps the blue box showing no Gradebook items exist

**Comment by kyleblythe** [comment]
Confirmed in trunk:

![image](https://cloud.githubusercontent.com/assets/11447474/21893240/4aeabdc6-d8a8-11e6-8495-dcfa132b81fa.png)
