### ISSUE TITLE
Selecting an empty group from the section/group dropdown causes the dropdown to disappear, along with all students

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3755]
To replicate:

1. Have an empty section/group in your site.
2. In GBNG, select the section/group dropdown and choose the empty group.
3. No students will display, but the section/group dropdown will also disappear.

Resetting the tool will bring the dropdown back, but we might want to display an error message instead of the table (e.g., no students are present in this group), and retain the dropdown. Alternatively, we can just not show groups in the dropdown if no members exist.

![2017-01-12_09-24-31](https://cloud.githubusercontent.com/assets/11447474/21893464/1ff7421e-d8a9-11e6-9546-e2659f915f49.gif)

**Comment by steveswinsburg** [comment]
Awaiting PR.

**Comment by steveswinsburg** [comment]
Ready to test

**Comment by kyleblythe** [comment]
Confirmed in trunk.

![image](https://cloud.githubusercontent.com/assets/11447474/22803506/46163d56-eee3-11e6-97c6-b2096a1acb41.png)
