### ISSUE TITLE
Settings - make entire section header bar clickable

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3756]
In Settings, we should make the header for each section clickable to expand/collapse the sections. Currently, only the section title is clickable. We can retain the styling / hover effect for the text, but just allow users to click anywhere in the section headers to expand/collapse.

![image](https://cloud.githubusercontent.com/assets/11447474/21893601/a2b3be30-d8a9-11e6-94e8-c944bc25d8b1.png)

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

I'm not seeing these updates reflected in nightly or in the 11.x branch. Have these gotten merged?

**Comment by steveswinsburg** [comment]
I'll check and let you know 👍

**Comment by steveswinsburg** [comment]
Oh looks like I accidentally deleted the branch before it was merged. I'll resubmit.

**Comment by steveswinsburg** [comment]
Ok it is in now.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

Seeing it now in trunk - thanks! One thing - right now, the clickable area across the full width of the section only seems to encompass the height of the text within the header, not the full height of the header itself:

![image](https://cloud.githubusercontent.com/assets/11447474/22889002/ade7f65a-f1d5-11e6-8c86-098ac9d532ae.png)

Can we make it so that the clickable area is the full height of the section? Right now I can see people clicking above/below the current clickable area. Thanks!

**Comment by steveswinsburg** [comment]
Ok new PR sent

**Comment by kyleblythe** [comment]
Confirmed in trunk!
