### ISSUE TITLE
Importing CSV with item that has a hyphen in name causes import failure

### ISSUE THREAD

**Issue by ottenhoff** [sakaiproject/sakai#3800]
Steps to replicate:

1) Create Gradebook Item called "Week 2: January 22 - 29" and make it worth 10 points
2) Use Export functionality
3) Use Import functionality

The failure will produce generic error in UI and no error in logs: "The file you uploaded was not formatted correctly."

The problem is that the regex is very strict:

final static Pattern ASSIGNMENT_WITH_POINTS_PATTERN = Pattern.compile("([\\w ]+ \\[[0-9]+(\\.[0-9][0-9]?)?\\])");

This regex is only allowing a-zA-Z0-9 so any special character like hyphen or colon causes import failure

**Comment by ottenhoff** [comment]
So if gradebook items don't have limits on special characters, my recommend would be to replace the "\w" with ".*

**Comment by steveswinsburg** [comment]
Good catch, will adjust the rgeex. There are limitations on some special characters but will make this work.

**Comment by ottenhoff** [comment]
Okay our clients need a solution here, so should we proceed with my PR?

**Comment by joliet** [comment]
Duke faculty are really frustrated by this import process not working as we've had this issue since fall.  According to D. Eveland's post to sakai-user, more will be experiencing this issue soon.  Hope a fix is in place very soon.

Jolie

**Comment by steveswinsburg** [comment]
FYI, If it was reported earlier it could be have been fixed earlier. We found out about this last week. Happy to go with your PR so long as the restricted chars are catered for and once you import you can then create and edit in the UI with that same pattern.

**Comment by joliet** [comment]
You're right, this is a new issue to the mime type issue we experienced last fall with import.  Didn't mean to imply this specific issue has been unresolved since fall.

**Comment by steveswinsburg** [comment]
@sam

**Comment by steveswinsburg** [comment]
Reopening because the regex in #3801 needs adjusting.

**Comment by ottenhoff** [comment]
Second PR submitted

**Comment by drramsey** [comment]
Verified on nightly master that I could import a gb item that includes a hyphen in the title.  Tried a few other special characters and they worked as well.

**Comment by ottenhoff** [comment]
Merged into 11.x with two commits:

3fbd931ab49f046ad35f8be7797744e985c3cb3b
51f8b44407802e700941d671ba8eff0d159af72d
