### ISSUE TITLE
Code shouldn't use e.printStackTrace()

### ISSUE THREAD

**Issue by ottenhoff** [sakaiproject/sakai#3807]
tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
133:                            e.printStackTrace();

tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
207:                    e.printStackTrace();
1185:                   e.printStackTrace();
1579:                   e.printStackTrace();
1708:                   e.printStackTrace();

tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java
139:                    e.printStackTrace();
142:                    e.printStackTrace();

tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
237:                                            e.printStackTrace();
276:                                            e.printStackTrace();

**Comment by jeffpasch** [comment]
Steve can you speak to this one?

**Comment by steveswinsburg** [comment]
Yep will correct this.

**Comment by ottenhoff** [comment]
I submitted a PR a few days ago

**Comment by steveswinsburg** [comment]
Closed by #3808
