### ISSUE TITLE
Settings panels no longer collapse

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#3842]
Discovered whilst addressing #3756 - the settings panels no longer collapse. They open fine.
Maybe someone broke jQuery?
http://stackoverflow.com/questions/12646455/accordion-doesnt-collapse

**Comment by steveswinsburg** [comment]
From offline discussion with @payten : Morpheus now loads bootstrap even if it has been loaded before.. so two events are bound to the link, so it closes and opens in quick succession
We can fix it by downgrading wicket's jquery down to v1.11.x (from v1.12.4) - but not sure if that's possible 
Alternatively, we can allow v1.12.x to be supported more widely.. e.g.
````
--- a/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
+++ b/portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
@@ -69,7 +69,7 @@
         }
         if ( window.jQuery ) {
             tver = jQuery.fn.jquery;
-            if ( tver.indexOf('1.11.') == 0 ) {
+            if ( tver.match(/^1\.1[1|2]\.[0-9]+/) ) { // match 1.11.x or 1.12.x
````

**Comment by payten** [comment]
A similar issue? https://github.com/steveswinsburg/sakai-widgets/commit/eaf94db462ef74549752f5c9a9fca14efca02b80

It looks like we can force Wicket to use Sakai's version of jQuery.  That would preferable to introducing a new untested jQuery version to the entire application.

**Comment by steveswinsburg** [comment]
Yup I think that is the best way around this. This is the same approach we took when inlining the widgets.

**Comment by ern** [comment]
Yeah typically you always want to use sakai's version of JS see PortalUtils and headscript for the JS version. A tool using a different version should really have some type of justification for doing so, as portal is loading jQuery ($PBJQ).

**Comment by kyleblythe** [comment]
Confirmed in 11.x maintenance branch: https://www.screencast.com/t/Ir6w6lqPHZ
