### ISSUE TITLE
On permissions page, null appears to be valid again

### ISSUE THREAD

**Issue by steveswinsburg** [sakaiproject/sakai#3874]
This needs a bit of investigation. The null entry appears to be valid again. Maybe something changed in Wicket.
![screen shot 2017-02-08 at 7 59 32 am](https://cloud.githubusercontent.com/assets/129129/22711275/a90c05fe-edd4-11e6-85ba-d8a465571e23.png)

**Comment by steveswinsburg** [comment]
Will investigate

**Comment by kyleblythe** [comment]
Confirmed in 11.x maintenance branch / trunk: 
![image](https://cloud.githubusercontent.com/assets/11447474/22888747/ceef5bfa-f1d4-11e6-8872-241971653fe9.png)
