### ISSUE TITLE
Updates to presentation and amount of text in "Categories & Weighting" section of Settings

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#3877]
Currently, there's a pretty massive chunk of blue info text sitting in the "Categories & Weighting" section of Settings:

![image](https://cloud.githubusercontent.com/assets/11447474/22742852/3fb66150-ede6-11e6-82d4-6bf97ac2e3ff.png)

To make the information here more contextual and easier to digest, can we do the following:

1) Provide the following text immediately below the "Categories & weighting" radio button (if either "Categories only" or "Categories & weighting are selected), above the checkboxes for drop highest / drop lowest / keep highest:

> Note:
> - If 'Categories & weighting' is enabled, uncategorized items will not be counted toward the course grade.
> - A category will only be visible if there is at least one Gradebook item assigned to it.

2) Remove "Enable" from the drop highest / drop lowest / keep highest labels.

3) Provide the following text beneath the drop highest / drop lowest / keep highest checkboxes:

> To apply drop highest, drop lowest, or keep highest to a category, all items in the category must have the same total point value.

4) When either drop highest or drop lowest AND keep highest are enabled, and a value has been entered in one of the columns for a category, we should apply hover text to the corresponding greyed out column for either drop highest, drop lowest, or keep highest that says:

> Drop highest / drop lowest cannot be used in the same category with keep highest.

5) Provide the following hover text for the mutually exclusive "Points" final grade selection and categories & weighting:

> 'Categories & weighting' is not compatible with the 'Points' final course grade display option.

With these updates, the blue info box is no longer needed.

**Comment by steveswinsburg** [comment]
@kyleblythe / @jeffpasch - can you please confirm if you indeed want standard tooltips via the 'title' attribute? How is this for accessibility? Here is a screenshot for changed 1-4. I didn't add the 'Note' or bullet points for item 1 as we don't have that elsewhere where we have multi line notes. But can do if desired.

![screen shot 2017-02-14 at 12 16 38 am](https://cloud.githubusercontent.com/assets/129129/22884853/0d821936-f24b-11e6-938a-0ddb4f05508c.png)

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

This looks much better - thank you! I agree that we don't need the "note" or bullet points here.

@payten might be able to speak better to the accessibility of the tooltips. I think there are ways to provide ARIA roles for tooltips to ensure they get captured by screenreaders, right?

**Comment by steveswinsburg** [comment]
Are we ok to proceed with the tooltips as is? I can provide the aria attributes on them.

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

Yep, ARIA tooltip attributes sound good - thanks!

**Comment by steveswinsburg** [comment]
Discussed 10/3/17: Title should be ok, perhaps add `aria-label`. Other option is to use a hidden label element but could be a bit overkill. Will test the tooltip and see how we go.

**Comment by steveswinsburg** [comment]
Ready to test sans the textbox adjustment in #3431.

**Comment by kyleblythe** [comment]
Confirmed in trunk: 
![image](https://cloud.githubusercontent.com/assets/11447474/25250232/c37a0a08-25e2-11e7-8b14-75465ede799a.png)
