### ISSUE TITLE
Category headers still inaccurate for some case

### ISSUE THREAD

**Issue by jonespm** [sakaiproject/sakai#3879]
So I saw this issue back in March on #1856 but an instance we have still has the category headers inaccurate in a site with the 11.2 version of GBNG (As of Nov 22nd) These are 2 categories

![image](https://cloud.githubusercontent.com/assets/27447/22746871/ea538a1c-edea-11e6-8ec5-7fbb7f6201eb.png)

However for the item NUR 223 Exam 1 it's under the header "Collaborative Exams" even though it is assigned in the Category Exams. This is the same for Collaborative Exam 1 which is in the Collaborative Exam column but in the Quizzes category header. 

![image](https://cloud.githubusercontent.com/assets/27447/22748190/e2255786-edee-11e6-9f75-da7fbe0e0599.png)

It appears fine in other areas an in Gradebook Classic. I wonder if a merge was missed somewhere or if this could still be a bug?

Update when I went to the Settings and gave the Collaborative Exams category 1% and saved it put them under the right header. Changing it back to 0% after seems like it kept it correct. I tried to reproduce on nightly with a 0% category and didn't seem to be able to reproduce the problem. Not sure what the issue here is but it's the first time I've seen it.

**Comment by steveswinsburg** [comment]
Can you reliably reproduce this?

**Comment by jonespm** [comment]
No, at the time I didn't see any way to reproduce this. I'm going to close for now, and if we get any more reports or a way to reproduce I'll re-open.
