### ISSUE TITLE
GradebookNG crashes when you type comma in a grade

### ISSUE THREAD

**Issue by juanarcadio** [sakaiproject/sakai#3930]
If you introduce comma ( **_,_** ) in a student grade GradebookNG crashes. (In all languages)

![1 input comma](https://cloud.githubusercontent.com/assets/10826639/23062239/3ef04706-f505-11e6-932c-0fe611eb0291.png)
![2 something wen wrong](https://cloud.githubusercontent.com/assets/10826639/23062238/3eef74e8-f505-11e6-92c6-621696bfa8a5.png)

```
Caused by: java.lang.NumberFormatException: For input string: "7,5"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.sakaiproject.gradebookng.tool.panels.GradeItemCellPanel$4.onUpdate(GradeItemCellPanel.java:211)
	...
```
This bug is quite severe in countries where comma ( **_,_** ) is used as decimal mark.
https://en.wikipedia.org/wiki/Decimal_mark#Hindu.E2.80.93Arabic_numeral_system

**Comment by PhilRancourt** [comment]
https://github.com/sakaiproject/sakai/issues/3375

**Comment by steveswinsburg** [comment]
I note that Assignments returns an error when the comma is being used. Do we have consistent handling across Sakai for this? Perhaps for now I just fix the error?
![screen shot 2017-03-06 at 11 37 33 am](https://cloud.githubusercontent.com/assets/129129/23593313/68346f7a-0261-11e7-88ce-b7b136e5bb4d.png)

**Comment by steveswinsburg** [comment]
Ignore above. I should be able to fix this pretty easy as I have access to the locale and the validation can be made is locale aware. So if in a locale where `,` is used, it will allow it.

**Comment by steveswinsburg** [comment]
I've done some testing on the other tools for this.

In Locale where decimal is `.` entering `99.0` is ok.
In Locale where decimal is `.` entering `99,0` results in an error.

In Locale where decimal is `,` entering `99,0` is ok.
In Locale where decimal is `,` entering `99.0` results in an error.

In both, entering multipel decimal points ie `99.9.9` or `99,9,9` results in an error.

I can either replicate this behaviour (easiest) or try to convert the number to a `.` decimal for storage and then back to `,` for display as required (harder).

**Comment by PhilRancourt** [comment]
I assume the Locale in GradeBookNG is set by the user using the language tab in the Preferences tool.

If so, the first option of validating the input with the locale is ok from my point of view. Converting every comma to a point would be great but not mandatory. However, the display must be in the user's locale.

**Comment by mpellicer** [comment]
Good morning, here is a PR proposal, works fine in all locales (Using comma or point).

**Comment by kyleblythe** [comment]
Confirmed in trunk: 

![image](https://cloud.githubusercontent.com/assets/11447474/25250166/89d591d2-25e2-11e7-8da3-152d8d806358.png)

**Comment by mpellicer** [comment]
@steveswinsburg @kyleblythe I've confirmed it's resolved in trunk now, can we close this again please?

Thanks
