### ISSUE TITLE
Showing question marks instead of value defined in localization properties in tabs label when change to uni-code languages(ex. JP)

### ISSUE THREAD

**Issue by saeidrastak** [sakaiproject/sakai#3965]
When i change my language to Japan, everything is fine except tab's label.
Showing question marks instead of value defined in localization properties in tabs label when change to uni-code languages(ex. JP)

![unicode-problem](https://cloud.githubusercontent.com/assets/7694285/23262705/e36f8ef0-f9f0-11e6-8a54-14ae487ed13c.png)

Related Jira issue:
[JIRA HPT-20 ](https://jira.sakaiproject.org/browse/HPT-20)

**Comment by jonespm** [comment]
Closing as it's filed in jira and unrelated to GBNG.

**Comment by saeidrastak** [comment]
What can i do for that?
