### ISSUE TITLE
GradebookNG german translation & datepicker

### ISSUE THREAD

**Issue by stendler** [sakaiproject/sakai#4161]
Due to the missing german translation the gradebookng tool cannot handle the german date format from the datepicker and thus it is not possible to create a new gradebook item with a due date.

(PR incoming)

**Comment by jonespm** [comment]
This was recently commented on here #4139 and I noticed GBNG was using the properties files for dates for some reason where older wicket tools (like Scorm and Profile2) were using a better system defined method. I don't think we should be having these in the properties files, as having values like this in properties needed for logic can cause a problem for some debugging features and it also requires every language be defined even if it's just for this. (And they're already already defined in java locales)

**Comment by steveswinsburg** [comment]
Thanks. Merged. However it sounds like the datepicker needs to be updated as per #4139.
