### ISSUE TITLE
Custom Grade Scales not Sorted Properly

### ISSUE THREAD

**Issue by kenaragon** [sakaiproject/sakai#4200]
Grade scales are not sorted properly. Doesn't look to use the GB_GRADING_SCALE_GRADES_T.grade_idx column for placement.  Attached is an image of the same scale in gb classic and gbng.

![scaleorder](https://cloud.githubusercontent.com/assets/1615915/24632412/dfd6c230-1878-11e7-8d86-80c32b6c95e0.png)

**Comment by jonespm** [comment]
Looks like the class LetterGradeComparator does the sorting here, and it has a few possible differences. If the first character matches (in the case of WP and WF) and no + or - it just returns it as a match. It looks like the older edu-services CourseGradeRecord comparator compared straight percents.

**Comment by kenaragon** [comment]
There is also the GB_GRADING_SCALE_GRADES_T.grade_idx column that works for placement as well.  I've used this for placement in GB2 and Classic.  I just changed this on the same example and moved the WF grade above the WP grade.
![sat-unsat-scale](https://cloud.githubusercontent.com/assets/1615915/24633645/6a5bff42-187e-11e7-8f4c-7a45420705ab.png)

**Comment by mpellicer** [comment]
Here is a PR proposal sorting the custom scales by value (Percents).

https://github.com/sakaiproject/sakai/pull/4211

The current scale sorting implementation is not optimal and i've tried to respect it, feedback really appreciated.

**Comment by steveswinsburg** [comment]
@kenaragon The current sort is based on the letter grade. I don't think anything uses the index column. Looks like that would be a good sort order to have though, since your letter grades have a custom sort not a natural one.

**Comment by ddelblanco** [comment]
IMO there is the need to rethink about how the scales and the custom scales are managed by the code.

I've seen things in the code like this:

if (ArrayUtils.contains(new String[] { "F", "NP", "F (0)" }, entry.getGrade())) {
					minPercent.setEnabled(false);
				}

or this:

if (StringUtils.equals(gradingScaleName, "Pass / Not Pass")) {

that rely in the name of the scale or the name of the grade... that means that if you change the name from "Pass / Not Pass"  "Pass / Fail" it will work in a different way. 

Or if you have a scale with a grade called "F" or "NP" but it is an F from "Fantastic".... you will have problem.

The code should be generic and if we want some scales to work in a special way, or the last value of the scale to work in a special way, we should be able to mark all the scales or values that we want to behave in that way... independently of the name, with a new "type" parameter or any other way that we can imagine, but never based in hardcoded string values.

**Comment by steveswinsburg** [comment]
You can't change the name, it's hardcoded in the GradebookService and then propagated into the database and everywhere else as the ID of the grading schema. This was an unfortunate design decision made by whoever created that code some time ago.

Happy to discuss approaches that can resolve this.

**Comment by ncaidin** [comment]
Tried testing on 11.x nightly MySQL and it doesn't seem to be working.

Steps:

1) Go to Gradebook Settings -> Gradebook Schema
2) Change A+ to 77 and C+ to 100 (switching grades, so to speak)
3) Save

Shouldn't we expect to see C+ go to the top of the grading schema and A+ move to where C+ had been?
Thanks

**Comment by mpellicer** [comment]
@ncaidin This change doesn't affects the letter grades scale nor grade points not pass/not pass, only affects other scales. That's why it doesn't order by value.

Miguel

**Comment by ncaidin** [comment]
@mpellicer how do you set up a different scale? I don't see any option in the GUI.

**Comment by mpellicer** [comment]
@ncaidin 
https://github.com/sakaiproject/sakai/blob/master/gradebook/xdocs/add_custom_grade_mappings.txt

I think you tried it in https://jira.sakaiproject.org/browse/SAK-32486, it's a bit hard because requires a server configuration & restart.. Maybe it's time to update the default gradebook scales to add all the cases.

**Comment by steveswinsburg** [comment]
I'm going to close this one out. If we want more changes we need a new ticket.
