### ISSUE TITLE
Equals compares the same objects

### ISSUE THREAD

**Issue by lifove** [sakaiproject/sakai#4272]
Hi

I've found a following issue in sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EntityBrokerEventRegistry.java

```
271                         EventLocaleKey o = (EventLocaleKey) obj;
272                         if(o.getEventId().equals(getEventId())
273                                         && o.getLocale().equals(o.getLocale())) {
274                                 return true;
```
In Line 273, o.getLocale().equals(o.getLocale())) should be o.getLocale().equals(**getLocale()**))? This might be trivial, bug wanted to report just in case. Thanks!

**Comment by jonespm** [comment]
Hi @lifove I filed this on our [jira  ](https://jira.sakaiproject.org/browse/SAK-32459) and I'll submit a PR on your behalf. This issue tracker is just temporary for issues related to gradebook. If you wanted to contribute other fixes directly please see our [page on contributing.](https://github.com/sakaiproject/sakai/blob/master/CONTRIBUTING.md
)

Thanks for the find.
