### ISSUE TITLE
Section/Group Dropdown and "Showing [x] Students" Text Not Aligned Horizontally

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#4284]
The section/group dropdown in the "Grades" screen, as well as the "Showing [x] Students" text, appear to be aligned to the _top_ of their grey container, causing them to butt up against the "Add Gradebook Item" button. This makes things at the top of the Grades screen feel a little cramped:

![image](https://cloud.githubusercontent.com/assets/11447474/25183359/59091cc0-24e5-11e7-8df7-6a78d9a83a41.png)

Can we center these horizontally within the grey container, so that they're horizontally aligned with the "Showing [x] of [y] items" text, Show/Hide Items menu, and Group by Category buttons?

**Comment by jeffpasch** [comment]
Confirmed in master. 
![2017-05-05_09-49-50](https://cloud.githubusercontent.com/assets/11447476/25748202/57378a5e-3178-11e7-8625-10e451ab277e.png)

**Comment by ncaidin** [comment]
Verified on 11.x nightly MySQL server.  Set any label on this to show status?  (we show in Jira if we have verified the fix in the branch, so just asking)
