### ISSUE TITLE
Make "Letter Grade" and "Percentage" the default final grade release selections

### ISSUE THREAD

**Issue by kyleblythe** [sakaiproject/sakai#4285]
In GB Classic, the final course grade always displayed as a letter grade + percentage. Currently, when you first select the "Display final course grade to students" option in Settings, only letter grade is selected.

Can we make it so that letter grade and percentage are the default selections?

**Comment by kyleblythe** [comment]
Confirmed in trunk: 
![image](https://cloud.githubusercontent.com/assets/11447474/25748112/055cb196-3178-11e7-8287-4db7039ee681.png)

**Comment by ncaidin** [comment]
Tested and Verified on nightly 11.x MySQL server.  Is there an indicator on the issue (like a label) I should set to show this?
Thanks.
