### ISSUE TITLE
Freeze pane

### ISSUE THREAD

**Issue by Itenium** [sakaiproject/sakai#4435]
Good day.

In Sakai, one needs to often go back to the top of a page.  For example, if one is in lessons, and the lesson get to long.

It would be nice that the top frame and side frame can be frozen, that one return to them at any stage.

For a example look at https://www.w3schools.com/css/default.asp

On this website the side frame and top frame are frozen, which make navigation much simpler.

I would suggest that the frame be frozen below the "Home, Overview" part of the attached file. 
![freeze pains](https://cloud.githubusercontent.com/assets/22473524/26252238/fb919fe4-3caf-11e7-97fb-4db75a61fd0d.JPG)

Thank you for your assistance.

Regards

**Comment by bjones86** [comment]
@Itenium, the Sakai community only uses GitHub issues for GradebookNG. All other bugs, feature requests, etc., should be filed in the community JIRA: https://jira.sakaiproject.org.

If you would like to see this feature added to a future version of Sakai, please open a feature request ticket in the community JIRA.

Thanks.
